import assert from 'node:assert/strict';
import {test,beforeEach} from 'node:test';
import {registerHooks} from 'node:module';
import {readFileSync,existsSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import ts from 'typescript';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../../../..');
let tables,failTable,context,writes,invalidations;
const db={from(table){let filters=[],op='read',payload,options={};const query={select(){return query;},eq(k,v){filters.push(r=>r[k]===v);return query;},neq(k,v){filters.push(r=>r[k]!==v);return query;},in(k,v){filters.push(r=>v.includes(r[k]));return query;},not(k,op,v){filters.push(r=>r[k]!==v);return query;},update(v){op='update';payload=v;return query;},upsert(v,o){op='upsert';payload=v;options=o;return query;},delete(){op='delete';return query;},single(){return run(true);},maybeSingle(){return run(true);},then(yes,no){return run(false).then(yes,no);}};async function run(single){const rows=tables[table]??[];let matches=rows.filter(r=>filters.every(fn=>fn(r)));if(op!=='read'){writes.push({table,op});if(failTable===table)return {data:null,error:new Error('fixture failure')};if(op==='update')matches.forEach(r=>Object.assign(r,structuredClone(payload)));if(op==='upsert'){const row=rows.find(r=>r.assessment_id===payload.assessment_id&&r.section_key===payload.section_key);if(row&&!options.ignoreDuplicates)Object.assign(row,structuredClone(payload));if(!row){const added={...structuredClone(payload)};tables[table]=[...rows,added];matches=[added];}}}return {data:structuredClone(single?matches[0]??null:matches),error:null};}return query;}};
globalThis.__lmuCompletionFixture={db,context:()=>context,invalidate:()=>invalidations++};
const mocks={'./server/account':'export const resolveAuthenticatedParticipant=async()=>globalThis.__lmuCompletionFixture.context();','@/lib/supabase/admin':'export const createAdminSupabaseClient=()=>globalThis.__lmuCompletionFixture.db;','@/lib/experiences/access/server':'export const requireExperiencePasswordBySlug=async()=>{};','server-only':'export {};','next/cache':'export const revalidatePath=()=>globalThis.__lmuCompletionFixture.invalidate();','next/server':'export const NextResponse=Response;','@/lib/experiences/lmu/server/account':'export const resolveAuthenticatedParticipant=async()=>globalThis.__lmuCompletionFixture.context();'};
registerHooks({resolve(s,c,n){if(mocks[s])return {url:`mock:${s}`,shortCircuit:true};let path;if(s.startsWith('@/'))path=resolve(root,s.slice(2));else if(s.startsWith('.')&&c.parentURL?.startsWith('file:'))path=resolve(dirname(fileURLToPath(c.parentURL)),s);if(path&&!existsSync(path)&&existsSync(path+'.ts'))path+='.ts';if(path&&existsSync(path))return {url:pathToFileURL(path).href,shortCircuit:true};return n(s,c);},load(url,c,n){if(url.startsWith('mock:'))return {format:'module',source:mocks[url.slice(5)],shortCircuit:true};if(url.endsWith('.ts'))return {format:'module',source:ts.transpileModule(readFileSync(fileURLToPath(url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText,shortCircuit:true};return n(url,c);}});
const {LMU_SECTION_KEYS}=await import('./constants.ts');
const {finalizeAssessmentIfComplete}=await import('./completion.ts');
const finalRoute=await import('../../../../app/api/lmu/sections/[sectionKey]/finalize/route.ts');
const draftRoute=await import('../../../../app/api/lmu/sections/[sectionKey]/route.ts');
const order=['skills','location','teammates','supervisor','growth','values','x-factor','salary'];
const post=(responseData={orderedMotivatorIds:order},resultData={result:{summary:'Fixture snapshot'}})=>finalRoute.POST(new Request('http://fixture/section/finalize',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({responseData,resultData})}),{params:Promise.resolve({sectionKey:'motivator_rankings'})});
beforeEach(()=>{tables={lmu_assessments:[{id:'a',participant_id:'p',status:'in_progress',completed_at:null}],lmu_section_progress:LMU_SECTION_KEYS.slice(0,-1).map(section_key=>({assessment_id:'a',section_key,status:'completed',completed_at:'2026-10-01T12:00:00Z'})),embedded_assessment_attempts:[],experience_enrollments:[],lmu_results:[]};failTable=null;writes=[];invalidations=0;context={admin:db,participant:{id:'p'},assessment:tables.lmu_assessments[0]};});
test('LMU final action validates ranking and creates no state after incorrect input',async()=>{assert.equal((await post({orderedMotivatorIds:['skills']})).status,400);assert.equal(writes.length,0);});
test('LMU final save persists actual snapshot and confirms completion',async()=>{const response=await post();assert.equal(response.status,200);assert.equal((await response.json()).assessmentCompleted,true);assert.equal(tables.lmu_assessments[0].status,'completed');assert.ok(invalidations);});
test('LMU response failure cannot write completed result or progress',async()=>{failTable='lmu_responses';assert.equal((await post()).status,500);assert.equal(tables.lmu_results.length,0);assert.equal(tables.lmu_section_progress.length,9);});
test('LMU result failure cannot complete assessment and can be retried',async()=>{failTable='lmu_results';assert.equal((await post()).status,500);assert.equal(tables.lmu_assessments[0].status,'in_progress');failTable=null;assert.equal((await post()).status,200);});
test('LMU repeated clicks retain immutable result and original completion dates',async()=>{await post();const result=structuredClone(tables.lmu_results[0]),date=tables.lmu_assessments[0].completed_at;await post({orderedMotivatorIds:order},{result:{summary:'Edited'}});assert.deepEqual(tables.lmu_results[0],result);assert.equal(tables.lmu_assessments[0].completed_at,date);});
test('embedded LMU completes child enrollment, never its parent or another participant',async()=>{tables.embedded_assessment_attempts=[{id:'attempt',provider_attempt_id:'a',participant_id:'p',assessment_enrollment_id:'child',status:'in_progress'},{id:'other',provider_attempt_id:'a',participant_id:'other',assessment_enrollment_id:'private',status:'in_progress'}];tables.experience_enrollments=[{id:'child',participant_id:'p',status:'in_progress'},{id:'parent',participant_id:'p',status:'in_progress'},{id:'private',participant_id:'other',status:'in_progress'}];await post();assert.equal(tables.experience_enrollments[0].status,'completed');assert.equal(tables.experience_enrollments[1].status,'in_progress');assert.equal(tables.experience_enrollments[2].status,'in_progress');assert.equal(tables.embedded_assessment_attempts[1].status,'in_progress');});
test('retry reconciles embedded enrollment after failure without replacing snapshot',async()=>{tables.embedded_assessment_attempts=[{id:'attempt',provider_attempt_id:'a',participant_id:'p',assessment_enrollment_id:'child',status:'completed'}];tables.experience_enrollments=[{id:'child',participant_id:'p',status:'in_progress'}];failTable='experience_enrollments';assert.equal((await post()).status,500);const result=structuredClone(tables.lmu_results[0]);failTable=null;await post();assert.deepEqual(tables.lmu_results[0],result);assert.equal(tables.experience_enrollments[0].status,'completed');});
test('LMU all required sections must be complete',async()=>{tables.lmu_section_progress=[];const result=await finalizeAssessmentIfComplete(db,'a','2026-10-02');assert.equal(result.completed,false);assert.equal(writes.length,0);});
test('LMU Save Draft does not complete and cannot overwrite completed section progress',async()=>{const response=await draftRoute.PUT(new Request('http://fixture/section',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({responseData:{text:'draft'},progress:{status:'completed'}})}),{params:Promise.resolve({sectionKey:'values'})});assert.equal(response.status,200);assert.equal(tables.lmu_assessments[0].status,'in_progress');assert.equal(tables.lmu_section_progress.find(r=>r.section_key==='values').completed_at,'2026-10-01T12:00:00Z');});
test('LMU completed assessment reset preserves historical result',async()=>{tables.lmu_assessments[0].status='completed';assert.equal((await draftRoute.DELETE(new Request('http://fixture/section'),{params:Promise.resolve({sectionKey:'values'})})).status,409);assert.equal(writes.length,0);});
test('unauthenticated LMU final action writes nothing',async()=>{context=null;assert.equal((await post()).status,401);assert.equal(writes.length,0);});

test('LMU missing source modules reject final response before creating a snapshot',async()=>{tables.lmu_section_progress=[];assert.equal((await post()).status,400);assert.equal(writes.length,0);});

const {confirmedLmuReturnAction}=await import('../completion-actions.ts');
const {resolveEmbeddedAssessmentReturnContext}=await import('../../builder/embedded-assessment-context.ts');
const {listCompletedAssessmentResults,loadCompletedAssessmentResult}=await import('../../../assessment-results.ts');
const {projectStartSomethingSave,emptyStartSomethingData}=await import('../../builder/start-something.ts');
const returnPath='/experiences/parent-course/course/module/lesson/section';
function embeddedFixture(){tables.embedded_assessment_attempts=[{id:'attempt',provider_attempt_id:'a',participant_id:'p',assessment_enrollment_id:'child',assessment_experience_id:'assessment',parent_enrollment_id:'parent',parent_content_block_id:'block',status:'completed'}];tables.experience_enrollments=[{id:'child',participant_id:'p',status:'completed',completed_at:'2026-10-02'},{id:'parent',participant_id:'p',experience_id:'course',status:'in_progress'}];tables.content_blocks=[{id:'block',block_type:'prebuilt_assessment',section_id:'section'}];tables.experience_sections=[{id:'section',section_key:'section',module_id:'module',lesson_id:'lesson'}];tables.experience_modules=[{id:'module',module_key:'module'}];tables.experience_lessons=[{id:'lesson',lesson_key:'lesson'}];tables.experiences=[{id:'course',slug:'parent-course'}];}
test('confirmed standalone LMU completion returns to Dashboard',async()=>{await post();assert.equal((await confirmedLmuReturnAction()).destination,'/dashboard');});
test('course-launched completion returns to its owned parent with cohort context',async()=>{embeddedFixture();await post();const path=returnPath+'?cohort=24fd0477-2a16-4ca1-98bb-c090931895c3';assert.equal((await confirmedLmuReturnAction('attempt',path)).destination,path);assert.equal(tables.experience_enrollments[1].status,'in_progress');});
test('unconfirmed LMU completion or incomplete child enrollment cannot claim success',async()=>{await assert.rejects(confirmedLmuReturnAction());embeddedFixture();tables.lmu_assessments[0].status='completed';tables.lmu_assessments[0].completed_at='2026-10-02';tables.experience_enrollments[0].status='in_progress';await assert.rejects(confirmedLmuReturnAction('attempt',returnPath));});
test('course-return context rejects another participant, another assessment, and external URLs',async()=>{embeddedFixture();const args={attemptId:'attempt',candidateReturnTo:returnPath,participantId:'p',assessmentEnrollmentId:'child',assessmentExperienceId:'assessment'};assert.equal(await resolveEmbeddedAssessmentReturnContext(args),returnPath);assert.equal(await resolveEmbeddedAssessmentReturnContext({...args,participantId:'other'}),null);assert.equal(await resolveEmbeddedAssessmentReturnContext({...args,assessmentExperienceId:'other'}),null);assert.equal(await resolveEmbeddedAssessmentReturnContext({...args,candidateReturnTo:'https://evil.invalid'}),null);assert.equal(await resolveEmbeddedAssessmentReturnContext({...args,candidateReturnTo:'/experiences/other-course/course/module/lesson/section'}),null);});
function genericFixture(completed=false){const draft=emptyStartSomethingData();draft.idea.idea_summary='Immutable idea';const envelope=projectStartSomethingSave({},draft,true,'2026-10-02T12:00:00Z');tables.lmu_assessments=[];tables.response_definitions=[{id:'d',response_key:'start_something'}];tables.participant_responses=[{id:'result',participant_id:'p',enrollment_id:'e',experience_version_id:'v',response_definition_id:'d',response_data:envelope,status:'submitted',finalized_at:envelope.finished.completedAt}];tables.experience_enrollments=[{id:'e',participant_id:'p',experience_id:'x',experience_version_id:'v',status:completed?'completed':'in_progress',completed_at:completed?'2026-10-02T12:00:01Z':null}];tables.experience_enrollment_version_history=[];}
test('saved snapshot pending enrollment completion is neither listed nor viewable as completed',async()=>{genericFixture();assert.deepEqual(await listCompletedAssessmentResults('p'),[]);assert.equal(await loadCompletedAssessmentResult('p','start-something','result'),null);});
test('canonical result remains available after reload; another participant cannot list or view it',async()=>{genericFixture(true);assert.equal((await listCompletedAssessmentResults('p')).length,1);assert.equal((await loadCompletedAssessmentResult('p','start-something','result')).data.idea.idea_summary,'Immutable idea');assert.deepEqual(await listCompletedAssessmentResults('other'),[]);assert.equal(await loadCompletedAssessmentResult('other','start-something','result'),null);});
test('retake preserves immutable historical results while new enrollment is active',async()=>{genericFixture();tables.experience_enrollments[0].experience_version_id='v2';tables.experience_enrollment_version_history=[{id:'history',participant_id:'p',enrollment_id:'e',experience_id:'x',experience_version_id:'v',artifact_snapshot:{completion:{completed_at:'2026-10-02T12:00:01Z'}}}];assert.equal((await listCompletedAssessmentResults('p')).length,1);assert.equal((await loadCompletedAssessmentResult('p','start-something','result')).data.idea.idea_summary,'Immutable idea');});
