"use client";

import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { LMU_ORIGINAL_EXPERIENCE_ID } from "@/lib/experiences/lmu/original-journey";
import type { LMUInstructionalMedia } from "@/lib/experiences/lmu/types";
import { challengeGrowthItems, growthCategoryLabels, professionalGrowthItems, trainingGrowthItems, type GrowthCategory, type GrowthCurriculumItem } from "@/modules/lmu/growth/curriculum";
import { completeGrowth, emptyGrowthResponse, resolveGrowthCandidates, saveGrowthResponse } from "@/modules/lmu/growth/storage";
import type { GrowthCandidate, GrowthResponse, GrowthScreen } from "@/modules/lmu/growth/types";
import { LMUBadgeIcon } from "./icons/badge/LMUBadgeIcon";
import { LMUInstructionalVideo } from "./LMUInstructionalVideo";
import { LMUScreenHeading } from "./LMUScreenHeading";
import { LMUShell } from "./LMUShell";
import { MapAccent } from "./MapAccent";
import { ModuleStartOverControl } from "./ModuleStartOverControl";
import { useOriginalProgress } from "./useOriginalProgress";
import { usePageStart } from "./usePageStart";
import { LMUFinalMoveControls, LMUFinalSelectionGroup, LMUFinalSelectionRow } from "./LMUFinalSelectionReview";

const categories: GrowthCategory[] = ["professional", "training", "challenge"];
const itemsByCategory: Record<GrowthCategory, GrowthCurriculumItem[]> = { professional: professionalGrowthItems, training: trainingGrowthItems, challenge: challengeGrowthItems };
const categoryQuestions: Record<GrowthCategory, string> = { professional: "Where do you want to increase your capability, responsibility, or contribution?", training: "What knowledge, instruction, or skill development would help you move forward?", challenge: "Where are you ready to stretch beyond what is currently comfortable or familiar?" };
const customPrompts: Record<GrowthCategory, string> = { professional: "What professional growth would you like to pursue that is not represented above?", training: "What other training or learning experience would help you grow?", challenge: "What challenge would stretch you in a meaningful way?" };

export function GrowthModule({ media }: { media?: Record<string, LMUInstructionalMedia> }) {
  const progress = useOriginalProgress(); const moduleProgress = progress.find((item) => item.moduleId === "growth");
  const response: GrowthResponse = moduleProgress ? { ...emptyGrowthResponse(), ...(moduleProgress.responses as unknown as Partial<GrowthResponse>) } : emptyGrowthResponse();
  const screen = response.resumeScreen; const headingRef = useRef<HTMLHeadingElement>(null); const router = useRouter();
  const [customDrafts, setCustomDrafts] = useState<Record<GrowthCategory, string>>({ professional: "", training: "", challenge: "" });
  const [pendingPriorityId, setPendingPriorityId] = useState<string | null>(null);
  const [expandedDetailIds, setExpandedDetailIds] = useState<Set<string>>(() => new Set());
  const [expandedBoardDetailIds, setExpandedBoardDetailIds] = useState<Set<string>>(() => new Set());
  usePageStart(screen, headingRef);
  const candidates = resolveGrowthCandidates(response);
  const finalCandidates = response.finalTopFiveIds.flatMap((id) => { const candidate = candidates.find((item) => item.id === id); return candidate ? [candidate] : []; });

  function save(next: GrowthResponse) { saveGrowthResponse(next); }
  function go(next: GrowthScreen, patch: Partial<GrowthResponse> = {}) { if (next === "board") setExpandedBoardDetailIds(new Set()); save({ ...response, ...patch, resumeScreen: next }); }
  function toggleCandidate(id: string) { const selectedCandidateIds = response.selectedCandidateIds.includes(id) ? response.selectedCandidateIds.filter((item) => item !== id) : [...response.selectedCandidateIds, id]; save({ ...response, selectedCandidateIds, finalTopFiveIds: response.finalTopFiveIds.filter((item) => selectedCandidateIds.includes(item)), finalizedAt: undefined }); }
  function updateDetail(id: string, detail: string) { save({ ...response, candidateDetails: { ...response.candidateDetails, [id]: detail.slice(0, 160) }, finalizedAt: undefined }); }
  function toggleDetail(id: string) { setExpandedDetailIds((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }
  function toggleBoardDetail(id: string) { setExpandedBoardDetailIds((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }
  function addCustom(category: GrowthCategory) { const displayLabel = customDrafts[category].trim(); const existing = response.customCandidates.filter((item) => item.sourceCategory === category); if (!displayLabel || existing.length >= 2) return; const id = [`${category}-custom-1`, `${category}-custom-2`].find((candidateId) => !existing.some((item) => item.id === candidateId))!; const custom = { id, sourceCategory: category, sourceType: "custom" as const, displayLabel }; save({ ...response, customCandidates: [...response.customCandidates, custom], selectedCandidateIds: [...response.selectedCandidateIds, id], finalizedAt: undefined }); setCustomDrafts((current) => ({ ...current, [category]: "" })); }
  function removeCandidate(id: string) { save({ ...response, selectedCandidateIds: response.selectedCandidateIds.filter((item) => item !== id), customCandidates: response.customCandidates.filter((item) => item.id !== id), finalTopFiveIds: response.finalTopFiveIds.filter((item) => item !== id), finalizedAt: undefined }); }
  function updateCustom(id: string, displayLabel: string) { save({ ...response, customCandidates: response.customCandidates.map((item) => item.id === id ? { ...item, displayLabel: displayLabel.slice(0, 120) } : item), finalizedAt: undefined }); }
  function continueArea(category: GrowthCategory) { const completedAreas = [...new Set([...response.completedAreas, category])]; const index = categories.indexOf(category); go(index < 2 ? categories[index + 1] : "board", { completedAreas }); }
  function beginPriorities() { if (candidates.length < 5) return; go("prioritize", { finalTopFiveIds: candidates.length === 5 ? candidates.map((item) => item.id) : response.finalTopFiveIds.filter((id) => candidates.some((item) => item.id === id)).slice(0, 5) }); }
  function choosePriority(id: string) { const index = response.finalTopFiveIds.indexOf(id); if (index >= 0) { save({ ...response, finalTopFiveIds: response.finalTopFiveIds.slice(0, index), finalizedAt: undefined }); return; } if (response.finalTopFiveIds.length === 5) { setPendingPriorityId(id); return; } save({ ...response, finalTopFiveIds: [...response.finalTopFiveIds, id], finalizedAt: undefined }); }
  function replacePriority(index: number) { if (!pendingPriorityId) return; const ids = [...response.finalTopFiveIds]; ids[index] = pendingPriorityId; save({ ...response, finalTopFiveIds: ids, finalizedAt: undefined }); setPendingPriorityId(null); }
  function movePriority(index: number, direction: -1 | 1) { const ids = [...response.finalTopFiveIds]; const target = index + direction; if (target < 0 || target >= ids.length) return; [ids[index], ids[target]] = [ids[target], ids[index]]; save({ ...response, finalTopFiveIds: ids, finalizedAt: undefined, resumeScreen: "review" }); }
  function confirm() { if (response.finalTopFiveIds.length === 5) go("final", { finalizedAt: new Date().toISOString() }); }
  function finish() { completeGrowth(response); router.push("/experiences/life-mapping-u/original"); }
  const startOver = <ModuleStartOverControl experienceId={LMU_ORIGINAL_EXPERIENCE_ID} moduleId="growth" moduleHref="/experiences/life-mapping-u/module/growth" />;

  function renderPathwayNav(active: GrowthCategory) { return <ol className="growth-pathway-nav" aria-label="Growth areas">{categories.map((category) => { const completed = response.completedAreas.includes(category); const state = category === active ? "current" : completed ? "active" : "light"; return <li className={category === active ? "is-current" : completed ? "is-complete" : ""} key={category}><LMUBadgeIcon name="growth" state={state} size={40} /><span>{growthCategoryLabels[category]}</span></li>; })}</ol>; }
  function renderArea(category: GrowthCategory) { const items = itemsByCategory[category]; const customCount = response.customCandidates.filter((item) => item.sourceCategory === category).length; return <main className="teammates-shell growth-area">{renderPathwayNav(category)}<div className="teammates-screen-heading"><LMUBadgeIcon name="growth" state="current" size={72} label="Growth" /><LMUScreenHeading eyebrow={`Growth · ${growthCategoryLabels[category]}`} title={categoryQuestions[category]} description="Select anything that genuinely resonates. You will narrow your combined ideas to five later." headingRef={headingRef} /></div><div className="growth-selected-count" role="status">Selected {candidates.filter((item) => item.sourceCategory === category).length}</div><section className="growth-choice-list">{items.map((item) => { const selected = response.selectedCandidateIds.includes(item.id); const expanded = expandedDetailIds.has(item.id); return <article className={selected ? "is-selected" : ""} key={item.id}><button type="button" aria-pressed={selected} onClick={() => toggleCandidate(item.id)}><span aria-hidden="true">{selected ? "✓" : ""}</span>{item.displayLabel}</button>{selected && item.detailPrompt && <div className="growth-detail"><button type="button" aria-expanded={expanded} onClick={() => toggleDetail(item.id)}>{expanded ? "− Hide Detail" : response.candidateDetails[item.id] ? "+ Edit Detail" : "+ Add More Detail"}</button>{expanded && <label><b>Optional</b><span>{item.detailPrompt}</span><input value={response.candidateDetails[item.id] ?? ""} onChange={(event) => updateDetail(item.id, event.target.value)} placeholder={item.detailPrompt} /></label>}</div>}</article>; })}</section><section className="growth-custom-composer"><p className="eyebrow">Add Your Own · Optional</p><label>Your Own Growth Idea<input value={customDrafts[category]} maxLength={120} onChange={(event) => setCustomDrafts((current) => ({ ...current, [category]: event.target.value }))} placeholder={customPrompts[category]} /></label><small>{category === "challenge" ? "For example: lead a difficult conversation or take responsibility for a larger project." : customPrompts[category]}</small><button type="button" disabled={!customDrafts[category].trim() || customCount >= 2} onClick={() => addCustom(category)}>+ Add to My Growth Ideas</button>{customCount >= 2 && <p>You have added the maximum of two ideas in this area.</p>}</section><div className="teammates-actions"><button className="story-cancel" type="button" onClick={() => go(category === "professional" ? "overview" : categories[categories.indexOf(category) - 1])}>← Back</button><button className="button button-primary" type="button" onClick={() => continueArea(category)}><span>{category === "challenge" ? "View My Growth Board" : `Continue to ${growthCategoryLabels[categories[categories.indexOf(category) + 1]]}`}</span><span aria-hidden="true">→</span></button></div>{startOver}</main>; }

  return <LMUShell context="Growth" theme="dark" journeyHref="/experiences/life-mapping-u/original">
    {screen === "introduction" && <main className="success-intro growth-intro"><section className="success-intro-copy teammates-intro-copy"><p className="eyebrow eyebrow-rule">Growth</p><h1 ref={headingRef} tabIndex={-1}>Where do you want to grow next?</h1><p className="success-intro-accent">Growth becomes more useful when you can put language around what you are ready to learn, develop, or stretch toward.</p>{media?.intro && <LMUInstructionalVideo {...media.intro} />}<div className="skills-reminders"><p className="eyebrow">Important Reminders</p><p>Identify the areas of growth, both professional and personal, that you are most eager to pursue.</p><p>Consider areas related to training, skill development, or stretching challenges. Be specific in your responses.</p><p><strong>Examples:</strong> “I want to learn fundraising.” “I want to grow in conflict management.”</p></div><button className="button button-primary" type="button" onClick={() => go("overview")}><span>Begin Growth</span><span aria-hidden="true">→</span></button>{startOver}</section><aside className="success-memory-panel teammates-intro-badge"><MapAccent density="tight" position="center" opacity={0.18} /><div><LMUBadgeIcon name="growth" state="current" size={112} label="Growth" context="dark" /><p className="eyebrow">A path of development</p><p>Notice where you are ready to learn, stretch, and move forward.</p></div></aside></main>}
    {screen === "overview" && <main className="teammates-shell growth-overview"><LMUScreenHeading eyebrow="Growth" title="Three Ways We Grow" description="Explore capability, learning, and meaningful challenge before choosing the five priorities that matter most." headingRef={headingRef} /><div className="growth-overview-path">{categories.map((category) => <section key={category}><LMUBadgeIcon name="growth" state="light" size={54} /><h2>{growthCategoryLabels[category]}</h2><p>{categoryQuestions[category]}</p></section>)}</div><button className="button button-primary" type="button" onClick={() => go("professional")}><span>Begin With Professional Growth</span><span aria-hidden="true">→</span></button>{startOver}</main>}
    {screen === "professional" && renderArea("professional")}{screen === "training" && renderArea("training")}{screen === "challenge" && renderArea("challenge")}
    {screen === "board" && <main className="teammates-shell growth-board"><LMUScreenHeading eyebrow="Growth" title="Your Growth Board" description="You identified several places where you are ready to learn, stretch, or develop. Now look across them together." headingRef={headingRef} />{categories.map((category) => <section key={category}><p className="eyebrow">{growthCategoryLabels[category]}</p>{candidates.filter((item) => item.sourceCategory === category).map((candidate) => { const expanded = expandedBoardDetailIds.has(candidate.id); return <article key={candidate.id}><LMUBadgeIcon name="growth" state="light" size={38} /><div>{candidate.sourceType === "custom" ? <input aria-label={`Edit ${growthCategoryLabels[category]} idea`} value={candidate.displayLabel} onChange={(event) => updateCustom(candidate.id, event.target.value)} /> : <strong>{candidate.displayLabel}</strong>}{candidate.detail && <p className="growth-board-detail">{candidate.detail}</p>}{candidate.detailPrompt && <><button className="growth-detail-action" type="button" aria-expanded={expanded} onClick={() => toggleBoardDetail(candidate.id)}>{expanded ? "− Close Edit" : candidate.detail ? "+ Edit Detail" : "+ Add More Detail"}</button>{expanded && <label className="growth-board-detail-editor"><span>Optional · {candidate.detailPrompt}</span><input aria-label={candidate.detailPrompt} value={response.candidateDetails[candidate.id] ?? ""} onChange={(event) => updateDetail(candidate.id, event.target.value)} placeholder={candidate.detailPrompt} /></label>}</>}</div><button type="button" onClick={() => removeCandidate(candidate.id)}>Remove</button></article>; })}</section>)}{candidates.length < 5 && <div className="skills-dependency"><strong>Choose at least five growth ideas before continuing.</strong><p>You currently have {candidates.length}. Return to any area to add more.</p></div>}<div className="growth-board-links">{categories.map((category) => <button key={category} type="button" onClick={() => go(category)}>Add or Edit {growthCategoryLabels[category]}</button>)}</div><button className="button button-primary" type="button" disabled={candidates.length < 5} onClick={beginPriorities}><span>Choose My Top 5 Growth Priorities</span><span aria-hidden="true">→</span></button>{startOver}</main>}
    {screen === "prioritize" && <main className="teammates-shell growth-prioritize"><LMUScreenHeading eyebrow="Growth" title="Which five growth priorities matter most?" description="Choose the priorities that matter most for the next season of your life and work. Your selection order becomes the initial priority order." headingRef={headingRef} /><div className="teammates-selected-count" role="status"><strong>Selected {response.finalTopFiveIds.length} of 5</strong><span>{response.finalTopFiveIds.length === 5 ? "Your five are ready to review." : `Choose ${5 - response.finalTopFiveIds.length} more.`}</span></div><section className="growth-priority-list">{candidates.map((candidate) => { const index = response.finalTopFiveIds.indexOf(candidate.id); return <button className={index >= 0 ? "is-selected" : ""} key={candidate.id} type="button" aria-pressed={index >= 0} aria-label={`${candidateLabel(candidate)}, ${index >= 0 ? `selected ${index + 1} of 5` : "not selected"}`} onClick={() => choosePriority(candidate.id)}><span>{index >= 0 ? index + 1 : ""}</span><div><strong>{candidateLabel(candidate)}</strong><small>{candidate.detail ? `${candidate.displayLabel} · ` : ""}{growthCategoryLabels[candidate.sourceCategory]}</small></div></button>; })}</section>{pendingPriorityId && <div className="custom-replacement"><p className="eyebrow">Choose a replacement</p><h2>Which growth priority should this replace?</h2>{finalCandidates.map((candidate, index) => <button key={candidate.id} type="button" onClick={() => replacePriority(index)}><span>{String(index + 1).padStart(2, "0")}</span>{candidateLabel(candidate)}</button>)}<button className="review-replace-cancel" type="button" onClick={() => setPendingPriorityId(null)}>Cancel</button></div>}<div className="teammates-actions"><button className="story-cancel" type="button" onClick={() => go("board")}>← Back to Growth Board</button><button className="button button-primary" type="button" disabled={response.finalTopFiveIds.length !== 5} onClick={() => go("review")}><span>Review My Top 5</span><span aria-hidden="true">→</span></button></div>{startOver}</main>}
    {screen === "review" && <main className="teammates-shell"><LMUScreenHeading eyebrow="Growth" title="Your Top 5 Growth Priorities" description="Review and adjust the order so it feels useful for your next season." headingRef={headingRef} /><LMUFinalSelectionGroup label="Your Top 5">{finalCandidates.map((candidate, index) => <LMUFinalSelectionRow key={candidate.id} rank={index + 1} total={5} title={candidateLabel(candidate)} badge={<LMUBadgeIcon name="growth" state="active" size={54} label="Growth" />} context={<p>{candidate.detail ? `${candidate.displayLabel} · ` : ""}{growthCategoryLabels[candidate.sourceCategory]}</p>} actions={<LMUFinalMoveControls title={candidateLabel(candidate)} index={index} lastIndex={4} onMove={(direction) => movePriority(index, direction)} />} />)}</LMUFinalSelectionGroup><button className="button button-primary" type="button" onClick={confirm}><span>Confirm My Growth Priorities</span><span aria-hidden="true">✓</span></button>{startOver}</main>}
    {screen === "final" && <main className="teammates-shell teammate-final"><LMUScreenHeading eyebrow="Growth" title="Your Top 5 Growth Priorities" description="These are the places where you are most ready to learn, develop, and stretch forward." headingRef={headingRef} /><ol>{finalCandidates.map((candidate, index) => <li key={candidate.id}><span>{String(index + 1).padStart(2, "0")}</span><LMUBadgeIcon name="growth" state="active" size={58} label="Growth" /><div><h2>{candidateLabel(candidate)}</h2><p>{candidate.detail ? `${candidate.displayLabel} · ` : ""}{growthCategoryLabels[candidate.sourceCategory]}</p></div></li>)}</ol><button className="button button-primary" type="button" onClick={finish}><span>Finish Section</span><span aria-hidden="true">→</span></button>{startOver}</main>}
  </LMUShell>;
}

function candidateLabel(candidate: GrowthCandidate) { return candidate.detail || candidate.displayLabel; }
