"use client";

import { useRef, useState, type ReactNode, type RefObject } from "react";
import { useRouter } from "next/navigation";
import { LMU_ORIGINAL_EXPERIENCE_ID } from "@/lib/experiences/lmu/original-journey";
import type { LMUInstructionalMedia } from "@/lib/experiences/lmu/types";
import { locationConstraints, locationReasons, relocationLabel, relocationOptions } from "@/modules/lmu/location/curriculum";
import { completeLocation, emptyLocationResponse, saveLocationResponse } from "@/modules/lmu/location/storage";
import type { LocationPreference, LocationResponse, LocationScreen, PrioritizedLocationReason, RelocationOpenness } from "@/modules/lmu/location/types";
import { LMUBadgeIcon } from "./icons/badge/LMUBadgeIcon";
import { LMUInstructionalVideo } from "./LMUInstructionalVideo";
import { LMUScreenHeading } from "./LMUScreenHeading";
import { LMUShell } from "./LMUShell";
import { MapAccent } from "./MapAccent";
import { ModuleStartOverControl } from "./ModuleStartOverControl";
import { useOriginalProgress } from "./useOriginalProgress";
import { usePageStart } from "./usePageStart";

const normalizeLocation = (value: string) => value.trim().replace(/\s+/g, " ").toLocaleLowerCase();
const priority = (index: number) => (index + 1) as 1 | 2 | 3;
const reasonText = (reason: PrioritizedLocationReason) => reason.id === "other" && reason.customLabel ? reason.customLabel : reason.label;

function migrateLocation(location: LocationPreference): LocationPreference {
  if (location.prioritizedReasons) return location;
  return { ...location, prioritizedReasons: (location.reasons ?? []).slice(0, 3).map((label, index) => ({ id: label.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""), label, priority: priority(index) })) };
}

export function LocationModule({ media }: { media?: Record<string, LMUInstructionalMedia> }) {
  const progress = useOriginalProgress();
  const stored = progress.find((item) => item.moduleId === "location")?.responses as unknown as Partial<LocationResponse> | undefined;
  const base = emptyLocationResponse();
  const response: LocationResponse = { ...base, ...stored, locations: (stored?.locations ?? base.locations).map(migrateLocation) };
  const headingRef = useRef<HTMLHeadingElement>(null);
  const router = useRouter();
  const [relocationContextOpen, setRelocationContextOpen] = useState(false);
  const [noteEditorIds, setNoteEditorIds] = useState<Set<string>>(() => new Set());
  const [constraintNoteOpen, setConstraintNoteOpen] = useState(false);
  const [reviewEditor, setReviewEditor] = useState<string | null>(null);
  const [replacement, setReplacement] = useState<{ locationId: string; reasonId: string; reasonLabel: string } | null>(null);
  const [locationMessage, setLocationMessage] = useState("");
  usePageStart(response.resumeScreen, headingRef);

  const isStay = response.relocationOpenness === "stay";
  const allLocations = [...response.locations].sort((a, b) => a.order - b.order);
  const activeLocations = isStay ? allLocations.slice(0, 1) : allLocations.slice(0, 3);
  const duplicateLocations = activeLocations.filter((location, index) => { const normalized = normalizeLocation(location.label); return normalized && activeLocations.findIndex((other) => normalizeLocation(other.label) === normalized) !== index; });
  const locationsValid = activeLocations.length === (isStay ? 1 : 3) && activeLocations.every((location) => location.label.trim()) && duplicateLocations.length === 0;
  const reasonsValid = activeLocations.every((location) => location.prioritizedReasons.length > 0 && location.prioritizedReasons.every((reason) => reason.id !== "other" || reason.customLabel?.trim()));
  const branchValid = isStay ? Boolean(response.stayReason?.trim()) : activeLocations.some((location) => location.id === response.primaryLocationId);
  const primaryLocation = activeLocations.find((location) => location.id === response.primaryLocationId) ?? activeLocations[0];
  const otherLocations = activeLocations.filter((location) => location.id !== primaryLocation?.id);

  function save(next: LocationResponse) { saveLocationResponse(next); }
  function go(screen: LocationScreen, patch: Partial<LocationResponse> = {}) { setReviewEditor(null); setNoteEditorIds(new Set()); setConstraintNoteOpen(false); setReplacement(null); save({ ...response, ...patch, resumeScreen: screen }); }
  function update(patch: Partial<LocationResponse>) { save({ ...response, ...patch, finalizedAt: undefined }); }
  function updateLocation(id: string, patch: Partial<LocationPreference>) { update({ locations: response.locations.map((location) => location.id === id ? { ...location, ...patch } : location) }); }
  function selectOpenness(id: RelocationOpenness) { update({ relocationOpenness: id, primaryLocationId: id === "stay" ? allLocations[0]?.id : response.relocationOpenness === "stay" ? undefined : response.primaryLocationId }); }
  function setReasons(locationId: string, reasons: PrioritizedLocationReason[]) { updateLocation(locationId, { prioritizedReasons: reasons.map((reason, index) => ({ ...reason, priority: priority(index) })) }); }
  function toggleReason(locationId: string, reasonId: string, reasonLabel: string) {
    const location = response.locations.find((item) => item.id === locationId); if (!location) return;
    const index = location.prioritizedReasons.findIndex((item) => item.id === reasonId);
    if (index >= 0) return setReasons(locationId, location.prioritizedReasons.filter((_, reasonIndex) => reasonIndex !== index));
    if (location.prioritizedReasons.length === 3) return setReplacement({ locationId, reasonId, reasonLabel });
    setReasons(locationId, [...location.prioritizedReasons, { id: reasonId, label: reasonLabel, priority: priority(location.prioritizedReasons.length) }]);
  }
  function replaceReason(slot: number) { if (!replacement) return; const location = response.locations.find((item) => item.id === replacement.locationId); if (!location) return; const reasons = [...location.prioritizedReasons]; reasons[slot] = { id: replacement.reasonId, label: replacement.reasonLabel, priority: priority(slot) }; setReasons(location.id, reasons); setReplacement(null); }
  function updateOther(locationId: string, value: string) { const location = response.locations.find((item) => item.id === locationId); if (location) setReasons(locationId, location.prioritizedReasons.map((reason) => reason.id === "other" ? { ...reason, customLabel: value.slice(0, 120) } : reason)); }
  function toggleConstraint(value: string) { update({ constraints: response.constraints.includes(value) ? response.constraints.filter((item) => item !== value) : [...response.constraints, value] }); }
  function toggleNoteEditor(id: string) { setNoteEditorIds((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }
  function chooseCurrentLocationSlot() { const target = activeLocations.find((location) => !location.label.trim()) ?? activeLocations[0]; setLocationMessage("Enter where you live now in the highlighted location field. No location permission is used."); window.requestAnimationFrame(() => document.getElementById(`location-input-${target.id}`)?.focus()); }
  function confirm() { if (response.relocationOpenness && locationsValid && reasonsValid && branchValid) go("final", { finalizedAt: new Date().toISOString(), primaryLocationId: isStay ? activeLocations[0].id : response.primaryLocationId }); }
  function finish() { completeLocation(response); router.push("/experiences/life-mapping-u/original"); }

  function reasonSelector(location: LocationPreference) {
    return <><div className="location-reason-list" aria-label={`Prioritized reasons for ${location.label}`}>{locationReasons.map((reason) => { const index = location.prioritizedReasons.findIndex((item) => item.id === reason.id); return <button type="button" className={index >= 0 ? "is-selected" : ""} aria-pressed={index >= 0} key={reason.id} onClick={() => toggleReason(location.id, reason.id, reason.label)}><span aria-hidden="true">{index >= 0 ? index + 1 : ""}</span>{reason.label}</button>; })}</div>{location.prioritizedReasons.some((reason) => reason.id === "other") && <label className="location-other-reason"><span>Required</span>What other reason?<input maxLength={120} value={location.prioritizedReasons.find((reason) => reason.id === "other")?.customLabel ?? ""} onChange={(event) => updateOther(location.id, event.target.value)} /></label>}{replacement?.locationId === location.id && <div className="location-replacement"><p className="eyebrow">Choose a replacement</p><h3>Which priority should “{replacement.reasonLabel}” replace?</h3>{location.prioritizedReasons.map((reason, index) => <button type="button" key={reason.id} onClick={() => replaceReason(index)}><span>{index + 1}</span>{reasonText(reason)}</button>)}<button className="review-replace-cancel" type="button" onClick={() => setReplacement(null)}>Cancel</button></div>}</>;
  }
  function reasonSummary(location: LocationPreference) { return location.prioritizedReasons.length > 0 && <div><p className="eyebrow">What Draws Me Here</p><ol className="location-priority-summary">{location.prioritizedReasons.map((reason) => <li key={reason.id}>{reasonText(reason)}</li>)}</ol></div>; }
  function placeReview(location: LocationPreference, label: string) {
    return <article key={location.id}><header><span>{label}</span><LMUBadgeIcon name="location" state="active" size={58} label="Location" /><h2>{location.label}</h2></header>{reasonSummary(location)}{location.note && <div><p className="eyebrow">Why This Place</p><p className="location-readonly-note">{location.note}</p></div>}<div className="location-review-actions"><button type="button" aria-expanded={reviewEditor === `${location.id}-location`} onClick={() => setReviewEditor(reviewEditor === `${location.id}-location` ? null : `${location.id}-location`)}>+ Edit Location</button><button type="button" aria-expanded={reviewEditor === `${location.id}-reasons`} onClick={() => setReviewEditor(reviewEditor === `${location.id}-reasons` ? null : `${location.id}-reasons`)}>+ Edit Reasons</button><button type="button" aria-expanded={reviewEditor === `${location.id}-note`} onClick={() => setReviewEditor(reviewEditor === `${location.id}-note` ? null : `${location.id}-note`)}>{location.note ? "+ Edit Note" : "+ Add Note"}</button></div>{reviewEditor === `${location.id}-location` && <div className="location-review-editor"><label>Location<input maxLength={120} value={location.label} onChange={(event) => updateLocation(location.id, { label: event.target.value })} /></label><button type="button" onClick={() => setReviewEditor(null)}>Save & Close</button></div>}{reviewEditor === `${location.id}-reasons` && <div className="location-review-editor">{reasonSelector(location)}<button type="button" disabled={!location.prioritizedReasons.length || location.prioritizedReasons.some((reason) => reason.id === "other" && !reason.customLabel?.trim())} onClick={() => setReviewEditor(null)}>Save & Close</button></div>}{reviewEditor === `${location.id}-note` && <div className="location-review-editor"><label>Optional note<textarea rows={4} maxLength={700} value={location.note ?? ""} onChange={(event) => updateLocation(location.id, { note: event.target.value })} /></label><button type="button" onClick={() => setReviewEditor(null)}>Save & Close</button></div>}</article>;
  }

  const locationSteps: LocationScreen[] | undefined = isStay ? ["introduction", "relocation", "locations", "reasons", "constraints", "review", "final"] : undefined;
  const activeLocationSteps: LocationScreen[] = locationSteps ?? ["introduction", "relocation", "locations", "reasons", "primary", "constraints", "review", "final"];
  const startOver = <ModuleStartOverControl experienceId={LMU_ORIGINAL_EXPERIENCE_ID} moduleId="location" moduleHref="/experiences/life-mapping-u/module/location" screen={response.resumeScreen} currentStep={Math.max(1, activeLocationSteps.indexOf(response.resumeScreen) + 1)} totalSteps={activeLocationSteps.length} onBack={response.resumeScreen === "introduction" ? undefined : () => go(activeLocationSteps[activeLocationSteps.indexOf(response.resumeScreen) - 1])} />;
  const actions = (back: () => void, next: () => void, label: string, disabled = false) => <div className="teammates-actions"><button className="story-cancel" type="button" onClick={back}>← Back</button><button className="button button-primary" type="button" disabled={disabled} onClick={next}><span>{label}</span><span aria-hidden="true">→</span></button></div>;

  return <LMUShell context="Location" theme="dark" journeyHref="/experiences/life-mapping-u/original">
    {response.resumeScreen === "introduction" && <Intro media={media} headingRef={headingRef} onNext={() => go("relocation")} startOver={startOver} />}
    {response.resumeScreen === "relocation" && <main className="teammates-shell location-shell"><div className="teammates-screen-heading"><LMUBadgeIcon name="location" state="current" size={72} label="Location" /><LMUScreenHeading eyebrow="Location · 1 of 4" title="How open are you to relocating?" description="Choose the statement that most closely reflects your current flexibility." headingRef={headingRef} /></div><section className="location-relocation-scale" aria-label="Relocation flexibility">{relocationOptions.map((option, index) => <button className={response.relocationOpenness === option.id ? "is-selected" : ""} type="button" aria-pressed={response.relocationOpenness === option.id} key={option.id} onClick={() => selectOpenness(option.id)}><span>{String(index + 1).padStart(2, "0")}</span><strong>{option.label}</strong></button>)}</section>{response.relocationOpenness && <section className="location-optional-editor"><button type="button" aria-expanded={relocationContextOpen} onClick={() => setRelocationContextOpen((open) => !open)}>{relocationContextOpen ? "− Close Context" : response.relocationContext ? "+ Edit Context" : "+ Add More Context"}</button>{response.relocationContext && !relocationContextOpen && <p>{response.relocationContext}</p>}{relocationContextOpen && <label><span>Optional</span>What most influences how open you are to relocating?<textarea rows={5} maxLength={700} value={response.relocationContext ?? ""} onChange={(event) => update({ relocationContext: event.target.value })} /></label>}</section>}{actions(() => go("introduction"), () => go("locations"), isStay ? "Enter My Home Location" : "Choose Three Places", !response.relocationOpenness)}{startOver}</main>}
    {response.resumeScreen === "locations" && <main className="teammates-shell location-shell"><LMUScreenHeading eyebrow="Location · 2 of 4" title={isStay ? "Where do you currently live?" : "Three places you would consider"} description={isStay ? "Enter the city or geographic area you consider home." : "Choose three geographic areas where you would either want to live or be willing to live."} headingRef={headingRef} /><button className="location-current-action" type="button" onClick={chooseCurrentLocationSlot}>Use Where I Live Now</button>{locationMessage && <p className="location-current-message" role="status">{locationMessage}</p>}<section className={`location-entry-path${isStay ? " is-home-only" : ""}`} aria-label={isStay ? "Current home location" : "Three geographic areas"}>{activeLocations.map((location, index) => <article key={location.id}><span>{isStay ? "HOME" : String(index + 1).padStart(2, "0")}</span><LMUBadgeIcon name="location" state={location.label.trim() ? "active" : "light"} size={52} label={isStay ? "Home" : `Location ${index + 1}`} /><label htmlFor={`location-input-${location.id}`}><small>{isStay ? "Current or home location" : "Location"}</small><input id={`location-input-${location.id}`} maxLength={120} value={location.label} onChange={(event) => { setLocationMessage(""); updateLocation(location.id, { label: event.target.value }); }} placeholder={index === 0 ? "Indianapolis, Indiana" : index === 1 ? "Nairobi, Kenya" : "Vienna, Austria"} /></label></article>)}</section>{isStay && <section className="location-stay-reason"><p className="eyebrow">What makes staying here important to you?</p><p>There may be relationships, responsibilities, community, or other realities that make remaining where you are the right choice for this season.</p><label>Why I want or need to stay here<textarea rows={6} maxLength={900} value={response.stayReason ?? ""} onChange={(event) => update({ stayReason: event.target.value })} /></label></section>}{duplicateLocations.length > 0 && <p className="location-error" role="alert">Each location needs to be different. Please revise the duplicate entry.</p>}{actions(() => go("relocation"), () => go("reasons", isStay ? { primaryLocationId: activeLocations[0].id } : {}), "Reflect on These Places", !locationsValid || (isStay && !response.stayReason?.trim()))}{startOver}</main>}
    {response.resumeScreen === "reasons" && <main className="teammates-shell location-shell"><LMUScreenHeading eyebrow="Location · 3 of 4" title={isStay ? "What draws you here?" : "Why these places?"} description="Choose up to three reasons this place stands out to you, beginning with the one that matters most." headingRef={headingRef} /><section className="location-reflection-path">{activeLocations.map((location, index) => { const noteOpen = noteEditorIds.has(location.id); return <article key={location.id}><header><span>{isStay ? "HOME" : String(index + 1).padStart(2, "0")}</span><LMUBadgeIcon name="location" state="active" size={54} label="Location" /><div><p className="eyebrow">What draws you here?</p><h2>{location.label}</h2></div></header>{reasonSelector(location)}{location.note && !noteOpen && <p className="location-readonly-note">{location.note}</p>}<div className="location-optional-editor"><button type="button" aria-expanded={noteOpen} onClick={() => toggleNoteEditor(location.id)}>{noteOpen ? "− Close Note" : location.note ? "+ Edit Note" : "+ Add a Note"}</button>{noteOpen && <label><span>Optional</span>What makes this place appealing or realistic for you?<textarea rows={4} maxLength={700} value={location.note ?? ""} onChange={(event) => updateLocation(location.id, { note: event.target.value })} /></label>}</div></article>; })}</section>{actions(() => go("locations"), () => go(isStay ? "constraints" : "primary"), isStay ? "Consider Practical Realities" : "Choose My First Choice", !reasonsValid)}{startOver}</main>}
    {response.resumeScreen === "primary" && !isStay && <main className="teammates-shell location-shell"><LMUScreenHeading eyebrow="Location" title="Which place is your first choice right now?" description="Choose the one place that currently rises to the top. You do not need to rank the other two." headingRef={headingRef} /><section className="location-primary-list">{activeLocations.map((location) => <button type="button" className={response.primaryLocationId === location.id ? "is-selected" : ""} aria-pressed={response.primaryLocationId === location.id} key={location.id} onClick={() => update({ primaryLocationId: location.id })}><span>{response.primaryLocationId === location.id ? "#1" : ""}</span><LMUBadgeIcon name="location" state={response.primaryLocationId === location.id ? "active" : "light"} size={48} label="Location" /><strong>{location.label}</strong></button>)}</section>{actions(() => go("reasons"), () => go("constraints"), "Consider Practical Realities", !response.primaryLocationId)}{startOver}</main>}
    {response.resumeScreen === "constraints" && <main className="teammates-shell location-shell"><LMUScreenHeading eyebrow="Location · 4 of 4" title="What could shape this decision?" description="A place may be appealing and still come with real constraints. This is simply a chance to name what matters." headingRef={headingRef} /><section className="location-constraints"><p className="eyebrow">Practical considerations · Optional</p><div className="location-chip-grid" aria-label="Practical considerations">{locationConstraints.map((constraint) => <button type="button" className={response.constraints.includes(constraint) ? "is-selected" : ""} aria-pressed={response.constraints.includes(constraint)} key={constraint} onClick={() => toggleConstraint(constraint)}>{response.constraints.includes(constraint) && <span aria-hidden="true">✓</span>}{constraint}</button>)}</div></section>{response.constraintNote && !constraintNoteOpen && <p className="location-readonly-note">{response.constraintNote}</p>}<section className="location-optional-editor"><button type="button" aria-expanded={constraintNoteOpen} onClick={() => setConstraintNoteOpen((open) => !open)}>{constraintNoteOpen ? "− Close Context" : response.constraintNote ? "+ Edit Context" : "+ Add More Context"}</button>{constraintNoteOpen && <label><span>Optional</span>Are there practical realities that would strongly shape where you could live?<textarea rows={5} maxLength={700} value={response.constraintNote ?? ""} onChange={(event) => update({ constraintNote: event.target.value })} /></label>}</section>{actions(() => go(isStay ? "reasons" : "primary"), () => go("review"), "Review My Preferences")}{startOver}</main>}
    {response.resumeScreen === "review" && <main className="teammates-shell location-shell location-review"><LMUScreenHeading eyebrow="Location" title="Your Location Preferences" description="Review the places where your life could take root." headingRef={headingRef} /><section className="location-review-relocation"><p className="eyebrow">Openness to Relocation</p><h2>{relocationLabel(response.relocationOpenness)}</h2>{response.relocationContext && <p>{response.relocationContext}</p>}<button type="button" onClick={() => go("relocation")}>+ Edit Relocation Flexibility</button></section>{isStay && <section className="location-review-constraints"><p className="eyebrow">Why Staying Here Matters</p><p>{response.stayReason}</p><button type="button" onClick={() => go("locations")}>+ Edit</button></section>}<section className="location-review-path"><p className="eyebrow">{isStay ? "Home" : "First Choice Right Now"}</p>{primaryLocation && placeReview(primaryLocation, isStay ? "HOME" : "#1")}{!isStay && otherLocations.length > 0 && <><p className="eyebrow location-other-places-title">Other Places I Would Consider</p>{otherLocations.map((location, index) => placeReview(location, String(index + 2).padStart(2, "0")))}</>}</section>{(response.constraints.length > 0 || response.constraintNote) && <section className="location-review-constraints"><p className="eyebrow">Practical Considerations</p>{response.constraints.length > 0 && <ul>{response.constraints.map((constraint) => <li key={constraint}>{constraint}</li>)}</ul>}{response.constraintNote && <p>{response.constraintNote}</p>}<button type="button" onClick={() => go("constraints")}>+ Edit</button></section>}<button className="button button-primary" type="button" disabled={!locationsValid || !reasonsValid || !branchValid} onClick={confirm}><span>Confirm My Location Preferences</span><span aria-hidden="true">✓</span></button>{startOver}</main>}
    {response.resumeScreen === "final" && <main className="teammates-shell location-shell location-final"><LMUScreenHeading eyebrow="Location" title="Your Location Preferences" description="These are the places and practical possibilities you identified for where your life and work could take root." headingRef={headingRef} /><section><p className="eyebrow">Openness to Relocation</p><h2>{relocationLabel(response.relocationOpenness)}</h2></section>{isStay && <section className="location-review-constraints"><p className="eyebrow">Why Staying Here Matters</p><p>{response.stayReason}</p></section>}<section className="location-final-path"><p className="eyebrow">{isStay ? "Home" : "Places I Would Consider"}</p>{primaryLocation && <FinalPlace location={primaryLocation} label={isStay ? "HOME" : "#1"} />}{!isStay && otherLocations.map((location, index) => <FinalPlace key={location.id} location={location} label={String(index + 2).padStart(2, "0")} />)}</section><button className="button button-primary" type="button" onClick={finish}><span>Finish Section</span><span aria-hidden="true">→</span></button>{startOver}</main>}
  </LMUShell>;
}

function FinalPlace({ location, label }: { location: LocationPreference; label: string }) { return <article><span>{label}</span><LMUBadgeIcon name="location" state="active" size={58} label="Location" /><div><h2>{location.label}</h2><ol className="location-priority-summary">{location.prioritizedReasons.map((reason) => <li key={reason.id}>{reasonText(reason)}</li>)}</ol></div></article>; }

function Intro({ media, headingRef, onNext, startOver }: { media?: Record<string, LMUInstructionalMedia>; headingRef: RefObject<HTMLHeadingElement | null>; onNext: () => void; startOver: ReactNode }) {
  return <main className="success-intro location-intro"><section className="success-intro-copy teammates-intro-copy"><p className="eyebrow eyebrow-rule">Location</p><h1 ref={headingRef} tabIndex={-1}>Where could your life and work take root?</h1><p className="success-intro-accent">Place matters. The people around you, the community you live in, and the practical realities of where you are can shape the life you build.</p>{media?.intro && <LMUInstructionalVideo {...media.intro} />}<div className="skills-intro-instructions"><p className="eyebrow">Why This Matters</p><p>Your purpose doesn’t exist in a vacuum. It is lived out in a place, among people, and in a community.</p><p>This section helps you reflect on where you would most like to live and what limits or possibilities exist around relocation.</p><p>Consider both your personal desires and practical constraints. Be realistic about whether or not you are open to relocating.</p><p><strong>Action step:</strong> Complete the Location section.</p></div><button className="button button-primary" type="button" onClick={onNext}><span>Explore My Location Preferences</span><span aria-hidden="true">→</span></button>{startOver}</section><aside className="success-memory-panel teammates-intro-badge"><MapAccent density="tight" position="center" opacity={0.18} /><div><LMUBadgeIcon name="location" state="current" size={112} label="Location" context="dark" /><p className="eyebrow">Where my life takes root</p><p>Consider the places, people, and practical realities that could support your next season.</p></div></aside></main>;
}
