"use client";
import { useEffect,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { LMU_ORIGINAL_EXPERIENCE_ID } from "@/lib/experiences/lmu/original-journey";
import { motivatorById,motivatorDefinitions,type MotivatorDefinition } from "@/modules/lmu/current-motivator-rankings/curriculum";
import { getMotivatorPreview } from "@/modules/lmu/current-motivator-rankings/previews";
import { shouldConfirmStayLocationTopChoice } from "@/modules/lmu/current-motivator-rankings/location-stay-check";
import { completeMotivatorRanking,emptyMotivatorRankingResponse,isValidMotivatorOrder,saveMotivatorRankingResponse } from "@/modules/lmu/current-motivator-rankings/storage";
import type { MotivatorId,MotivatorRankingResponse,MotivatorRankingScreen } from "@/modules/lmu/current-motivator-rankings/types";
import type { LocationResponse } from "@/modules/lmu/location/types";
import { LMUBadgeIcon } from "./icons/badge/LMUBadgeIcon";
import { LMUScreenHeading } from "./LMUScreenHeading";
import { LMUShell } from "./LMUShell";
import { MapAccent } from "./MapAccent";
import { ModuleStartOverControl } from "./ModuleStartOverControl";
import { SalaryRangeMeter } from "./SalaryModule";
import { useOriginalProgress } from "./useOriginalProgress";
import { usePageStart } from "./usePageStart";
import { LMUFinalMoveControls, LMUFinalSelectionRow } from "./LMUFinalSelectionReview";

export function MotivatorRankingsModule(){
  const progress=useOriginalProgress(); const stored=progress.find((item)=>item.moduleId==="current-motivator-rankings")?.responses as unknown as Partial<MotivatorRankingResponse>|undefined; const response={...emptyMotivatorRankingResponse(),...stored};
  const headingRef=useRef<HTMLHeadingElement>(null); const locationAttentionSeen=useRef(false); const pendingTriggerRef=useRef<HTMLElement|null>(null); const router=useRouter(); const [expanded,setExpanded]=useState<Set<MotivatorId>>(()=>new Set()); const [positionId,setPositionId]=useState<MotivatorId|null>(null); const [reflectionOpen,setReflectionOpen]=useState(false); const [pendingPriorityMove,setPendingPriorityMove]=useState<{id:MotivatorId;target:number}|null>(null); const [locationStayCheckInResolved,setLocationStayCheckInResolved]=useState(false); const [locationAttentionPulse,setLocationAttentionPulse]=useState(false);
  usePageStart(response.resumeScreen,headingRef); const previews=new Map(motivatorDefinitions.map((item)=>[item.id,getMotivatorPreview(item,progress)])); const sourcesComplete=motivatorDefinitions.every((item)=>previews.get(item.id)?.complete); const validOrder=isValidMotivatorOrder(response.orderedMotivatorIds); const locationProgress=progress.find((item)=>item.moduleId==="location"); const locationResponse=locationProgress?.responses as unknown as Partial<LocationResponse>|undefined; const hasFinalizedStayLocation=locationProgress?.status==="completed"&&locationResponse?.relocationOpenness==="stay"&&Boolean(locationResponse.finalizedAt); const currentFirst=response.orderedMotivatorIds[0];
  useEffect(()=>{const showsCards=response.resumeScreen==="review"||response.resumeScreen==="ranking";if(!hasFinalizedStayLocation||!showsCards||locationAttentionSeen.current)return;locationAttentionSeen.current=true;const start=window.setTimeout(()=>setLocationAttentionPulse(true),0);const finish=window.setTimeout(()=>setLocationAttentionPulse(false),1100);return()=>{window.clearTimeout(start);window.clearTimeout(finish);};},[hasFinalizedStayLocation,response.resumeScreen]);
  const unranked=motivatorDefinitions.filter((item)=>!response.orderedMotivatorIds.includes(item.id));
  function save(next:MotivatorRankingResponse){saveMotivatorRankingResponse(next);} function go(screen:MotivatorRankingScreen){setPositionId(null);save({...response,resumeScreen:screen});}
  function update(patch:Partial<MotivatorRankingResponse>){save({...response,...patch,finalizedAt:undefined});}
  function toggleExpanded(id:MotivatorId){setExpanded((current)=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;});}
  function nextOrderForMove(id:MotivatorId,target:number){const without=response.orderedMotivatorIds.filter((item)=>item!==id);const next=[...without];next.splice(Math.max(0,Math.min(target,next.length)),0,id);return next;}
  function commitMove(id:MotivatorId,target:number){const next=nextOrderForMove(id,target);update({orderedMotivatorIds:next});setPositionId(null);if(next[0]==="location")setLocationStayCheckInResolved(true);}
  function moveTo(id:MotivatorId,target:number){const next=nextOrderForMove(id,target);const changesTop=next[0]!==currentFirst;if(changesTop&&shouldConfirmStayLocationTopChoice({hasFinalizedStayLocation,proposedTopMotivator:next[0],checkInResolved:locationStayCheckInResolved})){pendingTriggerRef.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setPendingPriorityMove({id,target});return;}commitMove(id,target);}
  function moveBy(id:MotivatorId,direction:-1|1){const index=response.orderedMotivatorIds.indexOf(id); if(index<0)return;moveTo(id,index+direction);}
  function dragStart(event:React.DragEvent,id:MotivatorId){event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",id);}
  function drop(event:React.DragEvent,target:number){event.preventDefault();const id=event.dataTransfer.getData("text/plain") as MotivatorId;if(motivatorById.has(id))moveTo(id,target);}
  function finalizeRanking(){save({...response,finalizedAt:new Date().toISOString(),resumeScreen:"final"});}
  function confirm(){if(validOrder&&sourcesComplete)finalizeRanking();}
  function finish(){completeMotivatorRanking(response);router.push("/experiences/life-mapping-u/original");}
  function keepPendingTopPriority(){if(!pendingPriorityMove)return;const pending=pendingPriorityMove;setLocationStayCheckInResolved(true);setPendingPriorityMove(null);commitMove(pending.id,pending.target);}
  function makeLocationFirst(){setLocationStayCheckInResolved(true);setPendingPriorityMove(null);commitMove("location",0);}
  function reconsiderPendingTopPriority(){setPendingPriorityMove(null);}
  function resetRankingInteraction(){setExpanded(new Set());setPositionId(null);setReflectionOpen(false);setPendingPriorityMove(null);setLocationStayCheckInResolved(false);setLocationAttentionPulse(false);locationAttentionSeen.current=false;pendingTriggerRef.current=null;}
  function redoMotivatorRanking(){save({...emptyMotivatorRankingResponse(),resumeScreen:"ranking"});resetRankingInteraction();}
  const rankingSteps: MotivatorRankingScreen[]=["introduction","review","ranking","final-review","final"];
  const rankingBack=response.resumeScreen==="introduction"?undefined:()=>go(rankingSteps[rankingSteps.indexOf(response.resumeScreen)-1]);
  const hasMotivatorRankingWork=response.orderedMotivatorIds.length>0||Boolean(response.topPriorityReflection)||Boolean(response.finalizedAt);
  const motivatorRedo=hasMotivatorRankingWork&&["ranking","final-review","final"].includes(response.resumeScreen)?{label:"Redo Motivator Ranking",title:"Redo Motivator Ranking?",description:"This will erase your Motivator Ranking and its optional reflection. Your completed Life Map modules will remain, and you will begin the ranking process again.",onConfirm:redoMotivatorRanking}:undefined;
  const startOver=<ModuleStartOverControl experienceId={LMU_ORIGINAL_EXPERIENCE_ID} moduleId="current-motivator-rankings" moduleHref="/experiences/life-mapping-u/module/current-motivator-rankings" screen={response.resumeScreen} onBack={rankingBack} redo={motivatorRedo}/>;
  const dependency=!sourcesComplete&&<aside className="skills-dependency" role="status"><strong>Some Life Map areas are not completed yet.</strong><p>You can review and test the ranking experience, but you cannot confirm it until Skills, Location, Teammates, Supervisor, Growth, Values, X-Factor, and Salary are complete. No results have been invented.</p></aside>;
  function Card({definition,rank,compact=false,onSelect}: {definition:MotivatorDefinition;rank?:number;compact?:boolean;onSelect?:()=>void}){const preview=previews.get(definition.id)!;const isOpen=expanded.has(definition.id);const locationAttention=definition.id==="location"&&hasFinalizedStayLocation;return <article className={`motivator-card${compact?" is-compact":""}${onSelect?" is-selectable":""}${rank&&rank<=3?` is-top-${rank}`:""}${locationAttention?" has-location-attention":""}${locationAttention&&locationAttentionPulse?" is-entering":""}`} role={onSelect ? "button" : undefined} tabIndex={onSelect ? 0 : undefined} aria-label={`${definition.label}${rank?`, position ${rank} of 8`:""}${locationAttention?"; staying where you are was marked important":""}`} onKeyDown={(event)=>{if(!onSelect||event.target!==event.currentTarget)return;if(event.key==="Enter"||event.key===" "){event.preventDefault();onSelect();}}} onClick={(event)=>{if(!onSelect)return;const target=event.target;if(target instanceof Element&&target.closest("[data-motivator-results]"))return;onSelect();}}><div className="motivator-card-main">{rank&&<span className="motivator-rank-number">{String(rank).padStart(2,"0")}</span>}<LMUBadgeIcon name={definition.badgeKey} state={preview.complete?"active":"light"} size={compact?48:58} label={definition.label}/><div><p className="eyebrow">{definition.label}</p><h2>{definition.supportingDescription}</h2><p className={preview.complete?"motivator-preview":"motivator-preview is-incomplete"}>{preview.shortPreview}</p></div></div>{locationAttention&&<p className="motivator-location-context">You indicated that staying where you are is important to you.</p>}<button type="button" data-motivator-results aria-expanded={isOpen} onClick={()=>toggleExpanded(definition.id)}>{isOpen?"− Hide My Results":"+ View My Results"}</button>{isOpen&&<div className="motivator-expanded" data-motivator-results>{preview.complete?<>{preview.expandedGroups.map((group,index)=><section key={`${definition.id}-${index}`}>{group.label&&<p className="eyebrow">{group.label}</p>}<ul>{group.items.map((item)=><li key={item}>{item}</li>)}</ul></section>)}{preview.salaryRange?.financialFloor&&preview.salaryRange.fiveYearGoal&&<SalaryRangeMeter compact floor={preview.salaryRange.financialFloor} goal={preview.salaryRange.fiveYearGoal} currency={preview.salaryRange.currency} period={preview.salaryRange.compensationPeriod}/>}</>:<p>Not completed yet</p>}</div>}</article>;}
  function RankingRow({id,index}:{id:MotivatorId;index:number}){const definition=motivatorById.get(id)!;return <li className="motivator-ranking-item" onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>drop(event,index)}><Card definition={definition} rank={index+1} compact/><div className="motivator-rank-actions"><button type="button" draggable onDragStart={(event)=>dragStart(event,id)} aria-label={`Drag ${definition.label} from position ${index+1}`}>↕ Drag</button><button type="button" disabled={index===0} aria-label={`Move ${definition.label} up`} onClick={()=>moveBy(id,-1)}>Move Up</button><button type="button" disabled={index===response.orderedMotivatorIds.length-1} aria-label={`Move ${definition.label} down`} onClick={()=>moveBy(id,1)}>Move Down</button><button type="button" aria-expanded={positionId===id} onClick={()=>setPositionId(positionId===id?null:id)}>Change Position</button></div>{positionId===id&&<div className="motivator-position-picker"><p>Move {definition.label} to:</p>{motivatorDefinitions.map((_,target)=><button type="button" aria-label={`Move ${definition.label} to position ${target+1}`} className={target===index?"is-current":""} key={target} onClick={()=>moveTo(id,target)}>{target+1}</button>)}</div>}</li>;}
  function ReviewRankingRow({id,index}:{id:MotivatorId;index:number}){const definition=motivatorById.get(id)!;const preview=previews.get(id)!;const isOpen=expanded.has(id);return <LMUFinalSelectionRow rank={index+1} total={8} title={definition.label} badge={<LMUBadgeIcon name={definition.badgeKey} state="active" size={54} label={definition.label}/>} context={<p>{preview.shortPreview}</p>} disclosureLabel="My Results" expanded={isOpen} onToggleDisclosure={()=>toggleExpanded(id)} detail={<>{preview.expandedGroups.map((group,groupIndex)=><section key={`${id}-${groupIndex}`}>{group.label&&<p className="eyebrow">{group.label}</p>}<ul>{group.items.map((item)=><li key={item}>{item}</li>)}</ul></section>)}{preview.salaryRange?.financialFloor&&preview.salaryRange.fiveYearGoal&&<SalaryRangeMeter compact floor={preview.salaryRange.financialFloor} goal={preview.salaryRange.fiveYearGoal} currency={preview.salaryRange.currency} period={preview.salaryRange.compensationPeriod}/>}</>} actions={<LMUFinalMoveControls title={definition.label} index={index} lastIndex={7} onMove={(direction)=>moveBy(id,direction)} />}/>;}
  function ReadonlyRanking(){return <ol className="motivator-final-ranking">{response.orderedMotivatorIds.map((id,index)=>{const definition=motivatorById.get(id)!;return <li key={id}><span>{String(index+1).padStart(2,"0")}</span><LMUBadgeIcon name={definition.badgeKey} state="active" size={52} label={definition.label}/><div><h2>{definition.label}</h2><p>{previews.get(id)?.shortPreview}</p></div></li>;})}</ol>;}
  return <LMUShell context="Motivators" theme="dark" journeyHref="/experiences/life-mapping-u/original" onInternalBack={rankingBack}>
    {response.resumeScreen==="introduction"&&<main className="success-intro motivator-intro"><section className="success-intro-copy teammates-intro-copy"><p className="eyebrow eyebrow-rule">Motivator Rankings</p><h1 ref={headingRef} tabIndex={-1}>What matters most to you right now?</h1><p className="success-intro-accent">We are all driven by different things—meaning, growth, recognition, freedom, connection, and more.</p><div className="skills-intro-instructions"><p className="eyebrow">Why This Matters</p><p>This module helps you clarify what truly motivates you so that your choices reflect what brings you energy and purpose.</p><p>Review the areas you have explored throughout Life Mapping U.</p><p>Then rank them in order of importance based on what matters most to you now and in the season ahead.</p><p>This ranking can serve as a guide in later decisions and conversations.</p><p><strong>Action step:</strong> Complete the Motivator Rankings module.</p></div><button className="button button-primary" type="button" onClick={()=>go("review")}><span>Build My Priority Ranking</span><span aria-hidden="true">→</span></button>{startOver}</section><aside className="success-memory-panel teammates-intro-badge"><MapAccent density="tight" position="center" opacity={.18}/><div><LMUBadgeIcon name="motivators" state="current" size={112} label="Motivator Rankings" context="dark"/><p className="eyebrow">The final priority layer</p><p>Order the eight areas of your Life Map for the season ahead.</p></div></aside></main>}
    {response.resumeScreen==="review"&&<main className="teammates-shell motivator-shell"><div className="teammates-screen-heading"><LMUBadgeIcon name="motivators" state="current" size={72} label="Motivator Rankings"/><LMUScreenHeading eyebrow="Motivator Rankings" title="Look Across Your Life Map" description="Each of these areas tells you something different about what matters in your future. Take a moment to look across what you discovered before putting them in priority order." headingRef={headingRef}/></div>{dependency}<section className="motivator-review-grid">{motivatorDefinitions.map((definition)=><Card key={definition.id} definition={definition}/>)}</section><div className="teammates-actions"><button className="story-cancel" type="button" onClick={()=>go("introduction")}>← Back</button><button className="button button-primary" type="button" onClick={()=>go("ranking")}><span>Rank My Motivators</span><span aria-hidden="true">→</span></button></div>{startOver}</main>}
    {response.resumeScreen==="ranking"&&<main className="teammates-shell motivator-shell"><LMUScreenHeading eyebrow="Motivator Rankings" title="Your Priorities Right Now" description="Arrange these eight areas from what matters most to you right now to what matters least. All eight can still matter. This is about priority." headingRef={headingRef}/>{response.orderedMotivatorIds[0]&&<aside className="motivator-current-first"><p className="eyebrow">Current #1 Priority</p><strong>{motivatorById.get(response.orderedMotivatorIds[0])?.label}</strong></aside>}{dependency}{unranked.length>0&&<section className="motivator-unranked"><header><p className="eyebrow">Unranked · Choose what rises next</p><span>{unranked.length} remaining</span></header><div>{unranked.map((definition)=><div draggable key={definition.id} onDragStart={(event)=>dragStart(event,definition.id)}><Card definition={definition} compact onSelect={()=>moveTo(definition.id,response.orderedMotivatorIds.length)}/><button type="button" onClick={()=>moveTo(definition.id,response.orderedMotivatorIds.length)}>Add to Priority List</button></div>)}</div></section>}<section className="motivator-priority-board" aria-label="Priority ranking" onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>drop(event,response.orderedMotivatorIds.length)}><p className="eyebrow">Priority Order · 1 is highest current priority</p>{response.orderedMotivatorIds.length?<ol>{response.orderedMotivatorIds.map((id,index)=><RankingRow id={id} index={index} key={id}/>)}</ol>:<div className="motivator-empty-board">Add or drag a motivator here to begin with priority 01.</div>}</section><div className="teammates-actions"><button className="story-cancel" type="button" onClick={()=>go("review")}>← Back to Review</button><button className="button button-primary" type="button" disabled={!validOrder} onClick={()=>go("final-review")}><span>Review My Ranking</span><span aria-hidden="true">→</span></button></div>{startOver}</main>}
    {response.resumeScreen==="final-review"&&<main className="teammates-shell motivator-shell"><LMUScreenHeading eyebrow="Motivator Rankings" title="Your Current Motivator Ranking" description="Does this order reflect what matters most to you in this season? Your priorities may change over time. Move any item here until the order feels right." headingRef={headingRef}/>{dependency}<section className="motivator-review-ranking-editor" aria-label="Review and adjust motivator ranking"><p className="eyebrow">Review and Adjust · 1 is highest current priority</p><ol>{response.orderedMotivatorIds.map((id,index)=><ReviewRankingRow id={id} index={index} key={id}/>)}</ol></section><section className="location-optional-editor motivator-reflection">{response.topPriorityReflection&&!reflectionOpen&&<p>{response.topPriorityReflection}</p>}<button type="button" aria-expanded={reflectionOpen} onClick={()=>setReflectionOpen((open)=>!open)}>{reflectionOpen?"− Close Reflection":response.topPriorityReflection?"+ Edit Reflection":"+ Add Reflection"}</button>{reflectionOpen&&<label><span>Optional</span>Why does your #1 priority rise to the top right now?<textarea rows={5} maxLength={700} value={response.topPriorityReflection??""} onChange={(event)=>update({topPriorityReflection:event.target.value})}/></label>}</section><div className="teammates-actions"><button className="story-cancel" type="button" onClick={()=>go("ranking")}>Back to Ranking Board</button><button className="button button-primary" type="button" disabled={!validOrder||!sourcesComplete} onClick={confirm}><span>Confirm My Motivator Ranking</span><span aria-hidden="true">✓</span></button></div>{startOver}</main>}
    {response.resumeScreen==="final"&&<main className="teammates-shell motivator-shell motivator-final"><div className="teammates-screen-heading"><LMUBadgeIcon name="motivators" state="active" size={72} label="Motivator Rankings"/><LMUScreenHeading eyebrow="Motivator Rankings" title="Current Motivator Ranking" description="This order captures what matters most to you right now and in the season ahead." headingRef={headingRef}/></div>{ReadonlyRanking()}{response.topPriorityReflection&&<section className="motivator-final-reflection"><p className="eyebrow">Why #1 Rises to the Top</p><p>{response.topPriorityReflection}</p></section>}<button className="button button-primary" type="button" onClick={finish}><span>Finish Module</span><span aria-hidden="true">→</span></button>{startOver}</main>}
    {pendingPriorityMove&&<LocationStayRankingDialog motivatorLabel={motivatorById.get(pendingPriorityMove.id)?.label??pendingPriorityMove.id} onDismiss={reconsiderPendingTopPriority} onKeep={keepPendingTopPriority} onMakeLocationFirst={makeLocationFirst} returnFocusRef={pendingTriggerRef}/>}
  </LMUShell>;
}

function LocationStayRankingDialog({motivatorLabel,onDismiss,onKeep,onMakeLocationFirst,returnFocusRef}:{motivatorLabel:string;onDismiss:()=>void;onKeep:()=>void;onMakeLocationFirst:()=>void;returnFocusRef:React.RefObject<HTMLElement|null>}){
  const dialogRef=useRef<HTMLDivElement>(null);const reviewRef=useRef<HTMLButtonElement>(null);
  useEffect(()=>{reviewRef.current?.focus();function onKeyDown(event:KeyboardEvent){if(event.key==="Escape"){event.preventDefault();onDismiss();window.requestAnimationFrame(()=>returnFocusRef.current?.focus());return;}if(event.key!=="Tab")return;const buttons=dialogRef.current?.querySelectorAll<HTMLElement>('button:not([disabled])');if(!buttons?.length)return;const first=buttons[0];const last=buttons[buttons.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}document.addEventListener("keydown",onKeyDown);return()=>document.removeEventListener("keydown",onKeyDown);},[onDismiss,returnFocusRef]);
  return <div className="motivator-location-dialog-backdrop"><div ref={dialogRef} className="motivator-location-dialog" role="dialog" aria-modal="true" aria-labelledby="location-ranking-dialog-title" aria-describedby="location-ranking-dialog-description"><div className="motivator-location-dialog-kicker"><LMUBadgeIcon name="location" state="active" size={46} label="Location"/><p className="eyebrow">Location Check-In</p></div><h2 id="location-ranking-dialog-title">One More Thing to Consider</h2><p id="location-ranking-dialog-description">Earlier, you indicated that you prefer to stay where you are. Because where you want to live and work can place an important boundary around the opportunities you consider, we want to make sure your first priority reflects what matters most to you.</p><p>You selected {motivatorLabel} as your top priority. Do you still want {motivatorLabel} to remain above Location in your ranking?</p><dl><div><dt>You Selected</dt><dd>{motivatorLabel}</dd></div><div><dt>Earlier Location Preference</dt><dd>I prefer to stay where I am.</dd></div></dl><div className="motivator-location-dialog-actions"><button ref={reviewRef} className="button button-primary" type="button" onClick={onKeep}>Keep {motivatorLabel} as My Top Priority</button><button className="button button-secondary" type="button" onClick={onMakeLocationFirst}>Make Location My First Priority</button></div></div></div>;
}
