"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { LMU_DEV_UNLOCK_ALL } from "@/lib/experiences/lmu/development";
import { LMU_ORIGINAL_EXPERIENCE_ID } from "@/lib/experiences/lmu/original-journey";
import type { LMUInstructionalMedia } from "@/lib/experiences/lmu/types";
import { xFactorQuestionById, xFactorQuestions } from "@/modules/lmu/x-factor/curriculum";
import { balancedGroups, deriveXFactorResults, initialGlobalGroups, promotionGroups } from "@/modules/lmu/x-factor/ranked-stack";
import { allXFactorItems, completeXFactor, emptyXFactorResponse, saveXFactorResponse } from "@/modules/lmu/x-factor/storage";
import type { XFactorGroup, XFactorResponse, XFactorScreen } from "@/modules/lmu/x-factor/types";
import { LMUBadgeIcon } from "./icons/badge/LMUBadgeIcon";
import { LMUInstructionalVideo } from "./LMUInstructionalVideo";
import { LMUScreenHeading } from "./LMUScreenHeading";
import { LMUShell } from "./LMUShell";
import { MapAccent } from "./MapAccent";
import { ModuleStartOverControl } from "./ModuleStartOverControl";
import { useOriginalProgress } from "./useOriginalProgress";
import { usePageStart } from "./usePageStart";

const normalize = (value: string) => value.trim().replace(/\s+/g, " ").toLocaleLowerCase();

export function XFactorModule({ media }: { media?: Record<string, LMUInstructionalMedia> }) {
  const progress = useOriginalProgress(); const stored = progress.find((item) => item.moduleId === "x-factor")?.responses as unknown as Partial<XFactorResponse> | undefined;
  const response: XFactorResponse = { ...emptyXFactorResponse(), ...stored }; const items = allXFactorItems(response); const byId = new Map(items.map((item) => [item.id, item]));
  const headingRef = useRef<HTMLHeadingElement>(null); const router = useRouter(); const [expandedId, setExpandedId] = useState<string | null>(null); const [editingQuestionId, setEditingQuestionId] = useState<string | null>(null); const [replacementId, setReplacementId] = useState<string | null>(null); const [entryError, setEntryError] = useState("");
  usePageStart(response.resumeScreen, headingRef);
  const startOver = <ModuleStartOverControl experienceId={LMU_ORIGINAL_EXPERIENCE_ID} moduleId="x-factor" moduleHref="/experiences/life-mapping-u/module/x-factor" />;
  const nonEmpty = xFactorQuestions.filter((question) => (response.responsesByQuestion[question.id] ?? []).length > 0);
  const localQuestions = nonEmpty.filter((question) => (response.responsesByQuestion[question.id] ?? []).length > 1);
  const localQuestion = localQuestions[response.localRankingQuestionIndex];
  const currentGlobalGroup = response.globalGroups.find((group) => !response.globalRankings.some((ranking) => ranking.groupId === group.id));

  function save(next: XFactorResponse) { saveXFactorResponse(next); }
  function go(screen: XFactorScreen, patch: Partial<XFactorResponse> = {}) { save({ ...response, ...patch, resumeScreen: screen }); }
  function updateQuestion(questionId: string, slot: number, value: string) {
    const current = [...(response.responsesByQuestion[questionId] ?? [])]; const id = `${questionId}-${slot + 1}`; const trimmed = value.slice(0, 120);
    const existing = current.findIndex((item) => item.id === id); if (existing >= 0) current[existing] = { ...current[existing], label: trimmed }; else current.push({ id, questionId, label: trimmed });
    save({ ...response, responsesByQuestion: { ...response.responsesByQuestion, [questionId]: current }, globalGroups: [], globalRankings: [], finalTopFour: [], finalTopEight: [], finalizedAt: undefined });
  }
  function commitQuestion(index: number, nextScreen?: XFactorScreen) {
    const question = xFactorQuestions[index]; const raw = response.responsesByQuestion[question.id] ?? []; const clean = raw.filter((item) => item.label.trim()).map((item) => ({ ...item, label: item.label.trim() })); const seen = new Set<string>(); const duplicate = clean.some((item) => { const key = normalize(item.label); if (seen.has(key)) return true; seen.add(key); return false; });
    if (duplicate) return setEntryError("Each response in this area needs to be different."); setEntryError("");
    const responsesByQuestion = { ...response.responsesByQuestion, [question.id]: clean };
    if (nextScreen) return save({ ...response, responsesByQuestion, resumeScreen: nextScreen });
    if (index < 7) return save({ ...response, responsesByQuestion, questionIndex: index + 1 });
    const nextItems = Object.values(responsesByQuestion).flat();
    if (nextItems.length < 4) return save({ ...response, responsesByQuestion, questionIndex: index });
    const nextLocal = xFactorQuestions.filter((entry) => (responsesByQuestion[entry.id] ?? []).length > 1);
    if (!nextLocal.length) { const localRankings = Object.fromEntries(xFactorQuestions.map((entry) => [entry.id, (responsesByQuestion[entry.id] ?? []).map((item) => item.id)])); return save({ ...response, responsesByQuestion, localRankings, resumeScreen: "collection" }); }
    save({ ...response, responsesByQuestion, localRankingQuestionIndex: 0, resumeScreen: "local-ranking" });
  }
  function commitCollectionQuestion(questionId: string) {
    const raw = response.responsesByQuestion[questionId] ?? []; const clean = raw.filter((item) => item.label.trim()).map((item) => ({ ...item, label: item.label.trim() })); const seen = new Set<string>();
    if (clean.some((item) => { const key = normalize(item.label); if (seen.has(key)) return true; seen.add(key); return false; })) return setEntryError("Each response in this area needs to be different.");
    setEntryError(""); setEditingQuestionId(null); save({ ...response, responsesByQuestion: { ...response.responsesByQuestion, [questionId]: clean } });
  }
  function toggleLocal(id: string) { if (!localQuestion) return; const current = response.localDrafts[localQuestion.id] ?? []; const index = current.indexOf(id); const next = index >= 0 ? current.slice(0, index) : [...current, id]; save({ ...response, localDrafts: { ...response.localDrafts, [localQuestion.id]: next } }); }
  function confirmLocal() {
    if (!localQuestion) return; const ids = response.localDrafts[localQuestion.id] ?? []; const localRankings = { ...response.localRankings, [localQuestion.id]: ids }; const nextIndex = response.localRankingQuestionIndex + 1;
    if (nextIndex < localQuestions.length) return save({ ...response, localRankings, localRankingQuestionIndex: nextIndex, participantInteractions: response.participantInteractions + 1 });
    xFactorQuestions.forEach((question) => { const questionItems = response.responsesByQuestion[question.id] ?? []; if (questionItems.length <= 1) localRankings[question.id] = questionItems.map((item) => item.id); });
    save({ ...response, localRankings, participantInteractions: response.participantInteractions + 1, resumeScreen: "collection" });
  }
  function beginGlobal() { if (items.length < 4) return; const localRankings = Object.fromEntries(xFactorQuestions.map((question) => { const validIds = (response.responsesByQuestion[question.id] ?? []).filter((item) => item.label.trim()).map((item) => item.id); const storedOrder = response.localRankings[question.id] ?? []; return [question.id, [...storedOrder.filter((id) => validIds.includes(id)), ...validIds.filter((id) => !storedOrder.includes(id))]]; })); const groups = initialGlobalGroups(localRankings); go("global-ranking", { localRankings, globalGroups: groups, activeStackHeads: groups.flatMap((group) => group.itemIds) }); }
  function toggleGlobal(group: XFactorGroup, id: string) { const current = response.globalDrafts[group.id] ?? []; const index = current.indexOf(id); const next = index >= 0 ? current.slice(0, index) : [...current, id]; save({ ...response, globalDrafts: { ...response.globalDrafts, [group.id]: next } }); }
  function confirmGlobal(group: XFactorGroup) {
    const draft = response.globalDrafts[group.id] ?? []; const rankings = [...response.globalRankings, { groupId: group.id, orderedItemIds: draft }]; const remaining = response.globalGroups.some((entry) => entry.id !== group.id && !rankings.some((ranking) => ranking.groupId === entry.id));
    if (remaining) return save({ ...response, globalRankings: rankings, participantInteractions: response.participantInteractions + 1 });
    if (group.phase === "initial") { const promoted = promotionGroups(items, response.localRankings, rankings); if (promoted.length) return save({ ...response, globalGroups: [...response.globalGroups, ...promoted], globalRankings: rankings, activeStackHeads: [...new Set([...response.activeStackHeads, ...promoted.flatMap((entry) => entry.itemIds)])], participantInteractions: response.participantInteractions + 1 }); }
    const results = deriveXFactorResults(items, response.localRankings, rankings);
    if (items.length > 8 && !response.globalGroups.some((entry) => entry.phase === "close")) { const closeGroups = balancedGroups(results.sorted.slice(2, items.length <= 16 ? 6 : 10), "close", "close-boundary"); return save({ ...response, globalGroups: [...response.globalGroups, ...closeGroups], globalRankings: rankings, ...results, participantInteractions: response.participantInteractions + 1, resumeScreen: "close-review" }); }
    const finalTopEight = results.algorithmicTopEight; save({ ...response, globalRankings: rankings, ...results, finalTopEight, finalTopFour: finalTopEight.slice(0, 4), participantInteractions: response.participantInteractions + 1, resumeScreen: "top-eight" });
  }
  function promote(id: string) { if (response.finalTopFour.includes(id)) return; setReplacementId((current) => current === id ? null : id); }
  function replaceTopFour(slot: number) { if (!replacementId) return; const topEight = [...response.finalTopEight]; const from = topEight.indexOf(replacementId); [topEight[slot], topEight[from]] = [topEight[from], topEight[slot]]; save({ ...response, finalTopEight: topEight, finalTopFour: topEight.slice(0, 4), finalizedAt: undefined }); setReplacementId(null); }
  function moveTopFour(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target > 3) return; const topEight = [...response.finalTopEight]; [topEight[index], topEight[target]] = [topEight[target], topEight[index]]; save({ ...response, finalTopEight: topEight, finalTopFour: topEight.slice(0, 4), finalizedAt: undefined }); }
  function confirmFinal() { if (response.finalTopFour.length === 4) go("final", { finalizedAt: new Date().toISOString() }); }
  function finish() { completeXFactor(response); router.push("/experiences/life-mapping-u/original"); }
  function itemCard(id: string, rank?: number) { const item = byId.get(id); if (!item) return null; const question = xFactorQuestionById.get(item.questionId); const expanded = expandedId === id; return <article className="xfactor-card" key={id}>{typeof rank === "number" && <span>{rank}</span>}<LMUBadgeIcon name="x-factor" state={typeof rank === "number" ? "active" : "light"} size={44} label="X-Factor" /><div><small>{question?.title}</small><h3>{item.label}</h3><button type="button" aria-expanded={expanded} onClick={() => setExpandedId(expanded ? null : id)}>{expanded ? "− Hide Context" : "+ View Context"}</button>{expanded && <div className="xfactor-context"><p><strong>Question</strong><br />{question?.question}</p><p><strong>Your Response</strong><br />{item.label}</p>{response.localRankings[item.questionId]?.length > 1 && <p>Ranked {response.localRankings[item.questionId].indexOf(id) + 1} of {response.localRankings[item.questionId].length} in this area</p>}</div>}</div></article>; }

  const question = xFactorQuestions[response.questionIndex]; const questionItems = response.responsesByQuestion[question?.id] ?? [];
  return <LMUShell context="X-Factor" theme="dark" journeyHref="/experiences/life-mapping-u/original">
    {response.resumeScreen === "introduction" && <main className="success-intro"><section className="success-intro-copy teammates-intro-copy"><p className="eyebrow eyebrow-rule">X-Factors</p><h1 ref={headingRef} tabIndex={-1}>What else shapes who you are and the future you are building?</h1><p className="success-intro-accent">X-Factors are the personal traits, priorities, or interests that shape how you live and lead.</p>{media?.intro && <LMUInstructionalVideo {...media.intro} />}<div className="skills-intro-instructions"><p className="eyebrow">Why This Matters</p><p>They don’t always show up in job titles or resumes, but they often influence fulfillment, direction, and decision-making.</p><p>Identify characteristics, skills, lifestyle preferences, or interests that are important to you—both personally and professionally.</p><p>X-Factors may include things like creative expression, faith involvement, community engagement, flexibility, or meaningful relationships.</p><p>This section is about naming what sets you apart in a way that brings alignment to your future decisions.</p><p><strong>Action step:</strong> Complete the X-Factors section.</p></div><button className="button button-primary" type="button" onClick={() => go("questions")}><span>Explore My X-Factors</span><span aria-hidden="true">→</span></button>{startOver}</section><aside className="success-memory-panel teammates-intro-badge"><MapAccent density="tight" position="center" opacity={0.18} /><div><LMUBadgeIcon name="x-factor" state="current" size={112} label="X-Factor" context="dark" /><p className="eyebrow">Beyond titles and credentials</p><p>Name the traits, interests, priorities, and preferences that bring alignment to your future.</p></div></aside></main>}
    {response.resumeScreen === "questions" && question && <main className="teammates-shell xfactor-shell"><div className="teammates-screen-heading"><LMUBadgeIcon name="x-factor" state="current" size={72} label="X-Factor" /><LMUScreenHeading eyebrow={`X-Factor · ${response.questionIndex + 1} of 8`} title={question.title} description={question.question} headingRef={headingRef} /></div><p className="xfactor-examples">For example: {question.examples.slice(0, 3).join(" · ")}</p><section className="xfactor-entry-list">{[0,1,2,3].map((slot) => <label key={slot}><span>{String(slot + 1).padStart(2,"0")}</span><input aria-label={`${question.title} response ${slot + 1}`} maxLength={120} value={questionItems.find((item) => item.id === `${question.id}-${slot + 1}`)?.label ?? ""} onChange={(event) => updateQuestion(question.id, slot, event.target.value)} placeholder="Optional response" /></label>)}</section>{entryError && <p className="location-error" role="alert">{entryError}</p>}{response.questionIndex === 7 && items.length < 4 && <div className="skills-dependency"><strong>You currently have fewer than four X-Factors.</strong><p>Return to the questions and add at least four responses before choosing your Top 4.</p></div>}<div className="teammates-actions">{response.questionIndex > 0 && <button className="story-cancel" type="button" onClick={() => save({ ...response, questionIndex: response.questionIndex - 1 })}>← Back</button>}<button className="button button-primary" type="button" disabled={response.questionIndex === 7 && items.length < 4} onClick={() => commitQuestion(response.questionIndex)}><span>{response.questionIndex === 7 ? "Continue to Quick Ranking" : questionItems.some((item) => item.label.trim()) ? "Continue" : "No Response Needed Here"}</span><span aria-hidden="true">→</span></button></div>{startOver}</main>}
    {response.resumeScreen === "local-ranking" && localQuestion && <main className="teammates-shell xfactor-shell"><LMUScreenHeading eyebrow={`Quick Ranking · ${response.localRankingQuestionIndex + 1} of ${localQuestions.length}`} title={localQuestion.title} description="Which of these feels most significant to what you uniquely bring? Choose them in order, starting with the one that feels most significant." headingRef={headingRef} /><section className="xfactor-rank-grid">{(response.responsesByQuestion[localQuestion.id] ?? []).map((item) => { const rank = (response.localDrafts[localQuestion.id] ?? []).indexOf(item.id); return <button className={rank >= 0 ? "is-ranked" : ""} type="button" aria-pressed={rank >= 0} key={item.id} onClick={() => toggleLocal(item.id)}><span>{rank >= 0 ? rank + 1 : "—"}</span><strong>{item.label}</strong></button>; })}</section><button className="xfactor-reset" type="button" onClick={() => save({ ...response, localDrafts: { ...response.localDrafts, [localQuestion.id]: [] } })}>Reset Order</button><button className="button button-primary" type="button" disabled={(response.localDrafts[localQuestion.id] ?? []).length !== (response.responsesByQuestion[localQuestion.id] ?? []).length} onClick={confirmLocal}><span>Continue</span><span aria-hidden="true">→</span></button>{startOver}</main>}
    {response.resumeScreen === "collection" && <main className="teammates-shell xfactor-shell"><LMUScreenHeading eyebrow="X-Factor" title="Your X-Factor Collection" description="Review what you captured across the eight areas before narrowing the collection." headingRef={headingRef} /><section className="xfactor-collection">{nonEmpty.map((entry) => <article key={entry.id}><header><p className="eyebrow">{entry.title}</p><button type="button" aria-expanded={editingQuestionId === entry.id} onClick={() => setEditingQuestionId(editingQuestionId === entry.id ? null : entry.id)}>{editingQuestionId === entry.id ? "− Close Edit" : "+ Edit"}</button></header><ol>{(response.localRankings[entry.id] ?? (response.responsesByQuestion[entry.id] ?? []).map((item) => item.id)).map((id) => <li key={id}>{byId.get(id)?.label}</li>)}</ol>{editingQuestionId === entry.id && <div className="xfactor-inline-editor">{[0,1,2,3].map((slot) => <input aria-label={`${entry.title} response ${slot + 1}`} key={slot} value={(response.responsesByQuestion[entry.id] ?? []).find((item) => item.id === `${entry.id}-${slot + 1}`)?.label ?? ""} onChange={(event) => updateQuestion(entry.id, slot, event.target.value)} />)}{entryError && <p className="location-error" role="alert">{entryError}</p>}<button type="button" onClick={() => commitCollectionQuestion(entry.id)}>Save & Close</button></div>}</article>)}</section><button className="button button-primary" type="button" disabled={items.filter((item) => item.label.trim()).length < 4} onClick={beginGlobal}><span>Begin Global Narrowing</span><span aria-hidden="true">→</span></button>{startOver}</main>}
    {(response.resumeScreen === "global-ranking" || response.resumeScreen === "close-review") && currentGlobalGroup && <main className="teammates-shell xfactor-shell"><LMUScreenHeading eyebrow={currentGlobalGroup.phase === "close" ? "A few of these were close" : "X-Factor Narrowing"} title="Which feel most significant?" description="Choose these in order, beginning with the X-Factor that feels most significant to what you uniquely bring." headingRef={headingRef} /><section className="xfactor-rank-grid">{currentGlobalGroup.itemIds.map((id) => { const rank = (response.globalDrafts[currentGlobalGroup.id] ?? []).indexOf(id); return <button className={rank >= 0 ? "is-ranked" : ""} type="button" aria-pressed={rank >= 0} key={id} onClick={() => toggleGlobal(currentGlobalGroup, id)}><span>{rank >= 0 ? rank + 1 : "—"}</span><strong>{byId.get(id)?.label}</strong><small>{xFactorQuestionById.get(byId.get(id)?.questionId ?? "")?.title}</small></button>; })}</section><button className="xfactor-reset" type="button" onClick={() => save({ ...response, globalDrafts: { ...response.globalDrafts, [currentGlobalGroup.id]: [] } })}>Reset Order</button><button className="button button-primary" type="button" disabled={(response.globalDrafts[currentGlobalGroup.id] ?? []).length !== currentGlobalGroup.itemIds.length} onClick={() => confirmGlobal(currentGlobalGroup)}><span>Continue</span><span aria-hidden="true">→</span></button>{LMU_DEV_UNLOCK_ALL && <aside className="skills-ranking-diagnostic"><span>Total X-Factors: {items.length}</span><span>Non-empty questions: {nonEmpty.length}</span><span>Global contenders: {response.activeStackHeads.length}</span><span>Top 4 eliminated: {response.eliminatedFromTopFour.length}</span><span>Top 8 eliminated: {response.eliminatedFromTopEight.length}</span><span>Interactions: {response.participantInteractions}</span><span>Phase: {currentGlobalGroup.phase}</span></aside>}{startOver}</main>}
    {response.resumeScreen === "top-eight" && <main className="teammates-shell xfactor-shell"><LMUScreenHeading eyebrow="X-Factor" title="Your X-Factors" description="Review the provisional Top 4 and the other strong X-Factors. You have the final say." headingRef={headingRef} /><p className="top-five-divider">Top 4</p><section className="xfactor-final-list">{response.finalTopFour.map((id, index) => <div key={id}>{itemCard(id,index+1)}<div><button type="button" disabled={index===0} onClick={() => moveTopFour(index,-1)}>Move Up</button><button type="button" disabled={index===3} onClick={() => moveTopFour(index,1)}>Move Down</button></div></div>)}</section>{response.finalTopEight.length > 4 && <><p className="top-five-divider">Other Strong X-Factors</p><section className="xfactor-final-list">{response.finalTopEight.slice(4).map((id,index) => { const replacementOpen = replacementId === id; const panelId = `xfactor-replacement-${id}`; return <div className="xfactor-final-item" key={id}>{itemCard(id,index+5)}<button type="button" aria-expanded={replacementOpen} aria-controls={panelId} onClick={() => promote(id)}>Move Into Top 4</button>{replacementOpen && <div className="xfactor-inline-replacement" id={panelId}><p className="eyebrow">Move this X-Factor into Top 4</p><h2>Which Top 4 X-Factor should this replace?</h2>{response.finalTopFour.map((topFourId,topFourIndex) => <button type="button" key={topFourId} onClick={() => replaceTopFour(topFourIndex)}><span>{topFourIndex+1}</span>{byId.get(topFourId)?.label}</button>)}<button className="review-replace-cancel" type="button" onClick={() => setReplacementId(null)}>Cancel</button></div>}</div>; })}</section></>}<button className="button button-primary" type="button" onClick={confirmFinal}><span>Confirm My Top 4 X-Factors</span><span>✓</span></button>{startOver}</main>}
    {response.resumeScreen === "final" && <main className="teammates-shell xfactor-shell teammate-final"><LMUScreenHeading eyebrow="X-Factor" title="Your Top 4 X-Factors" description="These are the additional capabilities, experiences, relationships, interests, tools, training, and knowledge you identified as most significant." headingRef={headingRef} /><ol>{response.finalTopFour.map((id,index) => { const item=byId.get(id); return item ? <li key={id}><span>{String(index+1).padStart(2,"0")}</span><LMUBadgeIcon name="x-factor" state="active" size={58} label="X-Factor" /><div><h2>{item.label}</h2><p>{xFactorQuestionById.get(item.questionId)?.title}</p></div></li> : null; })}</ol><button className="button button-primary" onClick={finish}><span>Finish Section</span><span>→</span></button>{startOver}</main>}
  </LMUShell>;
}
