import "server-only";

import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import type { Json, Tables } from "@/lib/supabase/database.types";
import { resourceCourseIds } from "./resource-library-policy";
export { actualUsageCount, CATEGORY_LABELS, filterResources, isResourceSelectable, normalizeExperienceIds, normalizedFileType, resourceCourseIds, RESOURCE_CATEGORIES, validateResourceCategory, type ResourceFilters } from "./resource-library-policy";

export type ResourceUsage = { resourceId: string; experienceId: string | null; experienceName: string; kind: string; detail: string };
export type LibraryResource = Tables<"resources"> & { usages: ResourceUsage[]; associatedExperienceIds: string[]; courseIds: string[] };

function object(value: unknown): Record<string, Json | undefined> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, Json | undefined> : {}; }
function id(value: unknown) { return typeof value === "string" && /^[0-9a-f-]{36}$/i.test(value) ? value : null; }

export async function loadResourceLibrary() {
  const db = createAdminSupabaseClient();
  const [resources, experiences, versions, modules, lessons, sections, blocks, blockLinks, companions, companionLinks, themes, associations] = await Promise.all([
    db.from("resources").select("*").order("created_at", { ascending: false }), db.from("experiences").select("id,name,default_theme_id"), db.from("experience_versions").select("id,experience_id,version_label,status,course_configuration,theme_id"), db.from("experience_modules").select("id,experience_version_id,title"), db.from("experience_lessons").select("id,module_id,title"), db.from("experience_sections").select("id,lesson_id,title,settings"), db.from("content_blocks").select("id,lesson_id,section_id,block_type"), db.from("content_block_resources").select("content_block_id,resource_id"), db.from("companion_modules").select("id,experience_version_id,display_title,module_type"), db.from("companion_module_resources").select("companion_module_id,resource_id,delivery_override_id"), db.from("experience_themes").select("id,name,configuration"), db.from("resource_experience_associations").select("resource_id,experience_id"),
  ]);
  const error = [resources, experiences, versions, modules, lessons, sections, blocks, blockLinks, companions, companionLinks, themes, associations].find((result) => result.error)?.error; if (error) throw new Error(`Resource Library could not be loaded: ${error.message}`);
  const experienceMap = new Map((experiences.data ?? []).map((item) => [item.id, item])); const versionMap = new Map((versions.data ?? []).map((item) => [item.id, item])); const moduleMap = new Map((modules.data ?? []).map((item) => [item.id, item])); const lessonMap = new Map((lessons.data ?? []).map((item) => [item.id, item])); const sectionMap = new Map((sections.data ?? []).map((item) => [item.id, item])); const blockMap = new Map((blocks.data ?? []).map((item) => [item.id, item])); const companionMap = new Map((companions.data ?? []).map((item) => [item.id, item]));
  const usages: ResourceUsage[] = []; const add = (resourceId: string | null, experienceId: string | null, kind: string, detail: string, fallback = "Platform") => { if (resourceId) usages.push({ resourceId, experienceId, experienceName: experienceId ? experienceMap.get(experienceId)?.name ?? "Course" : fallback, kind, detail }); };
  for (const link of blockLinks.data ?? []) { const block = blockMap.get(link.content_block_id); const lesson = block && lessonMap.get(block.lesson_id); const curriculumModule = lesson && moduleMap.get(lesson.module_id); const version = curriculumModule && versionMap.get(curriculumModule.experience_version_id); const section = block?.section_id ? sectionMap.get(block.section_id) : null; add(link.resource_id, version?.experience_id ?? null, "Course Content", [curriculumModule?.title, lesson?.title, section?.title, block?.block_type].filter(Boolean).join(" → ")); }
  for (const link of companionLinks.data ?? []) { const companion = companionMap.get(link.companion_module_id); const version = companion && versionMap.get(companion.experience_version_id); add(link.resource_id, version?.experience_id ?? null, "Companion", companion?.display_title ?? "Companion Resource"); }
  for (const version of versions.data ?? []) { const appearance = object(object(version.course_configuration).appearance); for (const [key, label] of [["logo_resource_id", "Course Logo"], ["cover_resource_id", "Course Cover"], ["header_logo_resource_id", "Header Brand Logo"]] as const) add(id(appearance[key]), version.experience_id, label, `Version ${version.version_label}`); }
  for (const section of sections.data ?? []) { const lesson = lessonMap.get(section.lesson_id); const curriculumModule = lesson && moduleMap.get(lesson.module_id); const version = curriculumModule && versionMap.get(curriculumModule.experience_version_id); add(id(object(section.settings).hero_resource_id), version?.experience_id ?? null, "Page Hero", [curriculumModule?.title, lesson?.title, section.title].filter(Boolean).join(" → ")); }
  const themeUse = new Map<string, Set<string>>(); for (const version of versions.data ?? []) if (version.theme_id) { const set = themeUse.get(version.theme_id) ?? new Set<string>(); set.add(version.experience_id); themeUse.set(version.theme_id, set); } for (const experience of experiences.data ?? []) if (experience.default_theme_id) { const set = themeUse.get(experience.default_theme_id) ?? new Set<string>(); set.add(experience.id); themeUse.set(experience.default_theme_id, set); }
  for (const theme of themes.data ?? []) { const config = object(theme.configuration); const resourceIds = [id(config.logoResourceId), id(config.coverImageResourceId), ...(Array.isArray(config.decorativeResourceIds) ? config.decorativeResourceIds.map(id) : [])].filter((value): value is string => Boolean(value)); const courseIds = [...(themeUse.get(theme.id) ?? [])]; for (const resourceId of resourceIds) { if (courseIds.length) courseIds.forEach((experienceId) => add(resourceId, experienceId, "Theme", theme.name)); else add(resourceId, null, "Theme", theme.name, "Theme"); } }
  const associated = new Map<string, string[]>(); for (const row of associations.data ?? []) associated.set(row.resource_id, [...(associated.get(row.resource_id) ?? []), row.experience_id]);
  const usageMap = new Map<string, ResourceUsage[]>(); for (const usage of usages) usageMap.set(usage.resourceId, [...(usageMap.get(usage.resourceId) ?? []), usage]);
  return { resources: (resources.data ?? []).map((resource) => { const resourceUsages = usageMap.get(resource.id) ?? []; const associatedExperienceIds = associated.get(resource.id) ?? []; return { ...resource, usages: resourceUsages, associatedExperienceIds, courseIds: resourceCourseIds(resourceUsages, associatedExperienceIds) }; }), experiences: experiences.data ?? [], usages };
}
