import type { Tables } from "@/lib/supabase/database.types";

export const RESOURCE_CATEGORIES = ["logo", "image", "template", "worksheet", "guide", "document", "pdf_reading", "branding", "other"] as const;
export const CATEGORY_LABELS: Record<string, string> = { logo: "Logo", image: "Image", template: "Template", worksheet: "Worksheet", guide: "Guide", document: "Document", pdf_reading: "PDF / Reading", branding: "Branding", other: "Other" };
export type FilterableResource = Tables<"resources"> & { usages: unknown[]; associatedExperienceIds: string[]; courseIds: string[] };
export type ResourceFilters = { q?: string; sort?: string; category?: string; type?: string; experience?: string; status?: string };
export function validateResourceCategory(value: string) { if (!RESOURCE_CATEGORIES.includes(value as typeof RESOURCE_CATEGORIES[number])) throw new Error("Choose a valid Resource category."); return value; }
export function normalizeExperienceIds(values: readonly string[]) { return [...new Set(values.filter((value) => /^[0-9a-f-]{36}$/i.test(value)))]; }
export function isResourceSelectable(status: Tables<"resources">["status"]) { return status === "active"; }
export function resourceCourseIds(usages: readonly { experienceId: string | null }[], associatedExperienceIds: readonly string[]) { return [...new Set([...usages.flatMap((usage) => usage.experienceId ? [usage.experienceId] : []), ...associatedExperienceIds])]; }
export function actualUsageCount(usages: readonly unknown[]) { return usages.length; }
export function normalizedFileType(resource: Pick<Tables<"resources">, "resource_type" | "mime_type" | "external_url">) { return resource.resource_type === "pdf" || resource.mime_type === "application/pdf" ? "pdf" : resource.resource_type === "image" || resource.mime_type?.startsWith("image/") ? "image" : resource.external_url || resource.resource_type === "link" ? "link" : ["download", "worksheet", "guide", "article"].includes(resource.resource_type) ? "document" : "other"; }
export function filterResources<T extends FilterableResource>(resources: T[], filters: ResourceFilters) { const q = filters.q?.trim().toLocaleLowerCase() ?? ""; const status = filters.status || "usable"; return resources.filter((resource) => status === "all" ? true : status === "usable" ? resource.status !== "archived" : resource.status === status).filter((resource) => !q || [resource.title, resource.original_filename, resource.description].some((value) => value?.toLocaleLowerCase().includes(q))).filter((resource) => !filters.category || resource.resource_category === filters.category).filter((resource) => !filters.type || normalizedFileType(resource) === filters.type).filter((resource) => !filters.experience || resource.courseIds.includes(filters.experience)).sort((a, b) => filters.sort === "oldest" ? a.created_at.localeCompare(b.created_at) : filters.sort === "az" ? a.title.localeCompare(b.title) : filters.sort === "za" ? b.title.localeCompare(a.title) : b.created_at.localeCompare(a.created_at)); }
