import assert from "node:assert/strict";
import test from "node:test";
import { catalogParticipantCourseHref, featuredParticipantCourseEntry, resolveParticipantCourseEntries } from "./participant-course-context.ts";

const enrollment = { id: "enrollment", experience_id: "course", experience_version_id: "v1" };
const experience = { id: "course", slug: "kaleo" };
const cohorts = [{ id: "tuesday", name: "Tuesday Group", experience_id: "course", status: "active" }, { id: "thursday", name: "Thursday Group", experience_id: "course", status: "active" }];
const offerings = cohorts.map((cohort) => ({ cohort_id: cohort.id, experience_id: "course", experience_version_id: "v1", status: "active" }));
const member = (cohort_id: string, membership_role = "participant", status = "active") => ({ cohort_id, membership_role, status });

test("zero Cohorts produces one personal entry", () => assert.deepEqual(resolveParticipantCourseEntries({ enrollment, experience, memberships: [], cohorts, offerings }).map((entry) => entry.type), ["personal"]));
test("one Cohort replaces the personal entry and routes directly", () => { const entries = resolveParticipantCourseEntries({ enrollment, experience, memberships: [member("tuesday")], cohorts, offerings }); assert.equal(entries.length, 1); assert.equal(entries[0].type, "cohort"); assert.equal(entries[0].href, "/experiences/kaleo?cohort=tuesday"); assert.equal(featuredParticipantCourseEntry(entries)?.cohortId, "tuesday"); });
test("two Cohorts remain distinct without a personal fallback", () => { const entries = resolveParticipantCourseEntries({ enrollment, experience, memberships: [member("tuesday"), member("thursday")], cohorts, offerings }); assert.deepEqual(entries.map((entry) => entry.cohortId).toSorted(), ["thursday", "tuesday"]); assert.equal(entries.some((entry) => entry.type === "personal"), false); assert.equal(featuredParticipantCourseEntry(entries)?.type, "cohort"); });
test("participant, facilitator, and leader roles preserve Cohort context", () => { for (const role of ["participant", "facilitator", "leader"]) { const [entry] = resolveParticipantCourseEntries({ enrollment, experience, memberships: [member("tuesday", role)], cohorts, offerings }); assert.equal(entry.type, "cohort"); assert.equal(entry.role, role); } });
test("archived or inaccessible Cohorts do not suppress personal access", () => { const entries = resolveParticipantCourseEntries({ enrollment, experience, memberships: [member("tuesday", "participant", "completed")], cohorts, offerings }); assert.equal(entries[0].type, "personal"); const archived = resolveParticipantCourseEntries({ enrollment, experience, memberships: [member("tuesday")], cohorts: [{ ...cohorts[0], status: "archived" }], offerings }); assert.equal(archived[0].type, "personal"); });
test("wrong-version and ambiguous offerings do not suppress personal access", () => { const wrong = [{ ...offerings[0], experience_version_id: "v2" }]; assert.equal(resolveParticipantCourseEntries({ enrollment, experience, memberships: [member("tuesday")], cohorts, offerings: wrong })[0].type, "personal"); assert.equal(resolveParticipantCourseEntries({ enrollment, experience, memberships: [member("tuesday")], cohorts, offerings: [offerings[0], { ...offerings[0] }] })[0].type, "personal"); });
test("catalog opens one valid context and sends multiple contexts to My Trainings", () => { const one = resolveParticipantCourseEntries({ enrollment, experience, memberships: [member("tuesday")], cohorts, offerings }); const two = resolveParticipantCourseEntries({ enrollment, experience, memberships: [member("tuesday"), member("thursday")], cohorts, offerings }); assert.equal(catalogParticipantCourseHref("/experiences/kaleo", one), "/experiences/kaleo?cohort=tuesday"); assert.equal(catalogParticipantCourseHref("/experiences/kaleo", two), "/dashboard#trainings"); assert.equal(catalogParticipantCourseHref("/experiences/kaleo", []), "/experiences/kaleo"); });
