import Link from "next/link";
import { AdminPageHeader, AdminShell } from "@/components/admin/AdminShell";
import { requireAdmin } from "@/lib/admin/auth";
import { getAdminExperienceIndex } from "@/lib/experiences/admin/data";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import { createExperienceAction } from "../actions";

export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const admin = await requireAdmin();
  const { error } = await searchParams;
  const [{ organizations }, themes] = await Promise.all([getAdminExperienceIndex(), createAdminSupabaseClient().from("experience_themes").select("id,name,organization_id").eq("status", "active").order("name")]);
  return <AdminShell admin={admin}><AdminPageHeader eyebrow="Experience registry" title="Create Experience" description="Create the identity and, for builder or hybrid delivery, its initial draft version." action={<Link className="admin-secondary-link" href="/admin/trainings">Back to registry</Link>}/>{error && <p className="admin-form-message" role="alert">{error}</p>}<form action={createExperienceAction} className="admin-form admin-experience-form"><label>Name<input name="name" required maxLength={160}/></label><label>Slug<input name="slug" required maxLength={120} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="example-experience"/></label><label className="is-wide">Description<textarea name="description" maxLength={3000}/></label><label>Experience type<select name="experience_type" defaultValue="course">{["assessment","course","training","workshop","pathway","cohort_pathway","retreat","activity","resource"].map(value => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label><label>Delivery mode<select name="delivery_mode" defaultValue="builder"><option value="builder">Builder</option><option value="hybrid">Hybrid</option><option value="custom_code">Custom code</option></select></label><label>Visibility<select name="visibility" defaultValue="private"><option value="private">Private</option><option value="unlisted">Unlisted</option><option value="public">Public</option></select></label><label>Owner organization<select name="owner_organization_id" defaultValue=""><option value="">Platform</option>{organizations.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Default theme<select name="default_theme_id" defaultValue=""><option value="">No theme</option>{(themes.data ?? []).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><p className="admin-field-note is-wide">Custom-code experiences require a source-controlled runtime registration before launch. Slugs and delivery mode are protected after creation.</p><button className="admin-primary" type="submit">Create Experience</button></form></AdminShell>;
}
