import Link from "next/link";
import { AdminPageHeader, AdminShell } from "@/components/admin/AdminShell";
import { requireAdmin } from "@/lib/admin/auth";
import { formatDate, humanize } from "@/lib/admin/format";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";

export default async function Page({ searchParams }: { searchParams: Promise<{ q?: string; role?: string; status?: string }> }) {
  const identity=await requireAdmin(); const {q="",role="all",status="all"}=await searchParams; const db=createAdminSupabaseClient();
  const [peopleResult,assessmentResult,memberResult]=await Promise.all([db.from("participants").select("id,auth_user_id,full_name,first_name,email,created_at,updated_at").order("created_at",{ascending:false}),db.from("lmu_assessments").select("participant_id,status,updated_at"),db.from("admin_members").select("auth_user_id,role,status")]);
  const people=peopleResult.data??[],assessments=assessmentResult.data??[],members=memberResult.data??[]; const assessmentByPerson=new Map(assessments.map(a=>[a.participant_id,a])); const adminByAuth=new Map(members.filter(m=>m.auth_user_id).map(m=>[m.auth_user_id,m])); const search=q.trim().toLowerCase();
  const rows=people.filter(person=>{const member=person.auth_user_id?adminByAuth.get(person.auth_user_id):undefined;const access=member?.role??"none";const accountStatus=person.auth_user_id?"active":"unclaimed";return(!search||`${person.full_name??person.first_name} ${person.email}`.toLowerCase().includes(search))&&(role==="all"||role===access)&&(status==="all"||status===accountStatus)});
  return <AdminShell admin={identity}><AdminPageHeader eyebrow="Purpose OS CRM" title="Wayfinders" description="Every Purpose OS participant is a Wayfinder. Manage additional access, communities, and journey relationships without reducing a person to one role." action={identity.role==="super_admin"?<Link className="admin-primary admin-primary-link" href="/admin/users/new">Create Wayfinder</Link>:undefined}/><form className="admin-filter"><label>Search<input name="q" defaultValue={q} placeholder="Name or email"/></label><label>Additional access<select name="role" defaultValue={role}><option value="all">All Wayfinders</option><option value="none">No admin access</option><option value="admin">Admins</option><option value="super_admin">Super Admins</option></select></label><label>Status<select name="status" defaultValue={status}><option value="all">All statuses</option><option value="active">Active</option><option value="unclaimed">Unclaimed</option></select></label><button className="admin-primary">Apply</button></form><div className="admin-table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Identity</th><th>Additional access</th><th>Experiences</th><th>Last activity</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(person=>{const assessment=assessmentByPerson.get(person.id),member=person.auth_user_id?adminByAuth.get(person.auth_user_id):undefined;return <tr key={person.id}><td>{person.full_name??person.first_name}</td><td>{person.email}</td><td>Wayfinder</td><td>{member?humanize(member.role):"—"}</td><td>{assessment?`Life Mapping U · ${humanize(assessment.status)}`:"—"}</td><td>{formatDate(assessment?.updated_at??person.updated_at)}</td><td><span className={`admin-status is-${person.auth_user_id?"active":"unclaimed"}`}>{person.auth_user_id?"Active":"Unclaimed"}</span></td><td><Link href={`/admin/users/${person.id}`}>View Wayfinder</Link></td></tr>})}{!rows.length&&<tr><td colSpan={8}>No Wayfinders match this view.</td></tr>}</tbody></table></div><aside className="admin-crm-readiness"><strong>IDENTITY MODEL</strong><span>Wayfinder is universal. Scoped permissions, memberships, cohorts, enrollments, and journey classifications remain additive.</span></aside></AdminShell>;
}
