import Link from "next/link";
import { AdminPageHeader, AdminShell } from "@/components/admin/AdminShell";
import { requireAdmin } from "@/lib/admin/auth";
import { formatDate, humanize } from "@/lib/admin/format";
import { loadWayfinderRegistry, WAYFINDER_PAGE_SIZE } from "@/lib/admin/wayfinders/data";

type Search = { q?: string; hub?: string; role?: string; tag?: string; account?: string; experience?: string; cohort?: string; sort?: string; page?: string };
const valuesFor = <T extends { participant_id: string }>(rows: T[], id: string) => rows.filter((row) => row.participant_id === id);

export default async function Page({ searchParams }: { searchParams: Promise<Search> }) {
  const identity = await requireAdmin(); const params = await searchParams;
  const filters = { q: params.q?.trim() ?? "", hub: params.hub ?? "", role: params.role ?? "", tag: params.tag ?? "", account: params.account ?? "", experience: params.experience ?? "", cohort: params.cohort ?? "", sort: params.sort ?? "recent", page: Math.max(1, Number(params.page) || 1) };
  const data = await loadWayfinderRegistry(filters);
  const hubNames = new Map(data.hubs.map((item) => [item.id, item.name])); const tagNames = new Map(data.tags.map((item) => [item.id, item.name])); const experienceNames = new Map(data.experiences.map((item) => [item.id, item.name]));
  const pageCount = Math.max(1, Math.ceil(data.count / WAYFINDER_PAGE_SIZE));
  const pageHref = (page: number) => `/admin/users?${new URLSearchParams({ ...Object.fromEntries(Object.entries(filters).filter(([key, value]) => key !== "page" && value !== "" && value !== "recent").map(([key, value]) => [key, String(value)])), page: String(page) }).toString()}`;
  return <AdminShell admin={identity}><AdminPageHeader eyebrow="Purpose OS CRM" title="Wayfinders" description="Canonical people, relationships, journeys, access, and follow-up context in one operational workspace." action={<div className="admin-page-actions"><Link className="admin-secondary-link" href="/admin/users/import">Import Wayfinders</Link>{identity.role === "super_admin" && <Link className="admin-primary admin-primary-link" href="/admin/users/new">Create Wayfinder</Link>}</div>}/>
    <form className="crm-registry-filters"><label>Search<input name="q" defaultValue={filters.q} placeholder="Name or email"/></label><label>Hub<select name="hub" defaultValue={filters.hub}><option value="">All Hubs</option>{data.hubs.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Role<select name="role" defaultValue={filters.role}><option value="">All roles</option><option value="hub_leader">Hub Leader</option><option value="facilitator">Facilitator</option><option value="organization_admin">Organization Admin</option></select></label><label>Classification<select name="tag" defaultValue={filters.tag}><option value="">All classifications</option>{data.tags.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Experience<select name="experience" defaultValue={filters.experience}><option value="">All experiences</option>{data.experiences.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Cohort<select name="cohort" defaultValue={filters.cohort}><option value="">All cohorts</option>{data.cohorts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Account<select name="account" defaultValue={filters.account}><option value="">All accounts</option><option value="active">Active</option><option value="unclaimed">Unclaimed</option></select></label><label>Sort<select name="sort" defaultValue={filters.sort}><option value="recent">Recently joined</option><option value="updated">Recently active</option><option value="name">Name</option></select></label><button className="admin-primary">Apply filters</button><Link className="admin-secondary-link" href="/admin/users">Clear</Link></form>
    <div className="crm-registry-summary"><strong>{data.count}</strong><span>Wayfinders · Table view</span></div>
    <div className="admin-table-wrap crm-registry-table"><table><thead><tr><th>Wayfinder</th><th>Primary Hub</th><th>Other Hubs</th><th>Leadership</th><th>Journey</th><th>Classifications</th><th>Last activity</th><th>Account</th></tr></thead><tbody>{data.people.map((person) => { const hubs = valuesFor(data.hubRows, person.id); const preference = data.preferences.find((row) => row.participant_id === person.id); const roles = person.auth_user_id ? data.scopedRoles.filter((row) => row.auth_user_id === person.auth_user_id) : []; const member = person.auth_user_id ? data.adminMembers.find((row) => row.auth_user_id === person.auth_user_id) : undefined; const assessment = data.assessments.find((row) => row.participant_id === person.id); const enrollments = valuesFor(data.enrollments, person.id); const tags = valuesFor(data.tagRows, person.id); const latest = [person.updated_at, assessment?.updated_at, ...enrollments.map((row) => row.updated_at)].filter((value): value is string => Boolean(value)).sort().at(-1) ?? person.updated_at; const accountStatus = data.linkingIssueIds.has(person.id) ? "Linking issue" : person.auth_user_id ? "Active" : "Not activated"; return <tr key={person.id}><td><Link className="crm-person-link" href={`/admin/users/${person.id}`}><strong>{person.full_name ?? person.first_name}</strong><span>{person.email}</span></Link></td><td>{preference?.default_hub_id ? hubNames.get(preference.default_hub_id) ?? "Unavailable Hub" : "—"}</td><td>{hubs.filter((row) => row.hub_id !== preference?.default_hub_id).map((row) => hubNames.get(row.hub_id) ?? "Unavailable Hub").join(", ") || "—"}</td><td>{[member?.role, ...roles.map((row) => row.role)].filter((value): value is string => Boolean(value)).map(humanize).join(", ") || "—"}</td><td>{[assessment ? `LMU · ${humanize(assessment.status)}` : "", ...enrollments.map((row) => `${experienceNames.get(row.experience_id) ?? "Experience"} · ${humanize(row.status)}`)].filter(Boolean).join("; ") || "—"}</td><td>{tags.map((row) => tagNames.get(row.tag_id) ?? "Unavailable tag").join(", ") || "—"}</td><td>{formatDate(latest)}</td><td><span className={`admin-status is-${data.linkingIssueIds.has(person.id) ? "issue" : person.auth_user_id ? "active" : "unclaimed"}`}>{accountStatus}</span></td></tr>; })}{!data.people.length && <tr><td colSpan={8}>No Wayfinders match this view.</td></tr>}</tbody></table></div>
    <nav aria-label="Wayfinder pages" className="crm-pagination"><span>Page {filters.page} of {pageCount}</span>{filters.page > 1 && <Link href={pageHref(filters.page - 1)}>Previous</Link>}{filters.page < pageCount && <Link href={pageHref(filters.page + 1)}>Next</Link>}</nav>
  </AdminShell>;
}
