export interface TeammatePainPoint { id: string; originalLabel: string; displayLabel: string; label: string; examplePrompts: [string, string] }

const displayLabelOverrides: Record<string, string> = {
  "Closed": "Closed off or difficult to connect with",
  "Apologetic": "Overly apologetic or lacking confidence",
  "Exhibits low self-image": "Frequently doubts their own ability or value",
  "Controllers": "Tries to control other people or decisions",
  "Ego": "Ego-driven or overly focused on themselves",
  "Inconsistant": "Inconsistent",
  "Loudmouth": "Dominates conversations or talks over others",
  "Blamers": "Blames others rather than taking responsibility",
  "Authoritarian": "Expects compliance without inviting input",
  "Closed to new ideas": "Unwilling to consider new ideas",
  "One who avoids people": "Avoids interaction or connection with others",
  "Legalistic": "Overly rigid about rules and procedures",
  "Complainers": "Frequently complains without helping solve the problem",
  "Single-minded": "Unwilling to consider other perspectives",
  "Gossipers": "Talks about others behind their backs",
  "Company people": "Puts organizational loyalty ahead of people or good judgment",
  "Workaholics": "Does not maintain healthy boundaries around work",
  "Overly sales-y": "Pushy or overly focused on selling",
  "Clock watcher": "Overly focused on hours rather than contribution",
  "Plays to safe": "Plays it too safe or avoids reasonable risk",
  "Others are disposable": "Treats people as replaceable or disposable",
};

const slug = (label: string) => label.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
const item = (originalLabel: string, first: string, second: string): TeammatePainPoint => ({
  id: slug(originalLabel), originalLabel, displayLabel: displayLabelOverrides[originalLabel] ?? originalLabel, label: displayLabelOverrides[originalLabel] ?? originalLabel,
  examplePrompts: [`I value teammates who ${first}.`, `I work best with people who ${second}.`],
});

export const teammatePainPoints: TeammatePainPoint[] = [
  item("Closed", "share what they are thinking and make room for honest conversation", "are approachable and willing to talk things through"),
  item("Apologetic", "speak with confidence while taking responsibility when it is needed", "can contribute without continually second-guessing themselves"),
  item("Exhibits low self-image", "recognize their strengths and accept encouragement from others", "bring a grounded sense of confidence to the team"),
  item("Controllers", "invite others into decisions and share responsibility", "trust others to contribute without controlling every detail"),
  item("Ego", "stay curious about other perspectives and share credit", "put the team and the work ahead of personal recognition"),
  item("Inconsistant", "follow through and communicate when plans need to change", "show up dependably so others know what to expect"),
  item("Uncooperative", "look for ways to contribute and work toward shared outcomes", "collaborate willingly even when the work is difficult"),
  item("Disorganized", "keep track of commitments and communicate clear next steps", "bring enough structure that shared work can move forward"),
  item("Lazy", "carry their share of the work and take useful initiative", "contribute steady effort without needing to be continually pushed"),
  item("Loudmouth", "listen as thoughtfully as they speak and leave room for others", "communicate confidently without dominating the conversation"),
  item("Blamers", "focus on solutions and own their part when something goes wrong", "address problems without making another person the target"),
  item("Ruthless", "pursue results without losing sight of people", "make difficult decisions with care and humanity"),
  item("Demanding", "make clear requests while respecting other people’s capacity", "work through expectations collaboratively rather than issuing demands"),
  item("Unfair", "apply expectations consistently and consider each person’s circumstances", "make decisions transparently and treat people equitably"),
  item("Authoritarian", "invite input and explain the reasoning behind decisions", "use authority with humility and respect for others’ judgment"),
  item("Closed to new ideas", "listen to different ideas and explore them before deciding", "stay open to collaboration and changing their mind"),
  item("Rude", "listen well and respond respectfully even when they disagree", "speak considerately and notice how their words affect others"),
  item("One who avoids people", "stay available and engaged when collaboration is needed", "build working relationships instead of disappearing from the team"),
  item("Aggressive", "address concerns directly without intimidating others", "communicate firmly while keeping the conversation safe and respectful"),
  item("Legalistic", "use guidelines thoughtfully while considering context", "balance consistency with sound judgment and compassion"),
  item("Complainers", "name concerns constructively and help identify a way forward", "bring problems with a willingness to participate in solutions"),
  item("Single-minded", "consider the wider picture and make room for other priorities", "stay focused while remaining responsive to new information"),
  item("Gossipers", "speak directly to the people involved and protect trust", "handle sensitive information with discretion and integrity"),
  item("Company people", "think independently while supporting the shared mission", "can question an organizational decision respectfully when needed"),
  item("Low self-awareness", "reflect on their impact and respond to useful feedback", "notice their patterns and adjust how they work with others"),
  item("Overbearing", "make space for others and influence without overpowering", "offer direction while respecting other people’s agency"),
  item("Defensive", "hear feedback with curiosity before reacting", "can discuss mistakes or concerns without immediately protecting themselves"),
  item("Dishonest", "tell the truth clearly and keep their commitments", "build trust by being candid about what is happening"),
  item("Manipulative", "state what they need directly and respect others’ choices", "influence through honest conversation rather than hidden pressure"),
  item("Sexist", "respect people equally regardless of gender", "challenge bias and make space for everyone’s contribution"),
  item("Unethical", "act with integrity even when doing so is inconvenient", "consider the human consequences of their choices"),
  item("Workaholics", "work with commitment while respecting healthy boundaries", "make room for rest and life outside of work"),
  item("Irresponsible", "take ownership and follow through on what they commit to", "communicate early when they need help meeting a responsibility"),
  item("Overly sales-y", "communicate honestly without pressuring people", "build trust and let the value of an idea speak clearly"),
  item("Too serious", "bring perspective and appropriate lightness to the work", "can be focused without making every moment feel heavy"),
  item("Always late", "respect shared time and communicate promptly about delays", "arrive prepared when others are depending on them"),
  item("Arrogant", "show confidence while remaining teachable", "respect what others know and acknowledge when they have more to learn"),
  item("Overly emotional", "express feelings honestly without making others manage them", "stay grounded enough to work through charged moments constructively"),
  item("Low self-disclosure", "share relevant context so others can understand and work with them", "build trust by being appropriately open about their perspective"),
  item("Highly political", "make decisions based on the work rather than status or alliances", "communicate directly instead of maneuvering behind the scenes"),
  item("Clock watcher", "stay engaged with the team’s needs while maintaining boundaries", "focus on meaningful contribution rather than doing only the minimum"),
  item("Condescending", "speak to others as capable peers", "explain ideas without talking down to people"),
  item("Racist", "respect people of every race and actively oppose discriminatory behavior", "create belonging and take responsibility for their biases"),
  item("Hypocritical", "align their actions with the standards they expect from others", "acknowledge inconsistencies and work to correct them"),
  item("Plays to safe", "raise thoughtful concerns and take responsible risks", "speak up when a better path may be possible"),
  item("Rigid", "adapt when circumstances or good information change", "bring structure without insisting there is only one acceptable way"),
  item("Others are disposable", "treat people as valuable beyond their immediate usefulness", "make decisions with loyalty, dignity, and care for those affected"),
  item("Overly formal", "communicate professionally while still being warm and approachable", "allow relationships to feel human rather than unnecessarily distant"),
];

export const teammatePainPointById = new Map(teammatePainPoints.map((painPoint) => [painPoint.id, painPoint]));
