import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/AdminShell";
import { WayfinderNoteForm, WayfinderProfileForm } from "@/components/admin/WayfinderCrmForms";
import { WayfinderRelationshipManager } from "@/components/admin/WayfinderRelationshipManager";
import { WayfinderAuthorityManager } from "@/components/admin/WayfinderAuthorityManager";
import { WayfinderFutureSection, WayfinderWorkspaceTabs } from "@/components/admin/WayfinderWorkspace";
import { requireAdmin } from "@/lib/admin/auth";
import { formatDate, humanize } from "@/lib/admin/format";
import { loadWayfinderWorkspace } from "@/lib/admin/wayfinders/data";

export default async function Page({ params }: { params: Promise<{ userId: string }> }) {
  const identity = await requireAdmin(); const { userId } = await params; const data = await loadWayfinderWorkspace(userId); const user = data.participant; if (!user) notFound();
  const orgNames = new Map(data.orgs.map((item) => [item.id, item.name])); const hubNames = new Map(data.hubs.map((item) => [item.id, item.name])); const cohortNames = new Map(data.cohorts.map((item) => [item.id, item.name])); const tagNames = new Map(data.tags.map((item) => [item.id, item.name])); const experienceNames = new Map(data.experiences.map((item) => [item.id, item.name])); const offeringNames = new Map(data.offerings.map((item) => [item.id, item.name]));
  const existing = [...data.orgMemberships.filter((item) => item.status === "active").map((item) => ({ kind: "organization" as const, targetId: item.organization_id, name: orgNames.get(item.organization_id) ?? "Unavailable Partner", role: item.membership_role })), ...data.hubMemberships.filter((item) => item.status === "active").map((item) => ({ kind: "hub" as const, targetId: item.hub_id, name: hubNames.get(item.hub_id) ?? "Unavailable Hub", role: item.membership_role })), ...data.cohortMemberships.filter((item) => ["active", "completed"].includes(item.status)).map((item) => ({ kind: "cohort" as const, targetId: item.cohort_id, name: cohortNames.get(item.cohort_id) ?? "Unavailable Cohort", role: item.membership_role })), ...data.participantTags.map((item) => ({ kind: "tag" as const, targetId: item.tag_id, name: tagNames.get(item.tag_id) ?? "Unavailable classification", role: "classification" }))];
  const initials = (user.full_name ?? user.first_name).split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  const timeline = [{ id: `created-${user.id}`, label: "Wayfinder created", detail: user.email, at: user.created_at }, ...data.notes.map((note) => ({ id: `note-${note.id}`, label: "CRM note", detail: note.body, at: note.created_at })), ...data.auditRows.map((event) => ({ id: `audit-${event.id}`, label: humanize(event.action), detail: event.admin_email, at: event.created_at })), ...data.hubMemberships.map((item) => ({ id: `hub-${item.hub_id}-${item.created_at}`, label: "Hub membership", detail: `${hubNames.get(item.hub_id) ?? "Unavailable Hub"} · ${humanize(item.status)}`, at: item.joined_at ?? item.created_at })), ...data.participantTags.map((item) => ({ id: `tag-${item.tag_id}`, label: "Classification added", detail: tagNames.get(item.tag_id) ?? "Unavailable classification", at: item.created_at })), ...data.assessments.map((item) => ({ id: `lmu-${item.id}`, label: item.status === "completed" ? "Life Mapping U completed" : "Life Mapping U started", detail: humanize(item.current_module ?? item.status), at: item.completed_at ?? item.started_at }))].sort((a, b) => b.at.localeCompare(a.at));
  const defaultHub = data.preferences?.default_hub_id ? hubNames.get(data.preferences.default_hub_id) : null;
  return <AdminShell admin={identity}><header className="crm-wayfinder-header"><div className="crm-avatar" aria-hidden="true">{initials}</div><div><p className="admin-kicker">Wayfinder CRM</p><h1>{user.full_name ?? user.first_name}</h1><p>{user.email}</p><div className="crm-context-chips"><span>{data.accountLinkingIssue ? "Account-linking issue" : user.auth_user_id ? "Account active" : "Account not yet activated"}</span>{defaultHub && <span>{defaultHub}</span>}{data.adminMember && <span>{humanize(data.adminMember.role)}</span>}{data.roles.slice(0, 2).map((role) => <span key={role.id}>{humanize(role.role)}</span>)}</div></div></header>
    <WayfinderWorkspaceTabs/>
    <section className="crm-workspace-section" id="overview"><header><p className="admin-kicker">Overview</p><h2>At a glance</h2></header><div className="crm-overview-grid"><article><span>Profile</span><strong>{user.preferred_name ?? user.full_name ?? user.first_name}</strong><p>{[user.city, user.state_region, user.country].filter(Boolean).join(", ") || "No location added"}</p></article><article><span>Community</span><strong>{defaultHub ?? `${data.hubMemberships.filter((item) => item.status === "active").length} active Hubs`}</strong><p>{data.cohortMemberships.filter((item) => item.status === "active").length} active cohorts</p></article><article><span>Leadership</span><strong>{data.adminMember ? humanize(data.adminMember.role) : data.roles.length ? humanize(data.roles[0].role) : "Wayfinder"}</strong><p>{data.roles.length} scoped assignments</p></article><article><span>Current journey</span><strong>{data.assessments[0] ? `Life Mapping U · ${humanize(data.assessments[0].status)}` : data.enrollments[0] ? `${experienceNames.get(data.enrollments[0].experience_id) ?? "Experience"} · ${humanize(data.enrollments[0].status)}` : "No active journey"}</strong><p>Follow-ups will use the unified Task system.</p></article></div></section>
    <section className="crm-workspace-section" id="profile"><header><p className="admin-kicker">Profile</p><h2>Contact information</h2><p>Email remains read-only because it is tied to account identity.</p></header><WayfinderProfileForm participantId={user.id} profile={user}/></section>
    <section className="crm-workspace-section" id="journey"><header><p className="admin-kicker">Journey</p><h2>Experiences and progress</h2></header><div className="crm-panel-grid"><article><h3>Life Mapping U</h3>{data.assessments.map((assessment) => <div className="admin-record-row" key={assessment.id}><div><strong>{humanize(assessment.status)}</strong><span>Started {formatDate(assessment.started_at)}{assessment.completed_at ? ` · Completed ${formatDate(assessment.completed_at)}` : ` · ${humanize(assessment.current_module ?? "In progress")}`}</span></div><Link href={`/admin/assessments/life-mapping-u/${assessment.id}`}>View results</Link></div>)}{!data.assessments.length && <p>No Life Mapping U assessment records.</p>}</article><article><h3>Experiences</h3>{data.enrollments.map((enrollment) => <div className="admin-record-row" key={enrollment.id}><div><strong>{experienceNames.get(enrollment.experience_id) ?? "Unavailable experience"}</strong><span>{humanize(enrollment.status)} · Enrolled {formatDate(enrollment.enrolled_at)}</span></div></div>)}{!data.enrollments.length && <p>No experience enrollments.</p>}</article><article><h3>Cohorts</h3>{data.cohortMemberships.map((membership) => <div className="admin-record-row" key={`${membership.cohort_id}-${membership.membership_role}`}><div><strong>{cohortNames.get(membership.cohort_id) ?? "Unavailable cohort"}</strong><span>{humanize(membership.membership_role)} · {humanize(membership.status)}</span></div></div>)}{!data.cohortMemberships.length && <p>No cohort memberships.</p>}</article><article><h3>Certificates</h3><p>Certificates will appear here when the certificate domain is implemented.</p></article></div></section>
    <section className="crm-workspace-section" id="communities"><header><p className="admin-kicker">Communities</p><h2>Memberships and classifications</h2><p>Default Hub is context only. Memberships and classifications never grant authorization.</p></header><WayfinderRelationshipManager participantId={user.id} organizations={data.orgs.filter((item) => item.status === "active")} hubs={data.hubs.filter((item) => item.status === "active")} cohorts={data.cohorts.filter((item) => ["open", "active"].includes(item.status))} tags={data.tags.filter((item) => item.status === "active" || data.participantTags.some((assignment) => assignment.tag_id === item.id))} existing={existing} defaultHubId={data.preferences?.default_hub_id} canManageLeadership canManageDefinitions={identity.role === "super_admin"}/></section>
    <section className="crm-workspace-section" id="access"><header><p className="admin-kicker">Access &amp; Leadership</p><h2>Authority and experience access</h2><p>Global administration and Hub-scoped leadership are managed independently from membership and participation.</p></header>
      <WayfinderAuthorityManager participantId={user.id} participantName={user.full_name ?? user.first_name} accountActive={Boolean(user.auth_user_id)} actorRole={identity.role} isSelf={user.auth_user_id === identity.id} administratorRole={data.adminMember?.role ?? null} administratorActive={Boolean(data.adminMember && ["admin", "super_admin"].includes(data.adminMember.role) && data.adminMember.status === "active")} courseCreatorActive={data.roles.some((role) => role.role === "course_creator" && role.scope_type === "global" && role.scope_id === null)} hubs={data.hubs.filter((hub) => hub.status === "active")} leaderHubIds={data.roles.filter((role) => role.role === "hub_leader" && role.scope_type === "hub" && role.scope_id).map((role) => role.scope_id!)} entitlements={data.entitlementCatalog} roleEntitlements={data.roleEntitlementDefaults} entitlementOverrides={data.entitlementOverrides}/>
      <div className="crm-panel-grid"><article><h3>Current Authorization</h3>{data.adminMember && <div className="admin-record-row"><div><strong>{humanize(data.adminMember.role)}</strong><span>Global · {humanize(data.adminMember.status)}</span></div></div>}{data.roles.map((role) => <div className="admin-record-row" key={role.id}><div><strong>{humanize(role.role)}</strong><span>{humanize(role.scope_type)} · {role.scope_id ? hubNames.get(role.scope_id) ?? cohortNames.get(role.scope_id) ?? orgNames.get(role.scope_id) ?? role.scope_id : "Global"}</span></div></div>)}{!data.adminMember && !data.roles.length && <p>No additional platform authorization.</p>}</article><article><h3>Entitlements</h3>{data.entitlements.map((item, index) => <div className="admin-record-row" key={`${item.experience_id}-${item.source_type}-${index}`}><div><strong>{experienceNames.get(item.experience_id) ?? "Unavailable experience"}</strong><span>{humanize(item.status)} · Why: {humanize(item.source_type)}</span></div></div>)}{data.assignments.map((item) => <div className="admin-record-row" key={item.offering_id}><div><strong>{offeringNames.get(item.offering_id) ?? "Unavailable offering"}</strong><span>{humanize(item.status)} · Why: {humanize(item.source_type)}</span></div></div>)}{!data.entitlements.length && !data.assignments.length && <p>No explicit entitlements or offering assignments.</p>}</article></div>
    </section>
    <section className="crm-workspace-section" id="crm"><header><p className="admin-kicker">CRM</p><h2>Relationship notes and follow-up</h2><p>Notes are internal operational context. Follow-up persistence is deferred to the unified Task system.</p></header><WayfinderNoteForm participantId={user.id}/><div className="crm-notes">{data.notes.map((note) => <article key={note.id}><p>{note.body}</p><time>{formatDate(note.created_at)}</time></article>)}{!data.notes.length && <p>No internal CRM notes yet.</p>}</div><aside className="crm-future-links"><span>Future linked records</span><p>Related Tasks, Projects, Events, Files, and Certificates will connect here through their canonical systems.</p></aside></section>
    <WayfinderFutureSection id="engagement" eyebrow="Engagement" title="Participation beyond courses" description="Events, forms, workshops, retreats, service, and other meaningful participation will gather here through their canonical systems." cards={[{title:"Events & workshops",description:"No event or workshop participation is connected yet."},{title:"Forms & applications",description:"No submitted forms are connected yet."},{title:"Service & volunteering",description:"No service participation records are connected yet."}]}/>
    <WayfinderFutureSection id="relationships" eyebrow="Relationships" title="Who matters around this person" description="Mentors, disciplers, coaches, referral sources, staff owners, and significant people will live here without being confused with community membership." cards={[{title:"Key people",description:"No person-to-person relationship system is connected yet."},{title:"Relationship context",description:"Referral and staff stewardship fields will connect when the relationship domain is defined."}]}/>
    <section className="crm-workspace-section" id="activity"><header><p className="admin-kicker">Activity</p><h2>Timeline</h2><p>Composed from real audit, membership, classification, assessment, note, and creation events. Private LMU responses are excluded.</p></header><ol className="crm-timeline">{timeline.map((item) => <li key={item.id}><time>{formatDate(item.at)}</time><div><strong>{item.label}</strong><p>{item.detail}</p></div></li>)}</ol></section>
    <WayfinderFutureSection id="files" eyebrow="Files & Records" title="Documents that belong to this person" description="Assessment reports, certificates, signed forms, attachments, and shared-drive references will connect here through the future platform file system." cards={[{title:"Files",description:"No uploaded documents are connected yet."},{title:"Certificates",description:"No credentials have been issued yet."},{title:"Signed records",description:"No forms, waivers, or acknowledgements are connected yet."}]}/>
  </AdminShell>;
}
