"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { audit, requireAdmin } from "@/lib/admin/auth";
import { canBuildExperienceById, getAuthorizationContext } from "@/lib/platform/authorization";
import { getExperienceStructure } from "@/lib/experiences/builder/data";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";

export async function saveJourneyVisibilityAction(experienceId: string, offeringId: string, form: FormData) {
  const admin = await requireAdmin(); const authorization = await getAuthorizationContext(admin.id, admin.email); if (!await canBuildExperienceById(authorization, experienceId)) throw new Error("You are not authorized to configure this Journey.");
  const db = createAdminSupabaseClient(); const offering = await db.from("experience_offerings").select("*").eq("id", offeringId).eq("experience_id", experienceId).maybeSingle();
  if (!offering.data?.experience_version_id) throw new Error("Pin this offering to a Course Version first.");
  const structure = await getExperienceStructure(experienceId, offering.data.experience_version_id, db); const visibleModules = new Set(form.getAll("visible_module").map(String)); const visibleLessons = new Set(form.getAll("visible_lesson").map(String)); const visibleSections = new Set(form.getAll("visible_section").map(String)); const hiddenLessons = structure.modules.flatMap((module) => module.lessons).filter((lesson) => !visibleLessons.has(lesson.id)).map((lesson) => lesson.id);
  if (offering.data.cohort_id) {
    const existing = await db.from("cohort_course_plans").select("id").eq("cohort_id", offering.data.cohort_id).eq("experience_version_id", structure.version.id).eq("status", "active").maybeSingle(); let planId = existing.data?.id;
    if (!planId) { const created = await db.from("cohort_course_plans").insert({ cohort_id: offering.data.cohort_id, experience_id: experienceId, experience_version_id: structure.version.id, name: `${offering.data.name} Journey`, status: "active", settings: { hidden_lesson_ids: hiddenLessons }, created_by: admin.id }).select("id").single(); if (created.error) throw new Error(created.error.message); planId = created.data.id; }
    else { const updated = await db.from("cohort_course_plans").update({ settings: { hidden_lesson_ids: hiddenLessons } }).eq("id", planId); if (updated.error) throw new Error(updated.error.message); await db.from("cohort_course_plan_sections").delete().eq("plan_id", planId); await db.from("cohort_course_plan_modules").delete().eq("plan_id", planId); }
    for (const [order, module] of structure.modules.entries()) { const row = await db.from("cohort_course_plan_modules").insert({ plan_id: planId, experience_version_id: structure.version.id, source_module_id: module.id, sort_order: order, visibility: visibleModules.has(module.id) ? "visible" : "hidden" }).select("id").single(); if (row.error) throw new Error(row.error.message); const sections = module.lessons.flatMap((lesson) => lesson.sections); if (sections.length) { const result = await db.from("cohort_course_plan_sections").insert(sections.map((section, index) => ({ plan_id: planId!, plan_module_id: row.data.id, experience_version_id: structure.version.id, occurrence_type: "canonical", source_section_id: section.id, sort_order: index, visibility: visibleSections.has(section.id) ? "visible" : "hidden" }))); if (result.error) throw new Error(result.error.message); } }
  } else {
    let templateId = offering.data.default_delivery_plan_template_id;
    if (!templateId) { const created = await db.from("delivery_plan_templates").insert({ experience_id: experienceId, experience_version_id: structure.version.id, name: `${offering.data.name} Journey`, sharing_scope: "private", status: "active", settings: { hidden_lesson_ids: hiddenLessons }, created_by: admin.id }).select("id").single(); if (created.error) throw new Error(created.error.message); templateId = created.data.id; const attached = await db.from("experience_offerings").update({ default_delivery_plan_template_id: templateId }).eq("id", offeringId); if (attached.error) throw new Error(attached.error.message); }
    else { const updated = await db.from("delivery_plan_templates").update({ settings: { hidden_lesson_ids: hiddenLessons } }).eq("id", templateId); if (updated.error) throw new Error(updated.error.message); await db.from("delivery_plan_template_sections").delete().eq("template_id", templateId); await db.from("delivery_plan_template_modules").delete().eq("template_id", templateId); }
    for (const [order, module] of structure.modules.entries()) { const row = await db.from("delivery_plan_template_modules").insert({ template_id: templateId, experience_version_id: structure.version.id, source_module_id: module.id, sort_order: order, visibility: visibleModules.has(module.id) ? "visible" : "hidden" }).select("id").single(); if (row.error) throw new Error(row.error.message); const sections = module.lessons.flatMap((lesson) => lesson.sections); if (sections.length) { const result = await db.from("delivery_plan_template_sections").insert(sections.map((section, index) => ({ template_id: templateId!, template_module_id: row.data.id, experience_version_id: structure.version.id, source_section_id: section.id, sort_order: index, visibility: visibleSections.has(section.id) ? "visible" : "hidden" }))); if (result.error) throw new Error(result.error.message); } }
  }
  await audit(admin, "course.journey_visibility.updated", "experience_offering", offeringId, { experienceId }); revalidatePath(`/admin/trainings/${experienceId}/delivery`); redirect(`/admin/trainings/${experienceId}/delivery?saved=1`);
}
