import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminPageHeader, AdminShell } from "@/components/admin/AdminShell";
import { requireAdmin } from "@/lib/admin/auth";
import { getExperienceStructure } from "@/lib/experiences/builder/data";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import { saveJourneyVisibilityAction } from "./actions";

function hidden(settings: unknown) { if (!settings || typeof settings !== "object" || Array.isArray(settings)) return new Set<string>(); const ids = (settings as Record<string, unknown>).hidden_lesson_ids; return new Set(Array.isArray(ids) ? ids.filter((id): id is string => typeof id === "string") : []); }

export default async function Page({ params, searchParams }: { params: Promise<{ experienceId: string }>; searchParams: Promise<{ saved?: string }> }) {
  const admin = await requireAdmin(); const { experienceId } = await params; const notice = await searchParams; const db = createAdminSupabaseClient();
  const [experience, offeringResult] = await Promise.all([db.from("experiences").select("id,name").eq("id", experienceId).maybeSingle(), db.from("experience_offerings").select("*").eq("experience_id", experienceId).order("name")]); if (!experience.data || offeringResult.error) notFound();
  const offerings = await Promise.all((offeringResult.data ?? []).filter((item) => item.experience_version_id).map(async (offering) => {
    const structure = await getExperienceStructure(experienceId, offering.experience_version_id!, db); let settings: unknown = null; let moduleRows: Array<{ source_module_id: string; visibility: string }> = []; let sectionRows: Array<{ source_section_id: string | null; visibility: string }> = [];
    if (offering.cohort_id) { const plan = await db.from("cohort_course_plans").select("id,settings").eq("cohort_id", offering.cohort_id).eq("experience_version_id", offering.experience_version_id!).eq("status", "active").maybeSingle(); settings = plan.data?.settings; if (plan.data) { const [modules, sections] = await Promise.all([db.from("cohort_course_plan_modules").select("source_module_id,visibility").eq("plan_id", plan.data.id), db.from("cohort_course_plan_sections").select("source_section_id,visibility").eq("plan_id", plan.data.id)]); moduleRows = modules.data ?? []; sectionRows = sections.data ?? []; } }
    else if (offering.default_delivery_plan_template_id) { const [template, modules, sections] = await Promise.all([db.from("delivery_plan_templates").select("settings").eq("id", offering.default_delivery_plan_template_id).maybeSingle(), db.from("delivery_plan_template_modules").select("source_module_id,visibility").eq("template_id", offering.default_delivery_plan_template_id), db.from("delivery_plan_template_sections").select("source_section_id,visibility").eq("template_id", offering.default_delivery_plan_template_id)]); settings = template.data?.settings; moduleRows = modules.data ?? []; sectionRows = sections.data ?? []; }
    return { offering, structure, hiddenLessons: hidden(settings), modules: new Map(moduleRows.map((row) => [row.source_module_id, row.visibility])), sections: new Map(sectionRows.filter((row) => row.source_section_id).map((row) => [row.source_section_id!, row.visibility])) };
  }));
  return <AdminShell admin={admin}><AdminPageHeader eyebrow="Delivery" title={`${experience.data.name} Journeys`} description="Choose what each cohort or offering experiences without changing the master Course." action={<Link className="admin-secondary-link" href={`/admin/trainings/${experienceId}`}>Back to Course</Link>}/>{notice.saved && <p className="admin-form-message is-success">Journey visibility saved.</p>}<div className="delivery-visibility-list">{offerings.map(({ offering, structure, hiddenLessons, modules, sections }) => <section className="admin-panel delivery-visibility-card" key={offering.id}><header><div><p className="admin-kicker">{offering.cohort_id ? "Cohort Journey" : "Offering Journey"}</p><h2>{offering.name}</h2></div></header><form action={saveJourneyVisibilityAction.bind(null, experienceId, offering.id)}>{structure.modules.map((module) => <fieldset key={module.id}><legend><label><input type="checkbox" name="visible_module" value={module.id} defaultChecked={modules.get(module.id) !== "hidden"}/> {module.title}</label></legend>{module.lessons.map((lesson) => <div className="delivery-visibility-lesson" key={lesson.id}><label><input type="checkbox" name="visible_lesson" value={lesson.id} defaultChecked={!hiddenLessons.has(lesson.id)}/> {lesson.title}</label>{lesson.sections.map((section) => <label key={section.id}><input type="checkbox" name="visible_section" value={section.id} defaultChecked={sections.get(section.id) !== "hidden"}/> {section.title}</label>)}</div>)}</fieldset>)}<button className="admin-primary">Save Journey Visibility</button></form></section>)}{offerings.length === 0 && <p>No version-pinned offerings are ready for Journey configuration.</p>}</div></AdminShell>;
}
