import { addCompanionModuleAction, companionModuleCommandAction, updateCompanionModeAction, updateCompanionModuleAction } from "@/app/admin/trainings/[experienceId]/versions/[versionId]/companion-actions";
import { COMPANION_LIBRARY, COMPANION_TYPES, companionLines, companionText, companionType, type CompanionModuleRecord } from "@/lib/experiences/builder/companion";
import { groupLabel, type CourseConfiguration } from "@/lib/experiences/builder/course-configuration";
import type { BuilderCourseStructure } from "@/lib/experiences/builder/types";
import type { Tables } from "@/lib/supabase/database.types";

type Resource = Tables<"resources">;
type Props = { structure: BuilderCourseStructure; selectedId?: string; configuration: CourseConfiguration; modules: CompanionModuleRecord[]; resources: Resource[]; resourceLinks: Array<{ companion_module_id: string; resource_id: string }>; editable: boolean };

function TypeFields({ module }: { module: CompanionModuleRecord }) {
  const type = companionType(module.module_type); if (!type) return null;
  const config = module.configuration;
  const textAreaTypes = new Set(["reflection_prompt", "custom_text", "announcements", "group_discussion_prompt", "group_notes", "prayer", "chat"]);
  return <>
    {textAreaTypes.has(type) && <label>Content / prompt<textarea name="content" rows={4} defaultValue={companionText(config, "content")} placeholder={type === "chat" ? "Optional description for the future chat space" : "What should participants see?"}/></label>}
    {(type === "action_steps") && <label>Action steps <small>One per line</small><textarea name="items" rows={5} defaultValue={companionLines(config).join("\n")}/></label>}
    {(type === "video_call") && <><label>Provider<select name="provider" defaultValue={companionText(config, "provider") || "google_meet"}><option value="google_meet">Google Meet</option><option value="zoom">Zoom</option><option value="microsoft_teams">Microsoft Teams</option><option value="other">Other</option></select></label><label>Meeting URL<input type="url" name="url" defaultValue={companionText(config, "url")}/></label><label>Instructions<textarea name="instructions" rows={3} defaultValue={companionText(config, "instructions")}/></label><label>Recurring day/time<input name="recurring_time" defaultValue={companionText(config, "recurring_time")} placeholder="Thursdays at 6:30 PM"/></label><label>Button label<input name="button_label" defaultValue={companionText(config, "button_label") || "Join Call"}/></label><label>Who can start?<select name="who_can_start" defaultValue={companionText(config, "who_can_start") || "leaders_admin"}><option value="leaders_admin">Leaders / Admin</option><option value="any_group_member">Any Group Member</option></select></label></>}
    {type === "chat" && <label><input type="checkbox" name="allow_participant_posting" value="true" defaultChecked={companionText(config, "allow_participant_posting") !== "false"}/> Allow participant posting</label>}
    {type === "next_gathering" && <><label>Date<input type="date" name="date" defaultValue={companionText(config, "date")}/></label><label>Time<input type="time" name="time" defaultValue={companionText(config, "time")}/></label><label>Location<input name="location" defaultValue={companionText(config, "location")}/></label><label>Note<textarea name="note" rows={3} defaultValue={companionText(config, "note")}/></label><label>Optional link<input type="url" name="action_url" defaultValue={companionText(config, "action_url")}/></label><label>Link label<input name="action_label" defaultValue={companionText(config, "action_label") || "View details"}/></label></>}
    {type === "facilitator" && <><label>Name<input name="name" defaultValue={companionText(config, "name")}/></label><label>Role<input name="role" defaultValue={companionText(config, "role")}/></label><label>Short note<textarea name="note" rows={3} defaultValue={companionText(config, "note")}/></label></>}
    {type === "custom_link" && <><label>URL<input type="url" name="url" defaultValue={companionText(config, "url")}/></label><label>Button label<input name="button_label" defaultValue={companionText(config, "button_label") || "Open link"}/></label><label>Short description<textarea name="content" rows={3} defaultValue={companionText(config, "content")}/></label></>}
  </>;
}

export function CompanionBuilder({ structure, selectedId, configuration, modules, resources, resourceLinks, editable }: Props) {
  const week = groupLabel(configuration.terminology.group_label);
  const mode = configuration.companion_mode;
  return <aside className="companion-builder" aria-label="Companion Builder"><header><span>Enhanced Course</span><h2>Companion</h2><p>A quieter supporting space beside the lesson.</p></header>
    <form className="companion-mode-form" action={updateCompanionModeAction.bind(null, structure.experience.id, structure.version.id, selectedId)}><fieldset disabled={!editable}><legend>Companion mode</legend><label><input type="radio" name="companion_mode" value="individual" defaultChecked={mode === "individual"}/> Individual</label><label><input type="radio" name="companion_mode" value="group" defaultChecked={mode === "group"}/> Group</label></fieldset>{editable && <button>Save mode</button>}</form>
    {mode === "group" && <Link className="companion-manage-group" href={`/admin/trainings/${structure.experience.id}/delivery`}>Manage Groups &amp; Members →</Link>}
    <div className="companion-builder-list">{modules.map((module, index) => {
      const type = companionType(module.module_type); if (!type) return null; const definition = COMPANION_LIBRARY[type];
      const linked = new Set(resourceLinks.filter((link) => link.companion_module_id === module.id).map((link) => link.resource_id));
      return <article className={`companion-builder-card${module.visibility === "hidden" ? " is-hidden" : ""}`} key={module.id}><div className="companion-builder-card-head"><div><small>{definition.label} · {module.audience}</small><strong>{module.display_title}</strong>{definition.future && <em>Framework shell</em>}</div>{editable && <div className="companion-card-actions"><form action={companionModuleCommandAction.bind(null, structure.experience.id, structure.version.id, module.id, selectedId, "up")}><button disabled={index === 0} aria-label={`Move ${module.display_title} up`}>↑</button></form><form action={companionModuleCommandAction.bind(null, structure.experience.id, structure.version.id, module.id, selectedId, "down")}><button disabled={index === modules.length - 1} aria-label={`Move ${module.display_title} down`}>↓</button></form><form action={companionModuleCommandAction.bind(null, structure.experience.id, structure.version.id, module.id, selectedId, "toggle")}><button>{module.visibility === "hidden" ? "Show" : "Hide"}</button></form></div>}</div>
        <details><summary>Edit module</summary><form className="companion-module-form" action={updateCompanionModuleAction.bind(null, structure.experience.id, structure.version.id, module.id, selectedId)}><fieldset disabled={!editable}><label>Display title<input name="display_title" defaultValue={module.display_title} required maxLength={200}/></label><label>Where should this appear?<select name="scope" defaultValue={module.scope}><option value="course">Entire Course</option><option value="module">This {week}</option><option value="lesson">This Lesson</option><option value="page">This Page</option></select></label><label>Target {week}<select name="target_module_id" defaultValue={module.target_module_id ?? ""}><option value="">Choose {week}</option>{structure.modules.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label>Target Lesson<select name="target_lesson_id" defaultValue={module.target_lesson_id ?? ""}><option value="">Choose Lesson</option>{structure.modules.map((group) => <optgroup label={group.title} key={group.id}>{group.lessons.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</optgroup>)}</select></label><label>Target Page<select name="target_section_id" defaultValue={module.target_section_id ?? ""}><option value="">Choose Page</option>{structure.modules.flatMap((group) => group.lessons.map((lesson) => <optgroup label={`${group.title} · ${lesson.title}`} key={lesson.id}>{lesson.sections.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</optgroup>))}</select></label><label>Who is this for?<select name="audience" defaultValue={module.audience}>{definition.audiences.map((audience) => <option value={audience} key={audience}>{audience === "leaders" ? "Leaders / Admin" : audience[0].toUpperCase() + audience.slice(1)}</option>)}</select></label><TypeFields module={module}/>{(type === "resources" || type === "shared_resources") && <fieldset className="companion-resource-choices"><legend>Resources</legend>{resources.map((resource) => <label key={resource.id}><input type="checkbox" name="resource_id" value={resource.id} defaultChecked={linked.has(resource.id)}/> {resource.title}</label>)}{!resources.length && <small>No active Resources are available.</small>}</fieldset>}</fieldset>{editable && <button className="companion-save">Save module</button>}</form>{editable && <form className="companion-remove" action={companionModuleCommandAction.bind(null, structure.experience.id, structure.version.id, module.id, selectedId, "remove")}><button>Remove module</button></form>}</details>
      </article>;
    })}{!modules.length && <p className="companion-builder-empty">Add the first supporting module for this Course.</p>}</div>
    {editable && <details className="companion-add"><summary>+ Add Module</summary><form action={addCompanionModuleAction.bind(null, structure.experience.id, structure.version.id, selectedId)}><label>Module type<select name="module_type" required defaultValue=""><option value="" disabled>Choose a module</option>{COMPANION_TYPES.filter((type) => mode === "group" || COMPANION_LIBRARY[type].defaultAudience !== "group").map((type) => <option value={type} key={type}>{COMPANION_LIBRARY[type].label}</option>)}</select></label><button>Add Module</button></form></details>}
  </aside>;
}
import Link from "next/link";
