import Link from "next/link";
import { BuilderColumnBlocks } from "@/components/admin/BuilderBlocks";
import type { BuilderCourseStructure, BuilderSection } from "@/lib/experiences/builder/types";
import { getSectionLayoutWorkspace } from "@/lib/experiences/admin/layout-data";
import { createCourseLessonAction, createModuleAction, createSectionAction, updateSectionAction } from "@/app/admin/trainings/[experienceId]/versions/[versionId]/actions";
import { publishVersionAction } from "@/app/admin/trainings/[experienceId]/versions/[versionId]/release-actions";
import { updateCourseLayoutAction } from "@/app/admin/trainings/[experienceId]/edit-actions";

function Outline({ structure, selectedId, editable }: { structure: BuilderCourseStructure; selectedId?: string; editable: boolean }) {
  const base = `/admin/trainings/${structure.experience.id}/versions/${structure.version.id}`;
  return <aside className="course-builder-outline"><div className="course-builder-identity"><span>Course outline</span><strong>{structure.experience.name}</strong><small>{structure.modules.length} Week{structure.modules.length === 1 ? "" : "s"}</small></div>
    <nav aria-label="Builder curriculum">{structure.modules.map((module, moduleIndex) => {
      const activeModule = module.lessons.some((lesson) => lesson.sections.some((section) => section.id === selectedId));
      return <details key={module.id} open={activeModule || !selectedId && moduleIndex === 0}><summary>{module.title}</summary><div>{module.lessons.map((lesson) => {
        const single = lesson.sections.length === 1;
        return <div className="course-builder-lesson" key={lesson.id}>{single ? <Link aria-current={lesson.sections[0].id === selectedId ? "page" : undefined} href={`${base}?section=${lesson.sections[0].id}`}>{lesson.title}</Link> : <><strong>{lesson.title}</strong>{lesson.sections.map((section) => <Link key={section.id} aria-current={section.id === selectedId ? "page" : undefined} href={`${base}?section=${section.id}`}>{section.title}</Link>)}</>}{editable && lesson.sections.length === 0 && <details className="course-builder-add"><summary>+ Add Content Page</summary><form action={createSectionAction.bind(null, structure.experience.id, structure.version.id, lesson.id)}><label>Page title<input name="title" defaultValue={lesson.title} required maxLength={200}/></label><input type="hidden" name="requirement_level" value="required"/><input type="hidden" name="completion_rule" value="all_required_blocks"/><input type="hidden" name="renderer_mode" value="builder"/><button type="submit">Create Content Page</button></form></details>}{editable && lesson.sections.length > 1 && <details className="course-builder-add"><summary>+ Add Page</summary><form action={createSectionAction.bind(null, structure.experience.id, structure.version.id, lesson.id)}><label>Page title<input name="title" required maxLength={200}/></label><input type="hidden" name="requirement_level" value="required"/><input type="hidden" name="completion_rule" value="all_required_blocks"/><input type="hidden" name="renderer_mode" value="builder"/><button type="submit">Create Page</button></form></details>}</div>;
      })}{editable && <details className="course-builder-add"><summary>+ Add Lesson</summary><form action={createCourseLessonAction.bind(null, structure.experience.id, structure.version.id, module.id)}><label>Lesson title<input name="title" required maxLength={200}/></label><input type="hidden" name="requirement_level" value="required"/><input type="hidden" name="completion_rule" value="view"/><button type="submit">Create Lesson</button></form></details>}</div></details>;
    })}</nav>{editable && <details className="course-builder-add is-week"><summary>+ Add Week</summary><form action={createModuleAction.bind(null, structure.experience.id, structure.version.id)}><label>Week title<input name="title" required maxLength={200}/></label><input type="hidden" name="requirement_level" value="required"/><button type="submit">Create Week</button></form></details>}</aside>;
}

function LessonHeader({ structure, section, editable }: { structure: BuilderCourseStructure; section: BuilderSection; editable: boolean }) {
  const lesson = structure.modules.flatMap((module) => module.lessons).find((item) => item.id === section.lesson_id);
  const week = structure.modules.find((item) => item.id === section.module_id);
  return <header className="course-builder-lesson-header"><p>{week?.title ?? "Course"} / {lesson?.title ?? "Lesson"}</p><span>Lesson content</span><h2>{section.title}</h2>{section.description && <div>{section.description}</div>}{editable && <details className="course-builder-details"><summary>Edit lesson introduction</summary><form action={updateSectionAction.bind(null, structure.experience.id, structure.version.id, section.id)}><label>Title<input name="title" defaultValue={section.title} required maxLength={200}/></label><label>Introduction<textarea name="description" defaultValue={section.description ?? ""} maxLength={3000} rows={3}/></label><input type="hidden" name="requirement_level" value={section.requirement_level}/><input type="hidden" name="completion_rule" value={section.completion_rule}/><input type="hidden" name="section_key" value={section.section_key}/><input type="hidden" name="renderer_mode" value={section.renderer_mode}/><input type="hidden" name="custom_renderer_key" value={section.custom_renderer_key ?? ""}/><button type="submit">Save introduction</button></form></details>}</header>;
}

export async function CourseBuilderWorkspace({ structure, selectedId, error, saved }: { structure: BuilderCourseStructure; selectedId?: string; error?: string; saved?: string }) {
  const sections = structure.modules.flatMap((module) => module.lessons.flatMap((lesson) => lesson.sections));
  const selected = sections.find((section) => section.id === selectedId) ?? sections[0];
  const editable = structure.version.status === "draft";
  const base = `/admin/trainings/${structure.experience.id}/versions/${structure.version.id}`;
  const workspace = selected ? await getSectionLayoutWorkspace(structure.experience.id, structure.version.id, selected.id) : null;
  return <div className="course-builder-workspace"><header className="course-builder-topbar"><div><Link href={`/admin/trainings/${structure.experience.id}`}>← Courses</Link><span>{editable ? "Unpublished changes" : "Live · read only"}</span><h1>{structure.experience.name}</h1></div><div className="course-builder-top-actions"><Link href={`${base}/preview`}>Preview</Link>{editable && <details><summary>Publish</summary><p>Publishing makes this Draft live. Further changes require a new Draft.</p><form action={publishVersionAction.bind(null, structure.experience.id, structure.version.id)}><label><input type="checkbox" name="confirm_publish" value="yes" required/> Confirm publication</label><button type="submit">Publish course</button></form></details>}<details className="course-builder-settings"><summary>Settings</summary><form action={updateCourseLayoutAction.bind(null, structure.experience.id, structure.version.id)}><fieldset disabled={!editable}><legend>Course layout</legend><label><input type="radio" name="course_layout" value="standard" defaultChecked={structure.version.shell_mode !== "enhanced"}/> Standard</label><label><input type="radio" name="course_layout" value="enhanced" defaultChecked={structure.version.shell_mode === "enhanced"}/> Enhanced</label></fieldset>{editable && <button type="submit">Save layout</button>}</form><Link href={`/admin/trainings/${structure.experience.id}#versions`}>Version history and advanced settings</Link></details></div></header>
    {error && <p className="course-builder-notice is-error" role="alert">{error}</p>}{saved && <p className="course-builder-notice" role="status">{saved}</p>}
    <div className="course-builder-grid"><Outline structure={structure} selectedId={selected?.id} editable={editable}/><main className="course-builder-canvas">{selected && workspace ? <><LessonHeader structure={structure} section={selected} editable={editable}/>{workspace.columns.length ? workspace.columns.map((column) => <BuilderColumnBlocks key={column.id} column={column} columns={workspace.columns} blocks={workspace.blocks} route={{ experienceId: structure.experience.id, versionId: structure.version.id, sectionId: selected.id }} editable={editable}/>) : <div className="course-builder-empty"><p>This legacy Page has no Content target.</p><Link href={`${base}/sections/${selected.id}/layout?advanced=1`}>Open advanced repair</Link></div>}</> : <div className="course-builder-empty"><h2>Begin your course</h2><p>Add a Week, then a Lesson and Content Page. Your course will appear here as you build it.</p></div>}</main></div>
  </div>;
}
