import Image from "next/image";
import Link from "next/link";
import { applyCourseThemeAction, saveCourseThemeAction, setCourseCardImageAction, setCourseCoverAction, setCourseHeaderLogoAction, setCourseLogoAction, updateCourseCardAction, updateCourseConfigurationAction, updateCourseLayoutAction } from "@/app/admin/trainings/[experienceId]/edit-actions";
import { CoursePaletteEditor } from "@/components/admin/CoursePaletteEditor";
import { GROUP_LABELS, groupLabel, type CourseConfiguration } from "@/lib/experiences/builder/course-configuration";
import type { CourseAsset, ResolvedAsset } from "@/lib/experiences/builder/resource-assets";

type Theme = { id: string; name: string; revision: number };
type Palette = Record<"primaryAccent" | "secondaryAccent" | "background" | "surface" | "text" | "mutedText" | "borderColor" | "completion", string>;
type ImageAction = (form: FormData) => void | Promise<void>;

function CardHeading({ icon, title, children }: { icon: string; title: string; children: string }) {
  return <header className="course-customization-card-heading"><span aria-hidden="true">{icon}</span><div><h2>{title}</h2><p>{children}</p></div></header>;
}

function ImageCard({ kind, action, images, current, editable, mode, courseLogoAvailable = false }: { kind: "logo" | "cover" | "header_logo" | "card"; action: ImageAction; images: CourseAsset[]; current?: ResolvedAsset; editable: boolean; mode?: CourseConfiguration["appearance"]["header_logo_mode"]; courseLogoAvailable?: boolean }) {
  const title = kind === "logo" ? "Course Logo" : kind === "cover" ? "Course Cover" : kind === "card" ? "Course Card Image" : "Header Brand Logo";
  const description = kind === "logo" ? "Add a logo that identifies this Course." : kind === "cover" ? "Add a wide welcome image for the learner experience." : kind === "card" ? "Choose the landscape image participants see in Course lists." : "Replace the PurposeOS label with the Course Logo or a different image.";
  return <section className={`course-customization-card course-customization-image is-${kind}`}>
    <CardHeading icon="▧" title={title}>{description}</CardHeading>
    <div className="course-image-workspace">
      <div className="course-image-preview">{current ? <Image src={current.url} alt={`Current ${title}`} width={kind === "logo" ? 420 : 960} height={kind === "logo" ? 180 : 400} unoptimized/> : <div><span aria-hidden="true">◇</span><strong>No {kind} selected</strong><small>{kind === "logo" ? "A transparent PNG or SVG works best" : "A wide 16:9 image works best"}</small></div>}</div>
      <div className="course-image-actions">
        {kind === "header_logo" && <form action={action}><input type="hidden" name="asset_operation" value="use_course_logo"/><button type="submit" disabled={!editable || !courseLogoAvailable}>{mode === "course_logo" ? "Using Course Logo" : "Use Course Logo"}</button>{!courseLogoAvailable && <small>Add a Course Logo first to reuse it here.</small>}</form>}
        <form action={action}><input type="hidden" name="asset_operation" value="select"/><label>Select from library<select name="resource_id" required defaultValue=""><option value="" disabled>Select an image</option>{images.map((image) => <option value={image.id} key={image.id}>{image.title} · {image.original_filename}</option>)}</select></label><button type="submit" disabled={!editable}>{current ? "Replace from Library" : "Use Selected Image"}</button></form>
        <form action={action}><input type="hidden" name="asset_operation" value="upload"/><label className="course-file-button">Upload Image<input type="file" name="file" accept="image/jpeg,image/png,image/webp,image/gif" required disabled={!editable}/></label><label>Library title <small>(optional)</small><input name="asset_title" maxLength={200} placeholder="Name this asset" disabled={!editable}/></label><button type="submit" disabled={!editable}>{current ? "Upload Replacement" : "Upload Image"}</button></form>
        <small className="course-image-guidance">PNG, JPG, WebP, or GIF · maximum 25 MB</small>
        {(current || kind === "header_logo" && mode !== "purposeos") && <form className="course-image-remove" action={action}><input type="hidden" name="asset_operation" value="remove"/><button type="submit" disabled={!editable}>{kind === "header_logo" ? "Restore PurposeOS Label" : `Remove ${title}`}</button></form>}
      </div>
    </div>
  </section>;
}

export function CourseCardEditor({ textAction, imageAction, configuration, images, current, editable }: { textAction: ImageAction; imageAction: ImageAction; configuration: CourseConfiguration; images: CourseAsset[]; current?: ResolvedAsset; editable: boolean }) {
  return <section className="course-customization-card course-card-editor">
    <CardHeading icon="▤" title="Participant Course Card">Customize the complete card participants see in Course lists.</CardHeading>
    <div className="course-card-editor-layout">
      <div className="course-card-editor-image">
        <div className="course-image-preview">{current ? <Image src={current.url} alt="Current Course Card image" width={960} height={540} unoptimized/> : <div><span aria-hidden="true">◇</span><strong>No card image selected</strong><small>The Course Cover is used as the fallback</small></div>}</div>
        <div className="course-image-actions">
          <form action={imageAction}><input type="hidden" name="asset_operation" value="select"/><label>Select from library<select name="resource_id" required defaultValue=""><option value="" disabled>Select an image</option>{images.map((image) => <option value={image.id} key={image.id}>{image.title} · {image.original_filename}</option>)}</select></label><button type="submit" disabled={!editable}>{current ? "Replace from Library" : "Use Selected Image"}</button></form>
          <form action={imageAction}><input type="hidden" name="asset_operation" value="upload"/><label className="course-file-button">Upload Image<input type="file" name="file" accept="image/jpeg,image/png,image/webp,image/gif" required disabled={!editable}/></label><label>Library title <small>(optional)</small><input name="asset_title" maxLength={200} placeholder="Name this asset" disabled={!editable}/></label><button type="submit" disabled={!editable}>{current ? "Upload Replacement" : "Upload Image"}</button></form>
          <small className="course-image-guidance">Landscape images work best · maximum 25 MB</small>
          {current && <form className="course-image-remove" action={imageAction}><input type="hidden" name="asset_operation" value="remove"/><button type="submit" disabled={!editable}>Remove Card Image</button></form>}
        </div>
      </div>
      <form className="course-card-editor-copy" action={textAction}><fieldset disabled={!editable}><label>Eyebrow<small>Optional. Defaults to the Course type.</small><input name="card_eyebrow" maxLength={80} defaultValue={configuration.card.eyebrow ?? ""} placeholder="Guided Course"/></label><label>Headline<small>Optional. Defaults to the Course title.</small><input name="card_headline" maxLength={200} defaultValue={configuration.card.headline ?? ""} placeholder="Course title"/></label><label>Supporting text<small>Optional. Defaults to the Course description.</small><textarea name="card_supporting_text" maxLength={600} rows={5} defaultValue={configuration.card.supporting_text ?? ""} placeholder="A short invitation or description"/></label></fieldset>{editable && <button type="submit">Save Course Card Text</button>}</form>
    </div>
  </section>;
}

export function CourseCustomizationWorkspace({ experienceId, versionId, shellMode, configuration, palette, images, currentLogo, currentCover, currentHeaderLogo, currentCardImage, themes, themeId, editable }: { experienceId: string; versionId: string; shellMode: string; configuration: CourseConfiguration; palette: Palette; images: CourseAsset[]; currentLogo?: ResolvedAsset; currentCover?: ResolvedAsset; currentHeaderLogo?: ResolvedAsset; currentCardImage?: ResolvedAsset; themes: Theme[]; themeId: string | null; editable: boolean }) {
  const appearanceAction = updateCourseConfigurationAction.bind(null, experienceId, versionId);
  return <details className="course-customization"><summary><span><strong>Course Customization</strong><small>Shell, appearance, branding, colors, and reusable Themes</small></span><b><span className="when-closed">Open Customization</span><span className="when-open">Close Customization</span> <i aria-hidden="true">⌄</i></b></summary><div className="course-customization-body">
    <header className="course-customization-heading"><div><span>Appearance</span><h2 id="course-customization-title">Course Customization</h2><p>Shape the shell, branding, and visual system for this Draft. Preview before publishing changes.</p></div><Link href={`/admin/trainings/${experienceId}/versions/${versionId}/preview`}>Preview Course ↗</Link></header>
    <div className="course-customization-grid">
      <section className="course-customization-card course-shell-card"><CardHeading icon="▥" title="Course Shell">Choose how content and navigation are arranged.</CardHeading><form action={updateCourseLayoutAction.bind(null, experienceId, versionId)}><fieldset disabled={!editable}><legend className="sr-only">Course shell</legend><div className="course-shell-options"><label className={shellMode !== "enhanced" ? "is-selected" : ""}><input type="radio" name="course_layout" value="standard" defaultChecked={shellMode !== "enhanced"}/><span className="course-shell-mini is-standard"><i/><b/></span><strong>Standard</strong><small>Clean and focused for straightforward training experiences.</small></label><label className={shellMode === "enhanced" ? "is-selected" : ""}><input type="radio" name="course_layout" value="enhanced" defaultChecked={shellMode === "enhanced"}/><span className="course-shell-mini is-enhanced"><i/><b/><em/></span><strong>Enhanced</strong><small>Adds the Companion for personal or group-based learning.</small></label></div></fieldset>{editable && <button type="submit">Save Course Shell</button>}</form></section>
      <section className="course-customization-card course-appearance-card"><CardHeading icon="◉" title="Course Appearance">Fine-tune structure and presentation.</CardHeading><form action={appearanceAction}><fieldset disabled={!editable}><legend className="sr-only">Course appearance</legend><label>Curriculum Group Terminology<small>Used throughout the Navigator and builder.</small><select name="group_label" defaultValue={configuration.terminology.group_label}>{GROUP_LABELS.map((value) => <option value={value} key={value}>{groupLabel(value)}</option>)}</select></label><label>Header Style<select name="header_treatment" defaultValue={configuration.appearance.header_treatment}><option value="minimal">Minimal</option><option value="image">Image · uses Course Cover or Theme cover</option><option value="color">Color</option></select></label><label>Reading Width<select name="reading_width" defaultValue={configuration.appearance.reading_width}><option value="focused">Focused</option><option value="standard">Standard</option><option value="wide">Wide</option></select></label><label>Accent Override<small>Optional; otherwise the current Theme controls accents.</small><input name="accent_color" type="text" pattern="#[0-9a-fA-F]{6}" placeholder="Theme / Course default" defaultValue={configuration.appearance.accent_color ?? ""}/></label></fieldset>{editable && <button type="submit">Save Appearance</button>}</form></section>
      <CourseCardEditor textAction={updateCourseCardAction.bind(null, experienceId, versionId)} imageAction={setCourseCardImageAction.bind(null, experienceId, versionId)} configuration={configuration} images={images} current={currentCardImage} editable={editable}/>
      <section className="course-customization-card course-themes-card"><CardHeading icon="◇" title="Reusable Themes">Apply a saved Theme or preserve this Draft’s colors for reuse.</CardHeading><form action={applyCourseThemeAction.bind(null, experienceId, versionId)}><label>Current Theme<select name="theme_id" required defaultValue={themeId ?? ""}><option value="" disabled>Choose a saved Theme</option>{themes.map((theme) => <option key={theme.id} value={theme.id}>{theme.name} · R{theme.revision}</option>)}</select></label><button type="submit" disabled={!editable}>Apply Saved Theme</button></form><div className="course-theme-separator"><span>Save current Draft as a Theme</span></div><form action={saveCourseThemeAction.bind(null, experienceId, versionId)}><label>Theme Name<input name="theme_name" required maxLength={120} placeholder="Wayfinder Blue Theme"/></label><button type="submit" disabled={!editable}>Save Current as Theme</button></form><p>Editing Draft colors does not automatically create or update a reusable Theme.</p></section>
      <ImageCard kind="logo" action={setCourseLogoAction.bind(null, experienceId, versionId)} images={images} current={currentLogo} editable={editable}/>
      <ImageCard kind="cover" action={setCourseCoverAction.bind(null, experienceId, versionId)} images={images} current={currentCover} editable={editable}/>
      <ImageCard kind="header_logo" action={setCourseHeaderLogoAction.bind(null, experienceId, versionId)} images={images} current={currentHeaderLogo} editable={editable} mode={configuration.appearance.header_logo_mode} courseLogoAvailable={Boolean(currentLogo)}/>
      <div className="course-color-card"><CoursePaletteEditor action={appearanceAction} initialPalette={palette} groupLabel={configuration.terminology.group_label} headerTreatment={configuration.appearance.header_treatment} readingWidth={configuration.appearance.reading_width} accentColor={configuration.appearance.accent_color ?? ""} editable={editable}/></div>
    </div>
  </div></details>;
}
