import type { ThemeConfiguration } from "@/lib/experiences/builder/types";

type Resource = { id: string; title: string; resource_type: string };

function AssetSelect({ name, label, value, resources }: { name: string; label: string; value?: string; resources: Resource[] }) {
  return <label>{label}<select name={name} defaultValue={value ?? ""}><option value="">None</option>{resources.map(resource => <option value={resource.id} key={resource.id}>{resource.title} · {resource.resource_type}</option>)}</select></label>;
}

export function ThemeFields({ configuration, resources }: { configuration: ThemeConfiguration; resources: Resource[] }) {
  const colors = configuration.colors ?? {};
  const colorFields = [["primaryAccent","Primary accent","#303735"],["secondaryAccent","Secondary accent","#6b7471"],["background","Page background","#f7f6f1"],["surface","Surface","#ffffff"],["elevatedSurface","Elevated surface","#ffffff"],["text","Primary text","#252a29"],["mutedText","Muted text","#69716e"],["borderColor","Border","#d7d5cc"]] as const;
  return <>
    <fieldset className="theme-fieldset"><legend>Brand resources</legend><AssetSelect name="logoResourceId" label="Logo" value={configuration.logoResourceId} resources={resources}/><AssetSelect name="coverImageResourceId" label="Cover image" value={configuration.coverImageResourceId} resources={resources}/><AssetSelect name="decorativeResourceId" label="Decorative asset" value={configuration.decorativeResourceIds?.[0]} resources={resources}/></fieldset>
    <fieldset className="theme-fieldset theme-color-fields"><legend>Colors</legend>{colorFields.map(([name,label,fallback]) => <label key={name}>{label}<input type="color" name={name} defaultValue={colors[name] ?? fallback} required/></label>)}</fieldset>
    <fieldset className="theme-fieldset"><legend>Treatments</legend><label>Typography<select name="typographyKey" defaultValue={configuration.typographyKey ?? "purpose_mixed"}><option value="purpose_sans">Purpose sans</option><option value="purpose_editorial">Purpose editorial</option><option value="purpose_mixed">Purpose mixed</option></select></label><label>Headings<select name="headingTreatment" defaultValue={configuration.headingTreatment ?? "standard"}><option value="standard">Standard</option><option value="uppercase">Uppercase</option><option value="editorial">Editorial</option></select></label><label>Buttons<select name="buttonVariant" defaultValue={configuration.buttonVariant ?? "solid"}><option value="solid">Solid</option><option value="outline">Outline</option><option value="underlined">Underlined</option></select></label><label>Cards<select name="cardTreatment" defaultValue={configuration.cardTreatment ?? "bordered"}><option value="bordered">Bordered</option><option value="flat">Flat</option><option value="elevated">Elevated</option></select></label><label>Navigation<select name="navigationTreatment" defaultValue={configuration.navigationTreatment ?? "neutral"}><option value="neutral">Neutral</option><option value="accent_line">Accent line</option><option value="dark">Dark</option></select></label><label>Spacing<select name="spacingPreset" defaultValue={configuration.spacingPreset ?? "comfortable"}><option value="compact">Compact</option><option value="comfortable">Comfortable</option><option value="generous">Generous</option></select></label><label>Corners<select name="cornerPreset" defaultValue={configuration.cornerPreset ?? "square"}><option value="square">Square</option><option value="subtle">Subtle</option><option value="rounded">Rounded</option></select></label></fieldset>
  </>;
}
