import { CIRCLE_AREAS, CIRCLE_GUIDANCE, CIRCLE_REFLECTIONS, circleCounts, type CircleData } from "@/lib/experiences/builder/circle-of-influence";

export function CircleOfInfluenceGuidance() {
  return <section className="circle-guidance"><div className="circle-guidance-lede"><p className="circle-kicker">Everyday relationships · Meaningful influence</p><h3>Recognize the people already around you</h3><p>Your circle of influence includes the people you share life with. This reflection helps you notice where you have influence and where God may be inviting you to invest more intentionally.</p></div><blockquote>“Truly, truly, I say to you, he who does not enter by the door into the fold of the sheep, but climbs up some other way, he is a thief and a robber.”<cite>John 10:1 · NASB</cite></blockquote><div className="circle-guidance-definitions"><article><h4>A sheep pen</h4><p>An open-air corral that protects sheep from predators and thieves.</p></article><article><h4>Folding the sheep</h4><p>Managing sheep with skill, care, and a special relationship between shepherd and sheep.</p></article></div><div className="circle-guidance-context"><h4>Know your community</h4>{CIRCLE_GUIDANCE.slice(0, 3).map(paragraph => <p key={paragraph}>{paragraph}</p>)}</div><div className="circle-guidance-steps"><h4>How to use this reflection</h4><ol><li><strong>Map your people.</strong> List up to 15 people in each applicable area. Aim for 4–15 where possible, and leave areas that do not apply blank. Use Other to name another community.</li><li><strong>Notice your influence.</strong> Reflect on whom you already have strong influence with and why.</li><li><strong>Listen for an invitation.</strong> Pray for the people on your list and notice whom God is stirring your heart toward.</li></ol><p>This is a relationship map, not a score. Someone may belong to more than one area.</p></div></section>;
}
export function CircleOfInfluenceResults({ data }: { data: CircleData }) {
  const counts = circleCounts(data);
  return <div className="circle-results"><div className="circle-summary"><strong>{counts.reduce((sum, area) => sum + area.count, 0)}</strong><span>connections across {counts.filter(area => area.count).length} {counts.filter(area => area.count).length === 1 ? "area" : "areas"}</span><p>This is a picture of your relationships, not a score. Someone may belong to more than one area.</p></div><div className="circle-result-grid">{CIRCLE_AREAS.map((area, index) => <section key={area.key}><header><span>{String(index + 1).padStart(2, "0")}</span><h3>{counts[index].title}</h3><small>{counts[index].count} {counts[index].count === 1 ? "person" : "people"}</small></header><p>{area.description}</p>{data.people[area.key].some(name => name.trim()) ? <ol>{data.people[area.key].filter(name => name.trim()).map((name, i) => <li key={i}>{name}</li>)}</ol> : <p className="circle-empty">No people added in this area.</p>}</section>)}</div><section className="circle-reflection-result"><h3>Your influence reflection</h3><dl>{CIRCLE_REFLECTIONS.map(({ key, label: question }) => [question, data[key]]).map(([question, answer]) => <div key={question}><dt>{question}</dt><dd>{answer.trim() || "Not answered"}</dd></div>)}</dl>{[data.prayer, data.disciple, data.nextStep].some(value => value.trim()) && <details className="circle-legacy-reflections"><summary>Earlier saved reflections</summary><dl>{[["How will you pray for the people on your list?", data.prayer], ["Who might God be inviting you to disciple?", data.disciple], ["What is your next step to listen, care, protect, or lead?", data.nextStep]].filter(([, answer]) => answer.trim()).map(([question, answer]) => <div key={question}><dt>{question}</dt><dd>{answer}</dd></div>)}</dl></details>}</section><CircleOfInfluenceGuidance/></div>;
}
