import { CIRCLE_AREAS, CIRCLE_GUIDANCE, circleCounts, type CircleData } from "@/lib/experiences/builder/circle-of-influence";

export function CircleOfInfluenceGuidance() {
  return <section className="circle-guidance"><h3>Who is your flock?</h3><p><em>“Truly, truly, I say to you, he who does not enter by the door into the fold of the sheep, but climbs up some other way, he is a thief and a robber.”</em> (John 10:1, NASB)</p><p><strong>A sheep pen:</strong> An open-air corral that protects sheep at night from predators and thieves.</p><p><strong>Folding the sheep:</strong> Managing the sheep with skill and a special relationship between shepherd and sheep.</p>{CIRCLE_GUIDANCE.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</section>;
}
export function CircleOfInfluenceResults({ data }: { data: CircleData }) {
  const counts = circleCounts(data);
  return <div className="circle-results"><div className="circle-summary"><strong>{counts.reduce((sum, area) => sum + area.count, 0)}</strong><span>connections across {counts.filter(area => area.count).length} {counts.filter(area => area.count).length === 1 ? "area" : "areas"}</span><p>This is a picture of your relationships, not a score. Someone may belong to more than one area.</p></div><div className="circle-result-grid">{CIRCLE_AREAS.map((area, index) => <section key={area.key}><header><span>{String(index + 1).padStart(2, "0")}</span><h3>{counts[index].title}</h3><small>{counts[index].count} {counts[index].count === 1 ? "person" : "people"}</small></header><p>{area.description}</p>{data.people[area.key].some(name => name.trim()) ? <ol>{data.people[area.key].filter(name => name.trim()).map((name, i) => <li key={i}>{name}</li>)}</ol> : <p className="circle-empty">No people added in this area.</p>}</section>)}</div><section className="circle-reflection-result"><h3>Pray, discern, and act</h3><dl>{[["How will you pray for the people on your list?", data.prayer], ["Who might God be inviting you to disciple?", data.disciple], ["What is your next step to listen, care, protect, or lead?", data.nextStep]].map(([question, answer]) => <div key={question}><dt>{question}</dt><dd>{answer.trim() || "Not answered"}</dd></div>)}</dl></section><CircleOfInfluenceGuidance/></div>;
}
