import { savePersonalCompanionEntryAction } from "@/lib/experiences/builder/companion-actions";
import { COMPANION_LIBRARY, companionLines, companionText, companionType, moduleApplies } from "@/lib/experiences/builder/companion";
import type { CompanionRuntimeData, ResolvedCompanionModule } from "@/lib/experiences/builder/companion-data";
import type { CourseSectionLocation } from "./CourseNavigator";
import { CompanionPolling, GroupChatExperience, VideoCallExperience } from "./LiveCompanionInteractions";

function ModuleBody({ module, companion, preview, route }: { module: ResolvedCompanionModule; companion: CompanionRuntimeData; preview: boolean; route: { slug: string; moduleKey: string; lessonKey: string; sectionKey: string } }) {
  const type = companionType(module.module_type); if (!type) return null;
  const config = module.effective_configuration;
  if (type === "personal_notes") {
    const entry = module.entry?.entry_data && typeof module.entry.entry_data === "object" && !Array.isArray(module.entry.entry_data) ? module.entry.entry_data as Record<string, unknown> : {};
    return preview ? <div className="companion-placeholder"><p>Private notebook</p><span>Participant notes are never loaded in Admin Preview.</span></div> : <form className="companion-notes" action={savePersonalCompanionEntryAction.bind(null, route.slug, route.moduleKey, route.lessonKey, route.sectionKey, module.id)}><label><span className="sr-only">Personal notes</span><textarea name="notes" rows={7} maxLength={30000} defaultValue={typeof entry.text === "string" ? entry.text : ""} placeholder="Write a private note…"/></label><button>Save notes</button><small>Private to you</small></form>;
  }
  if (type === "resources" || type === "shared_resources") return module.resources.length ? <ul className="companion-resources">{module.resources.map((resource) => <li key={resource.id}><a href={resource.downloadUrl} target="_blank" rel="noreferrer"><strong>{resource.title}</strong><span>{resource.description || resource.originalFilename || "Open resource"}</span></a></li>)}</ul> : <p className="companion-empty">Resources will appear here when they are added.</p>;
  if (type === "action_steps") return <ul className="companion-checklist">{companionLines(config).map((item) => <li key={item}><span aria-hidden="true">○</span>{item}</li>)}</ul>;
  if (type === "video_call") return preview ? <div className="companion-placeholder"><p>Video Call preview</p><span>Live delivery state is never loaded in Admin Preview.</span></div> : <VideoCallExperience module={module} route={route} canStart={companionText(config, "who_can_start") === "any_group_member" || companion.currentMemberRole === "facilitator"} canEnd={companion.currentMemberRole === "facilitator"}/>;
  if (type === "next_gathering") { const url = companionText(config, "action_url"); return <div className="companion-detail">{companionText(config, "date") && <strong>{companionText(config, "date")} {companionText(config, "time")}</strong>}<span>{companionText(config, "location")}</span><p>{companionText(config, "note")}</p>{url && <a href={url} target="_blank" rel="noreferrer">{companionText(config, "action_label") || "View details"}</a>}</div>; }
  if (type === "facilitator") return <div className="companion-person"><span aria-hidden="true">{(companionText(config, "name") || "Guide")[0]}</span><div><strong>{companionText(config, "name") || "Your guide"}</strong><small>{companionText(config, "role")}</small><p>{companionText(config, "note")}</p></div></div>;
  if (type === "group_members") return companion.groupMembers.length ? <ul className="companion-members">{companion.groupMembers.map((member) => <li key={member.id}><span aria-hidden="true">{member.name[0]}</span><div><strong>{member.name}</strong><small>{member.role}</small></div></li>)}</ul> : <p className="companion-empty">Group members will appear when this Course is opened through a cohort delivery.</p>;
  if (type === "custom_link") { const url = companionText(config, "url"); return <div className="companion-detail"><p>{companionText(config, "content")}</p>{url && <a className="companion-action" href={url} target="_blank" rel="noreferrer">{companionText(config, "button_label") || "Open link"}</a>}</div>; }
  if (type === "chat") return preview ? <div className="companion-placeholder"><p>Group Chat preview</p><span>Private delivery messages are never loaded in Admin Preview.</span></div> : <GroupChatExperience module={module} route={route} messages={module.chat_messages}/>;
  if (type === "prayer") return <div className="companion-placeholder"><p>Prayer space</p><span>{companionText(config, "content") || `${COMPANION_LIBRARY[type].label} will live here in a future release.`}</span></div>;
  return <div className="companion-copy"><p>{companionText(config, "content") || companionText(config, "note")}</p></div>;
}

export function ParticipantCompanion({ companion, current, mode, preview = false, route, notice, error }: { companion: CompanionRuntimeData; current: CourseSectionLocation; mode: "individual" | "group"; preview?: boolean; route: { slug: string; moduleKey: string; lessonKey: string; sectionKey: string }; notice?: string; error?: string }) {
  const modules = companion.modules.filter((module) => moduleApplies(module, { moduleId: current.section.module_id, lessonId: current.section.lesson_id, sectionId: current.section.id })).filter((module) => preview || module.audience === "personal" || module.audience === "group" && mode === "group" && companion.hasGroupContext);
  return <aside className="participant-group-companion"><CompanionPolling enabled={!preview && modules.some((module) => module.module_type === "chat" || module.module_type === "video_call")}/><details><summary><span>Companion</span><small>{modules.length} available</small></summary><div className="participant-companion-intro"><p>{mode === "group" ? "Personal + Group" : "Personal"}</p><span>Support for this part of your Course</span></div>{notice && <p className="companion-notice" role="status">{notice}</p>}{error && <p className="companion-notice is-error" role="alert">{error}</p>}{modules.map((module) => <section className={`participant-companion-module is-${module.module_type}`} key={module.id}><header><small>{module.audience}</small><h2>{module.display_title}</h2></header><ModuleBody module={module} companion={companion} preview={preview} route={route}/></section>)}{!modules.length && <p className="companion-empty">No Companion items are assigned to this Page yet.</p>}</details></aside>;
}
