import { COMPANION_LIBRARY, companionLines, companionModuleAvailable, companionText, companionType, moduleApplies } from "@/lib/experiences/builder/companion";
import type { CompanionRuntimeData, ResolvedCompanionModule } from "@/lib/experiences/builder/companion-data";
import type { CourseSectionLocation } from "./CourseNavigator";
import { CompanionPolling, GroupChatExperience, VideoCallExperience } from "./LiveCompanionInteractions";
import { PersonalNotesExperience } from "./PersonalNotesExperience";

function ModuleBody({ module, companion, preview, route, location, noteSaved }: { module: ResolvedCompanionModule; companion: CompanionRuntimeData; preview: boolean; route: { slug: string; moduleKey: string; lessonKey: string; sectionKey: string; cohortId?: string | null }; location: string; noteSaved: boolean }) {
  const type = companionType(module.module_type); if (!type) return null;
  const config = module.effective_configuration;
  if (type === "personal_notes") {
    return preview ? <div className="companion-placeholder"><p>Private notebook</p><span>Participant notes are never loaded in Admin Preview.</span></div> : <PersonalNotesExperience module={module} route={route} participantId={companion.currentParticipantId} location={location} saved={noteSaved}/>;
  }
  if (type === "resources" || type === "shared_resources") return module.resources.length ? <ul className="companion-resources">{module.resources.map((resource) => <li key={resource.id}><a href={resource.downloadUrl} target="_blank" rel="noreferrer"><strong>{resource.title}</strong><span>{resource.description || resource.originalFilename || "Open resource"}</span></a></li>)}</ul> : <p className="companion-empty">Resources will appear here when they are added.</p>;
  if (type === "action_steps") return <ul className="companion-checklist">{companionLines(config).map((item) => <li key={item}><span aria-hidden="true">○</span>{item}</li>)}</ul>;
  if (type === "video_call") return preview ? <div className="companion-placeholder"><p>Video Call preview</p><span>The configured meeting link opens in the provider browser or app.</span></div> : <VideoCallExperience module={module}/>;
  if (type === "next_gathering") { const url = companionText(config, "action_url"); return <div className="companion-detail">{companionText(config, "date") && <strong>{companionText(config, "date")} {companionText(config, "time")}</strong>}<span>{companionText(config, "location")}</span><p>{companionText(config, "note")}</p>{url && <a href={url} target="_blank" rel="noreferrer">{companionText(config, "action_label") || "View details"}</a>}</div>; }
  if (type === "facilitator") return <div className="companion-person"><span aria-hidden="true">{(companionText(config, "name") || "Guide")[0]}</span><div><strong>{companionText(config, "name") || "Your guide"}</strong><small>{companionText(config, "role")}</small><p>{companionText(config, "note")}</p></div></div>;
  if (type === "group_members") return companion.cohortMembers.length ? <ul className="companion-members">{companion.cohortMembers.map((member) => <li key={member.id}><span aria-hidden="true">{member.name[0]}</span><div><strong>{member.name}</strong><small>{member.role}</small></div></li>)}</ul> : <p className="companion-empty">Cohort members will appear when this Course is opened through an active Cohort.</p>;
  if (type === "custom_link") { const url = companionText(config, "url"); return <div className="companion-detail"><p>{companionText(config, "content")}</p>{url && <a className="companion-action" href={url} target="_blank" rel="noreferrer">{companionText(config, "button_label") || "Open link"}</a>}</div>; }
  if (type === "chat") return preview ? <div className="companion-placeholder"><p>Cohort Chat preview</p><span>Private Cohort messages are never loaded in Admin Preview.</span></div> : <GroupChatExperience module={module} route={route} messages={module.chat_messages} currentParticipantId={companion.currentParticipantId}/>;
  if (type === "prayer") return <div className="companion-placeholder"><p>Prayer space</p><span>{companionText(config, "content") || `${COMPANION_LIBRARY[type].label} will live here in a future release.`}</span></div>;
  return <div className="companion-copy"><p>{companionText(config, "content") || companionText(config, "note")}</p></div>;
}

export function ParticipantCompanion({ companion, current, preview = false, route, notice, error }: { companion: CompanionRuntimeData; current: CourseSectionLocation; preview?: boolean; route: { slug: string; moduleKey: string; lessonKey: string; sectionKey: string; cohortId?: string | null }; notice?: string; error?: string }) {
  const modules = companion.modules
    .filter((module) => moduleApplies(module, { moduleId: current.section.module_id, lessonId: current.section.lesson_id, sectionId: current.section.id }))
    .filter((module) => companionModuleAvailable(module, companion.hasCohortContext, companion.currentMemberRole, preview));
  const location = [current.moduleTitle, current.lessonTitle, current.section.title].filter(Boolean).join(" · ");
  return <aside className="participant-group-companion" aria-label={`Companion · ${companion.contextLabel}`}><CompanionPolling enabled={!preview && modules.some((module) => module.module_type === "chat")}/><div className="participant-companion-content"><header className="participant-companion-intro"><p>Companion</p><strong>{companion.contextLabel}</strong><span>{companion.hasCohortContext ? "Personal + Cohort tools" : "Personal Course tools"}</span></header>{notice && <p className="companion-notice" role="status">{notice}</p>}{error && <p className="companion-notice is-error" role="alert">{error}</p>}{modules.map((module) => <section className={`participant-companion-module is-${module.module_type}`} key={module.id}><header><h2>{module.display_title}</h2></header><ModuleBody module={module} companion={companion} preview={preview} route={route} location={location} noteSaved={notice === "Note saved"}/></section>)}{!modules.length && <div className="participant-companion-empty"><strong>Nothing here yet</strong><p>No Companion items are available in this context.</p></div>}</div></aside>;
}
