/* eslint-disable react/no-children-prop -- boolean curriculum-descendant signal, not React content */
import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminPageHeader, AdminShell } from "@/components/admin/AdminShell";
import { requireAdmin } from "@/lib/admin/auth";
import { formatDate, humanize } from "@/lib/admin/format";
import { getExperienceStructure } from "@/lib/experiences/builder/data";
import type { BuilderLesson, BuilderModule, BuilderSection, RequirementLevel } from "@/lib/experiences/builder/types";
import { createLessonAction, createModuleAction, createSectionAction, deleteAction, moveSectionAction, reorderAction, updateLessonAction, updateModuleAction, updateSectionAction } from "./actions";

const requirementOptions: RequirementLevel[] = ["required", "recommended", "optional"];
const lessonCompletion = ["view", "manual", "blocks_complete", "response_submitted"];
const sectionCompletion = ["all_required_blocks", "view", "manual", "response_submitted"];
const rendererModes = ["builder", "hybrid", "custom", "route_handoff"];
type Route = { experienceId: string; versionId: string };

function Requirements({ value = "required" }: { value?: string }) { return <label>Requirement<select name="requirement_level" defaultValue={value}>{requirementOptions.map(option => <option key={option} value={option}>{humanize(option)}</option>)}</select></label>; }
function OrderControls({ route, kind, id, first, last, editable }: { route: Route; kind: "module" | "lesson" | "section"; id: string; first: boolean; last: boolean; editable: boolean }) {
  if (!editable) return null;
  return <span className="curriculum-order"><form action={reorderAction.bind(null, route.experienceId, route.versionId, kind, id, "up")}><button type="submit" disabled={first} aria-label={`Move ${kind} up`}>↑</button></form><form action={reorderAction.bind(null, route.experienceId, route.versionId, kind, id, "down")}><button type="submit" disabled={last} aria-label={`Move ${kind} down`}>↓</button></form></span>;
}
function DeleteControl({ route, kind, id, children }: { route: Route; kind: "module" | "lesson" | "section"; id: string; children?: boolean }) {
  return <form action={deleteAction.bind(null, route.experienceId, route.versionId, kind, id)} className="curriculum-delete"><label><input type="checkbox" name="confirm_delete" value="yes" required/> Confirm delete{children ? " after removing child curriculum" : ""}</label><button type="submit">Delete {kind}</button></form>;
}
function SectionEditor({ section, route, lessons, editable, index, count }: { section: BuilderSection; route: Route; lessons: BuilderLesson[]; editable: boolean; index: number; count: number }) {
  return <article className="curriculum-section"><header><div><strong>{section.title}</strong><span className="curriculum-key">{section.section_key}</span></div><div className="curriculum-badges"><span>{humanize(section.requirement_level)}</span><span>{humanize(section.renderer_mode)}</span><OrderControls route={route} kind="section" id={section.id} first={index === 0} last={index === count - 1} editable={editable}/></div></header>{section.description && <p>{section.description}</p>}<Link className="curriculum-layout-link" href={`/admin/trainings/${route.experienceId}/versions/${route.versionId}/sections/${section.id}/layout`}>{editable ? "Configure Layout" : "View Layout"}</Link>{editable && <details><summary>Edit Section</summary><form action={updateSectionAction.bind(null, route.experienceId, route.versionId, section.id)} className="admin-form curriculum-form"><label>Title<input name="title" defaultValue={section.title} maxLength={200} required/></label><label>Stable key<input name="section_key" defaultValue={section.section_key} maxLength={80} required/></label><label className="is-wide">Description<textarea name="description" defaultValue={section.description ?? ""} maxLength={3000}/></label><Requirements value={section.requirement_level}/><label>Renderer<select name="renderer_mode" defaultValue={section.renderer_mode}>{rendererModes.map(option => <option key={option} value={option}>{humanize(option)}</option>)}</select></label><label>Approved renderer key<input name="custom_renderer_key" defaultValue={section.custom_renderer_key ?? ""} maxLength={120}/></label><label>Completion<select name="completion_rule" defaultValue={section.completion_rule}>{sectionCompletion.map(option => <option key={option} value={option}>{humanize(option)}</option>)}</select></label><button className="admin-primary" type="submit">Save Section</button></form><div className="curriculum-secondary-actions">{lessons.length > 1 && <form action={moveSectionAction.bind(null, route.experienceId, route.versionId, section.id)}><label>Move to Lesson<select name="target_lesson_id" defaultValue={section.lesson_id}>{lessons.map(lesson => <option key={lesson.id} value={lesson.id}>{lesson.title}</option>)}</select></label><button type="submit">Move Section</button></form>}<DeleteControl route={route} kind="section" id={section.id}/></div></details>}</article>;
}
function LessonEditor({ lesson, route, allLessons, editable, index, count }: { lesson: BuilderLesson; route: Route; allLessons: BuilderLesson[]; editable: boolean; index: number; count: number }) {
  return <details className="curriculum-lesson" open><summary><span><strong>{lesson.title}</strong><small>{lesson.lesson_key} · {lesson.sections.length} Section{lesson.sections.length === 1 ? "" : "s"}</small></span><span className="curriculum-badges"><span>{humanize(lesson.requirement_level)}</span><OrderControls route={route} kind="lesson" id={lesson.id} first={index === 0} last={index === count - 1} editable={editable}/></span></summary>{lesson.description && <p>{lesson.description}</p>}{editable && <details className="curriculum-edit"><summary>Edit Lesson</summary><form action={updateLessonAction.bind(null, route.experienceId, route.versionId, lesson.id)} className="admin-form curriculum-form"><label>Title<input name="title" defaultValue={lesson.title} required maxLength={200}/></label><label>Stable key<input name="lesson_key" defaultValue={lesson.lesson_key} required maxLength={80}/></label><label className="is-wide">Description<textarea name="description" defaultValue={lesson.description ?? ""} maxLength={3000}/></label><Requirements value={lesson.requirement_level}/><label>Completion<select name="completion_rule" defaultValue={lesson.completion_rule}>{lessonCompletion.map(option => <option key={option} value={option}>{humanize(option)}</option>)}</select></label><button className="admin-primary" type="submit">Save Lesson</button></form><DeleteControl route={route} kind="lesson" id={lesson.id} children={lesson.sections.length > 0}/></details>}<div className="curriculum-sections">{lesson.sections.map((section, sectionIndex) => <SectionEditor key={section.id} section={section} route={route} lessons={allLessons} editable={editable} index={sectionIndex} count={lesson.sections.length}/>)}{!lesson.sections.length && <p className="curriculum-empty">Add the first participant-facing Section.</p>}</div>{editable && <details className="curriculum-add"><summary>+ Add Section</summary><form action={createSectionAction.bind(null, route.experienceId, route.versionId, lesson.id)} className="admin-form curriculum-form"><label>Title<input name="title" required maxLength={200}/></label><label>Key <small>(generated if blank)</small><input name="section_key" maxLength={80}/></label><label className="is-wide">Description<textarea name="description" maxLength={3000}/></label><Requirements/><label>Renderer<select name="renderer_mode" defaultValue="builder">{rendererModes.map(option => <option key={option} value={option}>{humanize(option)}</option>)}</select></label><label>Approved renderer key<input name="custom_renderer_key" maxLength={120}/></label><label>Completion<select name="completion_rule" defaultValue="all_required_blocks">{sectionCompletion.map(option => <option key={option} value={option}>{humanize(option)}</option>)}</select></label><button className="admin-primary" type="submit">Create Section</button></form></details>}</details>;
}
function ModuleEditor({ module, route, allLessons, editable, index, count }: { module: BuilderModule; route: Route; allLessons: BuilderLesson[]; editable: boolean; index: number; count: number }) {
  return <details className="curriculum-module" open><summary><span><strong>{module.title}</strong><small>{module.module_key} · {module.lessons.length} Lesson{module.lessons.length === 1 ? "" : "s"}</small></span><span className="curriculum-badges"><span>{humanize(module.requirement_level)}</span><OrderControls route={route} kind="module" id={module.id} first={index === 0} last={index === count - 1} editable={editable}/></span></summary>{module.description && <p>{module.description}</p>}{editable && <details className="curriculum-edit"><summary>Edit Module</summary><form action={updateModuleAction.bind(null, route.experienceId, route.versionId, module.id)} className="admin-form curriculum-form"><label>Title<input name="title" defaultValue={module.title} required maxLength={200}/></label><label>Stable key<input name="module_key" defaultValue={module.module_key} required maxLength={80}/></label><label className="is-wide">Description<textarea name="description" defaultValue={module.description ?? ""} maxLength={3000}/></label><Requirements value={module.requirement_level}/><button className="admin-primary" type="submit">Save Module</button></form><DeleteControl route={route} kind="module" id={module.id} children={module.lessons.length > 0}/></details>}<div className="curriculum-lessons">{module.lessons.map((lesson, lessonIndex) => <LessonEditor key={lesson.id} lesson={lesson} route={route} allLessons={allLessons} editable={editable} index={lessonIndex} count={module.lessons.length}/>)}{!module.lessons.length && <p className="curriculum-empty">Add the first activity or lesson.</p>}</div>{editable && <details className="curriculum-add"><summary>+ Add Lesson</summary><form action={createLessonAction.bind(null, route.experienceId, route.versionId, module.id)} className="admin-form curriculum-form"><label>Title<input name="title" required maxLength={200}/></label><label>Key <small>(generated if blank)</small><input name="lesson_key" maxLength={80}/></label><label className="is-wide">Description<textarea name="description" maxLength={3000}/></label><Requirements/><label>Completion<select name="completion_rule" defaultValue="view">{lessonCompletion.map(option => <option key={option} value={option}>{humanize(option)}</option>)}</select></label><button className="admin-primary" type="submit">Create Lesson</button></form></details>}</details>;
}

export default async function Page({ params, searchParams }: { params: Promise<Route>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const admin = await requireAdmin();
  const route = await params;
  const notice = await searchParams;
  let structure;
  try { structure = await getExperienceStructure(route.experienceId, route.versionId); } catch { notFound(); }
  const { experience, version, modules } = structure;
  const editable = version.status === "draft";
  const allLessons = modules.flatMap(module => module.lessons);
  const customEmpty = experience.delivery_mode === "custom_code" && modules.length === 0;
  return <AdminShell admin={admin}><AdminPageHeader eyebrow="Curriculum workspace" title={version.title} description={`${experience.name} · Version ${version.version_label}`} action={<Link className="admin-secondary-link" href={`/admin/trainings/${experience.id}#versions`}>Back to Experience</Link>}/>{notice.error && <p className="admin-form-message" role="alert">{notice.error}</p>}{notice.saved && <p className="admin-form-message is-success" role="status">{notice.saved}</p>}<section className="admin-detail-meta curriculum-version-meta"><div><span>Version</span><strong>{version.version_label}</strong></div><div><span>Status</span><strong>{humanize(version.status)}</strong></div><div><span>Release</span><strong>{humanize(version.release_type)}</strong></div><div><span>Theme pin</span><strong>{version.theme_id ? "Pinned" : "Experience default"}</strong></div><div><span>Based on</span><strong>{version.based_on_version_id ? "Metadata reference" : "None"}</strong></div><div><span>Published</span><strong>{formatDate(version.published_at)}</strong></div></section>{!editable && <p className="curriculum-readonly">This version is immutable. Create a new draft version to make curriculum changes. Draft creation currently copies metadata only.</p>}{customEmpty && <section className="admin-empty-state"><h2>Source-controlled custom runtime</h2><p>This Experience uses a source-controlled custom runtime. Generic curriculum structure is optional and has not been added.</p></section>}{(!customEmpty || editable) && <section className="curriculum-workspace"><header><div><p className="admin-kicker">Version structure</p><h2>Curriculum hierarchy</h2></div><span>{modules.length} Module{modules.length === 1 ? "" : "s"} · {allLessons.length} Lessons</span></header>{modules.map((module, index) => <ModuleEditor key={module.id} module={module} route={route} allLessons={allLessons} editable={editable} index={index} count={modules.length}/>)}{!modules.length && !customEmpty && <p className="curriculum-empty is-root">Start by adding your first Module, Week, or Stage.</p>}{editable && <details className="curriculum-add is-root"><summary>+ Add Module, Week, or Stage</summary><form action={createModuleAction.bind(null, route.experienceId, route.versionId)} className="admin-form curriculum-form"><label>Title<input name="title" required maxLength={200}/></label><label>Key <small>(generated if blank)</small><input name="module_key" maxLength={80}/></label><label className="is-wide">Description<textarea name="description" maxLength={3000}/></label><Requirements/><button className="admin-primary" type="submit">Create Module</button></form></details>}</section>}</AdminShell>;
}
