import Link from "next/link";
import { AdminPageHeader, AdminShell } from "@/components/admin/AdminShell";
import { requireAdmin } from "@/lib/admin/auth";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import { createCohortAction } from "./actions";

export default async function Page() {
  const admin = await requireAdmin(); const db = createAdminSupabaseClient();
  const [cohorts, experiences, memberships] = await Promise.all([db.from("cohorts").select("id,name,status,experience_id,start_date,end_date").order("created_at", { ascending: false }), db.from("experiences").select("id,name,current_published_version_id").not("current_published_version_id", "is", null).order("name"), db.from("cohort_memberships").select("cohort_id,membership_role,status").eq("status", "active")]);
  const courses = new Map((experiences.data ?? []).map((course) => [course.id, course.name])); const people = memberships.data ?? [];
  return <AdminShell admin={admin}><AdminPageHeader eyebrow="Experiences" title="Cohorts" description="Create and manage Course-linked Cohorts, members, and facilitators."/><section className="admin-panel group-setup-create"><p className="admin-kicker">New Cohort</p><h2>Create Cohort</h2><form action={createCohortAction}><label>Cohort name<input name="name" required maxLength={200}/></label><label>Training / Course<select name="experience_id" required defaultValue=""><option value="" disabled>Choose a Course</option>{(experiences.data ?? []).map((course) => <option value={course.id} key={course.id}>{course.name}</option>)}</select></label><label>Start date<input type="date" name="start_date"/></label><label>End date<input type="date" name="end_date"/></label><label>Status<select name="status" defaultValue="active"><option value="draft">Draft</option><option value="open">Open</option><option value="active">Active</option></select></label><button className="admin-primary">Create Cohort</button></form></section><section className="admin-panel"><div className="admin-table-wrap"><table><thead><tr><th>Cohort</th><th>Course</th><th>Status</th><th>Dates</th><th>Leaders</th><th>Members</th><th>Actions</th></tr></thead><tbody>{(cohorts.data ?? []).map((cohort) => { const active = people.filter((row) => row.cohort_id === cohort.id); return <tr key={cohort.id}><td><Link href={`/admin/cohorts/${cohort.id}`}><strong>{cohort.name}</strong></Link></td><td>{courses.get(cohort.experience_id) ?? "Course"}</td><td>{cohort.status}</td><td>{cohort.start_date || "—"}{cohort.end_date ? ` – ${cohort.end_date}` : ""}</td><td>{active.filter((row) => row.membership_role === "facilitator").length}</td><td>{active.length}</td><td><Link href={`/admin/cohorts/${cohort.id}`}>Edit Cohort →</Link></td></tr>; })}{!cohorts.data?.length && <tr><td colSpan={7}>No Cohorts yet.</td></tr>}</tbody></table></div></section></AdminShell>;
}
